// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/alert.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Alert_AlertType int32

const (
	Alert_ALERT_TYPE_UNSPECIFIED Alert_AlertType = 0 // Unset enum
	Alert_ALERT_TYPE_INFORMATION Alert_AlertType = 1
	Alert_ALERT_TYPE_WARNING     Alert_AlertType = 2
	Alert_ALERT_TYPE_CRITICAL    Alert_AlertType = 3
	Alert_ALERT_TYPE_ERROR       Alert_AlertType = 4
	Alert_ALERT_TYPE_FATAL       Alert_AlertType = 5
	Alert_ALERT_TYPE_MODE_CHANGE Alert_AlertType = 6
)

// Enum value maps for Alert_AlertType.
var (
	Alert_AlertType_name = map[int32]string{
		0: "ALERT_TYPE_UNSPECIFIED",
		1: "ALERT_TYPE_INFORMATION",
		2: "ALERT_TYPE_WARNING",
		3: "ALERT_TYPE_CRITICAL",
		4: "ALERT_TYPE_ERROR",
		5: "ALERT_TYPE_FATAL",
		6: "ALERT_TYPE_MODE_CHANGE",
	}
	Alert_AlertType_value = map[string]int32{
		"ALERT_TYPE_UNSPECIFIED": 0,
		"ALERT_TYPE_INFORMATION": 1,
		"ALERT_TYPE_WARNING":     2,
		"ALERT_TYPE_CRITICAL":    3,
		"ALERT_TYPE_ERROR":       4,
		"ALERT_TYPE_FATAL":       5,
		"ALERT_TYPE_MODE_CHANGE": 6,
	}
)

func (x Alert_AlertType) Enum() *Alert_AlertType {
	p := new(Alert_AlertType)
	*p = x
	return p
}

func (x Alert_AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alert_AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_alert_proto_enumTypes[0].Descriptor()
}

func (Alert_AlertType) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_alert_proto_enumTypes[0]
}

func (x Alert_AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Alert_AlertType.Descriptor instead.
func (Alert_AlertType) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDescGZIP(), []int{0, 0}
}

type Alert_AlertStatus int32

const (
	Alert_ALERT_STATUS_UNSPECIFIED Alert_AlertStatus = 0 // Unset enum
	Alert_ALERT_STATUS_ACTIVE      Alert_AlertStatus = 1
	Alert_ALERT_STATUS_ACKNOWLEDGE Alert_AlertStatus = 2
	Alert_ALERT_STATUS_REJECT      Alert_AlertStatus = 3
	Alert_ALERT_STATUS_IGNORE      Alert_AlertStatus = 4
	Alert_ALERT_STATUS_CLEAR       Alert_AlertStatus = 5
)

// Enum value maps for Alert_AlertStatus.
var (
	Alert_AlertStatus_name = map[int32]string{
		0: "ALERT_STATUS_UNSPECIFIED",
		1: "ALERT_STATUS_ACTIVE",
		2: "ALERT_STATUS_ACKNOWLEDGE",
		3: "ALERT_STATUS_REJECT",
		4: "ALERT_STATUS_IGNORE",
		5: "ALERT_STATUS_CLEAR",
	}
	Alert_AlertStatus_value = map[string]int32{
		"ALERT_STATUS_UNSPECIFIED": 0,
		"ALERT_STATUS_ACTIVE":      1,
		"ALERT_STATUS_ACKNOWLEDGE": 2,
		"ALERT_STATUS_REJECT":      3,
		"ALERT_STATUS_IGNORE":      4,
		"ALERT_STATUS_CLEAR":       5,
	}
)

func (x Alert_AlertStatus) Enum() *Alert_AlertStatus {
	p := new(Alert_AlertStatus)
	*p = x
	return p
}

func (x Alert_AlertStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alert_AlertStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_alert_proto_enumTypes[1].Descriptor()
}

func (Alert_AlertStatus) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_alert_proto_enumTypes[1]
}

func (x Alert_AlertStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Alert_AlertStatus.Descriptor instead.
func (Alert_AlertStatus) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDescGZIP(), []int{0, 1}
}

type Alert_DiscretePriority int32

const (
	Alert_DISCRETE_PRIORITY_UNSPECIFIED Alert_DiscretePriority = 0 // Alert priority not set
	Alert_DISCRETE_PRIORITY_LOW         Alert_DiscretePriority = 1 // Low alert priority
	Alert_DISCRETE_PRIORITY_MEDIUM      Alert_DiscretePriority = 2 // Medium alert priority
	Alert_DISCRETE_PRIORITY_HIGH        Alert_DiscretePriority = 3 // High alert priority
)

// Enum value maps for Alert_DiscretePriority.
var (
	Alert_DiscretePriority_name = map[int32]string{
		0: "DISCRETE_PRIORITY_UNSPECIFIED",
		1: "DISCRETE_PRIORITY_LOW",
		2: "DISCRETE_PRIORITY_MEDIUM",
		3: "DISCRETE_PRIORITY_HIGH",
	}
	Alert_DiscretePriority_value = map[string]int32{
		"DISCRETE_PRIORITY_UNSPECIFIED": 0,
		"DISCRETE_PRIORITY_LOW":         1,
		"DISCRETE_PRIORITY_MEDIUM":      2,
		"DISCRETE_PRIORITY_HIGH":        3,
	}
)

func (x Alert_DiscretePriority) Enum() *Alert_DiscretePriority {
	p := new(Alert_DiscretePriority)
	*p = x
	return p
}

func (x Alert_DiscretePriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alert_DiscretePriority) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_alert_proto_enumTypes[2].Descriptor()
}

func (Alert_DiscretePriority) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_alert_proto_enumTypes[2]
}

func (x Alert_DiscretePriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Alert_DiscretePriority.Descriptor instead.
func (Alert_DiscretePriority) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDescGZIP(), []int{0, 2}
}

// [START messages]
type Alert struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AlertId     *string                `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3,oneof" json:"alert_id,omitempty"`                                                           // ULID for the message
	AlertType   *Alert_AlertType       `protobuf:"varint,2,opt,name=alert_type,json=alertType,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Alert_AlertType,oneof" json:"alert_type,omitempty"` // Type of alert message
	Status      *Alert_AlertStatus     `protobuf:"varint,3,opt,name=status,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Alert_AlertStatus,oneof" json:"status,omitempty"`                      // State of the information in this message
	Description *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`                                                                  // Description of the alert (normally displayed on a GUI)
	// Types that are valid to be assigned to LocationOneof:
	//
	//	*Alert_RangeBearing
	//	*Alert_Location
	LocationOneof         isAlert_LocationOneof   `protobuf_oneof:"location_oneof"`
	RegionId              *string                 `protobuf:"bytes,7,opt,name=region_id,json=regionId,proto3,oneof" json:"region_id,omitempty"`                                            // ULID of the region the alert is from
	Priority              *Alert_DiscretePriority `protobuf:"varint,8,opt,name=priority,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Alert_DiscretePriority,oneof" json:"priority,omitempty"` // Priority of the alert
	Ranking               *float32                `protobuf:"fixed32,9,opt,name=ranking,proto3,oneof" json:"ranking,omitempty"`                                                            // 0-1
	Confidence            *float32                `protobuf:"fixed32,10,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`                                                     // Confidence (0-1) that the alert is not a false-alarm
	AssociatedFile        []*AssociatedFile       `protobuf:"bytes,11,rep,name=associated_file,json=associatedFile,proto3" json:"associated_file,omitempty"`                               // URL linking to any files associated with the alert
	AssociatedDetection   []*AssociatedDetection  `protobuf:"bytes,12,rep,name=associated_detection,json=associatedDetection,proto3" json:"associated_detection,omitempty"`                // Detections associated with the alert
	AdditionalInformation *string                 `protobuf:"bytes,13,opt,name=additional_information,json=additionalInformation,proto3,oneof" json:"additional_information,omitempty"`    // Any additional information that may be useful for the alert consumer
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetAlertId() string {
	if x != nil && x.AlertId != nil {
		return *x.AlertId
	}
	return ""
}

func (x *Alert) GetAlertType() Alert_AlertType {
	if x != nil && x.AlertType != nil {
		return *x.AlertType
	}
	return Alert_ALERT_TYPE_UNSPECIFIED
}

func (x *Alert) GetStatus() Alert_AlertStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Alert_ALERT_STATUS_UNSPECIFIED
}

func (x *Alert) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Alert) GetLocationOneof() isAlert_LocationOneof {
	if x != nil {
		return x.LocationOneof
	}
	return nil
}

func (x *Alert) GetRangeBearing() *RangeBearing {
	if x != nil {
		if x, ok := x.LocationOneof.(*Alert_RangeBearing); ok {
			return x.RangeBearing
		}
	}
	return nil
}

func (x *Alert) GetLocation() *Location {
	if x != nil {
		if x, ok := x.LocationOneof.(*Alert_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *Alert) GetRegionId() string {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return ""
}

func (x *Alert) GetPriority() Alert_DiscretePriority {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return Alert_DISCRETE_PRIORITY_UNSPECIFIED
}

func (x *Alert) GetRanking() float32 {
	if x != nil && x.Ranking != nil {
		return *x.Ranking
	}
	return 0
}

func (x *Alert) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *Alert) GetAssociatedFile() []*AssociatedFile {
	if x != nil {
		return x.AssociatedFile
	}
	return nil
}

func (x *Alert) GetAssociatedDetection() []*AssociatedDetection {
	if x != nil {
		return x.AssociatedDetection
	}
	return nil
}

func (x *Alert) GetAdditionalInformation() string {
	if x != nil && x.AdditionalInformation != nil {
		return *x.AdditionalInformation
	}
	return ""
}

type isAlert_LocationOneof interface {
	isAlert_LocationOneof()
}

type Alert_RangeBearing struct {
	RangeBearing *RangeBearing `protobuf:"bytes,5,opt,name=range_bearing,json=rangeBearing,proto3,oneof"` // Location of the alert in Sphereical coordinates
}

type Alert_Location struct {
	Location *Location `protobuf:"bytes,6,opt,name=location,proto3,oneof"` // Location of the alert in Geo coordinates
}

func (*Alert_RangeBearing) isAlert_LocationOneof() {}

func (*Alert_Location) isAlert_LocationOneof() {}

var File_sapient_msg_bsi_flex_335_v2_0_alert_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDesc = "" +
	"\n" +
	")sapient_msg/bsi_flex_335_v2_0/alert.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a8sapient_msg/bsi_flex_335_v2_0/associated_detection.proto\x1a3sapient_msg/bsi_flex_335_v2_0/associated_file.proto\x1a,sapient_msg/bsi_flex_335_v2_0/location.proto\x1a1sapient_msg/bsi_flex_335_v2_0/range_bearing.proto\x1a\x1fsapient_msg/proto_options.proto\"\xec\v\n" +
	"\x05Alert\x12(\n" +
	"\balert_id\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x10\x01H\x01R\aalertId\x88\x01\x01\x12R\n" +
	"\n" +
	"alert_type\x18\x02 \x01(\x0e2..sapient_msg.bsi_flex_335_v2_0.Alert.AlertTypeH\x02R\talertType\x88\x01\x01\x12M\n" +
	"\x06status\x18\x03 \x01(\x0e20.sapient_msg.bsi_flex_335_v2_0.Alert.AlertStatusH\x03R\x06status\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x04R\vdescription\x88\x01\x01\x12R\n" +
	"\rrange_bearing\x18\x05 \x01(\v2+.sapient_msg.bsi_flex_335_v2_0.RangeBearingH\x00R\frangeBearing\x12E\n" +
	"\blocation\x18\x06 \x01(\v2'.sapient_msg.bsi_flex_335_v2_0.LocationH\x00R\blocation\x12(\n" +
	"\tregion_id\x18\a \x01(\tB\x06\x8a\xb5\x18\x02\x10\x01H\x05R\bregionId\x88\x01\x01\x12V\n" +
	"\bpriority\x18\b \x01(\x0e25.sapient_msg.bsi_flex_335_v2_0.Alert.DiscretePriorityH\x06R\bpriority\x88\x01\x01\x12\x1d\n" +
	"\aranking\x18\t \x01(\x02H\aR\aranking\x88\x01\x01\x12#\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x02H\bR\n" +
	"confidence\x88\x01\x01\x12V\n" +
	"\x0fassociated_file\x18\v \x03(\v2-.sapient_msg.bsi_flex_335_v2_0.AssociatedFileR\x0eassociatedFile\x12e\n" +
	"\x14associated_detection\x18\f \x03(\v22.sapient_msg.bsi_flex_335_v2_0.AssociatedDetectionR\x13associatedDetection\x12:\n" +
	"\x16additional_information\x18\r \x01(\tH\tR\x15additionalInformation\x88\x01\x01\"\xbc\x01\n" +
	"\tAlertType\x12\x1a\n" +
	"\x16ALERT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ALERT_TYPE_INFORMATION\x10\x01\x12\x16\n" +
	"\x12ALERT_TYPE_WARNING\x10\x02\x12\x17\n" +
	"\x13ALERT_TYPE_CRITICAL\x10\x03\x12\x14\n" +
	"\x10ALERT_TYPE_ERROR\x10\x04\x12\x14\n" +
	"\x10ALERT_TYPE_FATAL\x10\x05\x12\x1a\n" +
	"\x16ALERT_TYPE_MODE_CHANGE\x10\x06\"\xac\x01\n" +
	"\vAlertStatus\x12\x1c\n" +
	"\x18ALERT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ALERT_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18ALERT_STATUS_ACKNOWLEDGE\x10\x02\x12\x17\n" +
	"\x13ALERT_STATUS_REJECT\x10\x03\x12\x17\n" +
	"\x13ALERT_STATUS_IGNORE\x10\x04\x12\x16\n" +
	"\x12ALERT_STATUS_CLEAR\x10\x05\"\x8a\x01\n" +
	"\x10DiscretePriority\x12!\n" +
	"\x1dDISCRETE_PRIORITY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DISCRETE_PRIORITY_LOW\x10\x01\x12\x1c\n" +
	"\x18DISCRETE_PRIORITY_MEDIUM\x10\x02\x12\x1a\n" +
	"\x16DISCRETE_PRIORITY_HIGH\x10\x03B\x10\n" +
	"\x0elocation_oneofB\v\n" +
	"\t_alert_idB\r\n" +
	"\v_alert_typeB\t\n" +
	"\a_statusB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_region_idB\v\n" +
	"\t_priorityB\n" +
	"\n" +
	"\b_rankingB\r\n" +
	"\v_confidenceB\x19\n" +
	"\x17_additional_informationB3\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\n" +
	"AlertProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_alert_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sapient_msg_bsi_flex_335_v2_0_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_alert_proto_goTypes = []any{
	(Alert_AlertType)(0),        // 0: sapient_msg.bsi_flex_335_v2_0.Alert.AlertType
	(Alert_AlertStatus)(0),      // 1: sapient_msg.bsi_flex_335_v2_0.Alert.AlertStatus
	(Alert_DiscretePriority)(0), // 2: sapient_msg.bsi_flex_335_v2_0.Alert.DiscretePriority
	(*Alert)(nil),               // 3: sapient_msg.bsi_flex_335_v2_0.Alert
	(*RangeBearing)(nil),        // 4: sapient_msg.bsi_flex_335_v2_0.RangeBearing
	(*Location)(nil),            // 5: sapient_msg.bsi_flex_335_v2_0.Location
	(*AssociatedFile)(nil),      // 6: sapient_msg.bsi_flex_335_v2_0.AssociatedFile
	(*AssociatedDetection)(nil), // 7: sapient_msg.bsi_flex_335_v2_0.AssociatedDetection
}
var file_sapient_msg_bsi_flex_335_v2_0_alert_proto_depIdxs = []int32{
	0, // 0: sapient_msg.bsi_flex_335_v2_0.Alert.alert_type:type_name -> sapient_msg.bsi_flex_335_v2_0.Alert.AlertType
	1, // 1: sapient_msg.bsi_flex_335_v2_0.Alert.status:type_name -> sapient_msg.bsi_flex_335_v2_0.Alert.AlertStatus
	4, // 2: sapient_msg.bsi_flex_335_v2_0.Alert.range_bearing:type_name -> sapient_msg.bsi_flex_335_v2_0.RangeBearing
	5, // 3: sapient_msg.bsi_flex_335_v2_0.Alert.location:type_name -> sapient_msg.bsi_flex_335_v2_0.Location
	2, // 4: sapient_msg.bsi_flex_335_v2_0.Alert.priority:type_name -> sapient_msg.bsi_flex_335_v2_0.Alert.DiscretePriority
	6, // 5: sapient_msg.bsi_flex_335_v2_0.Alert.associated_file:type_name -> sapient_msg.bsi_flex_335_v2_0.AssociatedFile
	7, // 6: sapient_msg.bsi_flex_335_v2_0.Alert.associated_detection:type_name -> sapient_msg.bsi_flex_335_v2_0.AssociatedDetection
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_alert_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_alert_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_alert_proto != nil {
		return
	}
	file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_location_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_init()
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_alert_proto_msgTypes[0].OneofWrappers = []any{
		(*Alert_RangeBearing)(nil),
		(*Alert_Location)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_alert_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_alert_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_alert_proto_depIdxs,
		EnumInfos:         file_sapient_msg_bsi_flex_335_v2_0_alert_proto_enumTypes,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_alert_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_alert_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_alert_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_alert_proto_depIdxs = nil
}
