// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/alert_ack.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertAck_AlertAckStatus int32

const (
	AlertAck_ALERT_ACK_STATUS_UNSPECIFIED AlertAck_AlertAckStatus = 0 // Reason not set
	AlertAck_ALERT_ACK_STATUS_ACCEPTED    AlertAck_AlertAckStatus = 1 // Alert accepted
	AlertAck_ALERT_ACK_STATUS_REJECTED    AlertAck_AlertAckStatus = 2 // Alert rejected
	AlertAck_ALERT_ACK_STATUS_CANCELLED   AlertAck_AlertAckStatus = 3 // Alert cancelled
)

// Enum value maps for AlertAck_AlertAckStatus.
var (
	AlertAck_AlertAckStatus_name = map[int32]string{
		0: "ALERT_ACK_STATUS_UNSPECIFIED",
		1: "ALERT_ACK_STATUS_ACCEPTED",
		2: "ALERT_ACK_STATUS_REJECTED",
		3: "ALERT_ACK_STATUS_CANCELLED",
	}
	AlertAck_AlertAckStatus_value = map[string]int32{
		"ALERT_ACK_STATUS_UNSPECIFIED": 0,
		"ALERT_ACK_STATUS_ACCEPTED":    1,
		"ALERT_ACK_STATUS_REJECTED":    2,
		"ALERT_ACK_STATUS_CANCELLED":   3,
	}
)

func (x AlertAck_AlertAckStatus) Enum() *AlertAck_AlertAckStatus {
	p := new(AlertAck_AlertAckStatus)
	*p = x
	return p
}

func (x AlertAck_AlertAckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertAck_AlertAckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_enumTypes[0].Descriptor()
}

func (AlertAck_AlertAckStatus) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_enumTypes[0]
}

func (x AlertAck_AlertAckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertAck_AlertAckStatus.Descriptor instead.
func (AlertAck_AlertAckStatus) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDescGZIP(), []int{0, 0}
}

// [START messages]
type AlertAck struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AlertId *string                `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3,oneof" json:"alert_id,omitempty"` // ULID for the message
	// optional AlertStatus alert_status = 2 [(field_options) = {is_mandatory: true}]; // State of the information in this message
	// optional string reason = 3; // Reason why alert was not accepted
	Reason         []string                 `protobuf:"bytes,4,rep,name=reason,proto3" json:"reason,omitempty"`                                                                                                           // Reason(s) why alert was not accepted
	AlertAckStatus *AlertAck_AlertAckStatus `protobuf:"varint,5,opt,name=alert_ack_status,json=alertAckStatus,proto3,enum=sapient_msg.bsi_flex_335_v2_0.AlertAck_AlertAckStatus,oneof" json:"alert_ack_status,omitempty"` // State of the information in this message
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AlertAck) Reset() {
	*x = AlertAck{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertAck) ProtoMessage() {}

func (x *AlertAck) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertAck.ProtoReflect.Descriptor instead.
func (*AlertAck) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDescGZIP(), []int{0}
}

func (x *AlertAck) GetAlertId() string {
	if x != nil && x.AlertId != nil {
		return *x.AlertId
	}
	return ""
}

func (x *AlertAck) GetReason() []string {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *AlertAck) GetAlertAckStatus() AlertAck_AlertAckStatus {
	if x != nil && x.AlertAckStatus != nil {
		return *x.AlertAckStatus
	}
	return AlertAck_ALERT_ACK_STATUS_UNSPECIFIED
}

var File_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDesc = "" +
	"\n" +
	"-sapient_msg/bsi_flex_335_v2_0/alert_ack.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fsapient_msg/proto_options.proto\"\xfc\x02\n" +
	"\bAlertAck\x12(\n" +
	"\balert_id\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x10\x01H\x00R\aalertId\x88\x01\x01\x12\x16\n" +
	"\x06reason\x18\x04 \x03(\tR\x06reason\x12m\n" +
	"\x10alert_ack_status\x18\x05 \x01(\x0e26.sapient_msg.bsi_flex_335_v2_0.AlertAck.AlertAckStatusB\x06\x8a\xb5\x18\x02\b\x01H\x01R\x0ealertAckStatus\x88\x01\x01\"\x90\x01\n" +
	"\x0eAlertAckStatus\x12 \n" +
	"\x1cALERT_ACK_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ALERT_ACK_STATUS_ACCEPTED\x10\x01\x12\x1d\n" +
	"\x19ALERT_ACK_STATUS_REJECTED\x10\x02\x12\x1e\n" +
	"\x1aALERT_ACK_STATUS_CANCELLED\x10\x03B\v\n" +
	"\t_alert_idB\x13\n" +
	"\x11_alert_ack_statusJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04B6\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\rAlertAckProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_goTypes = []any{
	(AlertAck_AlertAckStatus)(0), // 0: sapient_msg.bsi_flex_335_v2_0.AlertAck.AlertAckStatus
	(*AlertAck)(nil),             // 1: sapient_msg.bsi_flex_335_v2_0.AlertAck
}
var file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_depIdxs = []int32{
	0, // 0: sapient_msg.bsi_flex_335_v2_0.AlertAck.alert_ack_status:type_name -> sapient_msg.bsi_flex_335_v2_0.AlertAck.AlertAckStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto != nil {
		return
	}
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_depIdxs,
		EnumInfos:         file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_enumTypes,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_depIdxs = nil
}
