// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/associated_file.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [START messages]
type AssociatedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"` // Type of file contained available at the URL
	Url           *string                `protobuf:"bytes,2,opt,name=url,proto3,oneof" json:"url,omitempty"`   // The network address of where the file can be accessed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociatedFile) Reset() {
	*x = AssociatedFile{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociatedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociatedFile) ProtoMessage() {}

func (x *AssociatedFile) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociatedFile.ProtoReflect.Descriptor instead.
func (*AssociatedFile) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDescGZIP(), []int{0}
}

func (x *AssociatedFile) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *AssociatedFile) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

var File_sapient_msg_bsi_flex_335_v2_0_associated_file_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDesc = "" +
	"\n" +
	"3sapient_msg/bsi_flex_335_v2_0/associated_file.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fsapient_msg/proto_options.proto\"a\n" +
	"\x0eAssociatedFile\x12\x1f\n" +
	"\x04type\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x00R\x04type\x88\x01\x01\x12\x1d\n" +
	"\x03url\x18\x02 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x01R\x03url\x88\x01\x01B\a\n" +
	"\x05_typeB\x06\n" +
	"\x04_urlB<\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\x13AssociatedFileProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_goTypes = []any{
	(*AssociatedFile)(nil), // 0: sapient_msg.bsi_flex_335_v2_0.AssociatedFile
}
var file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_associated_file_proto != nil {
		return
	}
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_depIdxs,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_associated_file_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_depIdxs = nil
}
