// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/associated_detection.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssociationRelation int32

const (
	AssociationRelation_ASSOCIATION_RELATION_UNSPECIFIED AssociationRelation = 0 // Unset enum
	AssociationRelation_ASSOCIATION_RELATION_NO_RELATION AssociationRelation = 1
	AssociationRelation_ASSOCIATION_RELATION_PARENT      AssociationRelation = 2
	AssociationRelation_ASSOCIATION_RELATION_CHILD       AssociationRelation = 3
	AssociationRelation_ASSOCIATION_RELATION_SIBLING     AssociationRelation = 4
)

// Enum value maps for AssociationRelation.
var (
	AssociationRelation_name = map[int32]string{
		0: "ASSOCIATION_RELATION_UNSPECIFIED",
		1: "ASSOCIATION_RELATION_NO_RELATION",
		2: "ASSOCIATION_RELATION_PARENT",
		3: "ASSOCIATION_RELATION_CHILD",
		4: "ASSOCIATION_RELATION_SIBLING",
	}
	AssociationRelation_value = map[string]int32{
		"ASSOCIATION_RELATION_UNSPECIFIED": 0,
		"ASSOCIATION_RELATION_NO_RELATION": 1,
		"ASSOCIATION_RELATION_PARENT":      2,
		"ASSOCIATION_RELATION_CHILD":       3,
		"ASSOCIATION_RELATION_SIBLING":     4,
	}
)

func (x AssociationRelation) Enum() *AssociationRelation {
	p := new(AssociationRelation)
	*p = x
	return p
}

func (x AssociationRelation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssociationRelation) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_enumTypes[0].Descriptor()
}

func (AssociationRelation) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_enumTypes[0]
}

func (x AssociationRelation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssociationRelation.Descriptor instead.
func (AssociationRelation) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDescGZIP(), []int{0}
}

// [START messages]
type AssociatedDetection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`                                                                                            // UTC timestamp the message was sent
	NodeId          *string                `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`                                                                                    // ULID for the node where the assoicated detection has originiated
	ObjectId        *string                `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"`                                                                              // ULID for the object detected in the environment
	AssociationType *AssociationRelation   `protobuf:"varint,4,opt,name=association_type,json=associationType,proto3,enum=sapient_msg.bsi_flex_335_v2_0.AssociationRelation,oneof" json:"association_type,omitempty"` // Relationship of associated detection to this message
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssociatedDetection) Reset() {
	*x = AssociatedDetection{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociatedDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociatedDetection) ProtoMessage() {}

func (x *AssociatedDetection) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociatedDetection.ProtoReflect.Descriptor instead.
func (*AssociatedDetection) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDescGZIP(), []int{0}
}

func (x *AssociatedDetection) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AssociatedDetection) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *AssociatedDetection) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

func (x *AssociatedDetection) GetAssociationType() AssociationRelation {
	if x != nil && x.AssociationType != nil {
		return *x.AssociationType
	}
	return AssociationRelation_ASSOCIATION_RELATION_UNSPECIFIED
}

var File_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDesc = "" +
	"\n" +
	"8sapient_msg/bsi_flex_335_v2_0/associated_detection.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fsapient_msg/proto_options.proto\"\xc9\x02\n" +
	"\x13AssociatedDetection\x12=\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ttimestamp\x88\x01\x01\x12&\n" +
	"\anode_id\x18\x02 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x18\x01H\x01R\x06nodeId\x88\x01\x01\x12*\n" +
	"\tobject_id\x18\x03 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x10\x01H\x02R\bobjectId\x88\x01\x01\x12b\n" +
	"\x10association_type\x18\x04 \x01(\x0e22.sapient_msg.bsi_flex_335_v2_0.AssociationRelationH\x03R\x0fassociationType\x88\x01\x01B\f\n" +
	"\n" +
	"_timestampB\n" +
	"\n" +
	"\b_node_idB\f\n" +
	"\n" +
	"_object_idB\x13\n" +
	"\x11_association_type*\xc4\x01\n" +
	"\x13AssociationRelation\x12$\n" +
	" ASSOCIATION_RELATION_UNSPECIFIED\x10\x00\x12$\n" +
	" ASSOCIATION_RELATION_NO_RELATION\x10\x01\x12\x1f\n" +
	"\x1bASSOCIATION_RELATION_PARENT\x10\x02\x12\x1e\n" +
	"\x1aASSOCIATION_RELATION_CHILD\x10\x03\x12 \n" +
	"\x1cASSOCIATION_RELATION_SIBLING\x10\x04BA\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\x18AssociatedDetectionProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_goTypes = []any{
	(AssociationRelation)(0),      // 0: sapient_msg.bsi_flex_335_v2_0.AssociationRelation
	(*AssociatedDetection)(nil),   // 1: sapient_msg.bsi_flex_335_v2_0.AssociatedDetection
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_depIdxs = []int32{
	2, // 0: sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: sapient_msg.bsi_flex_335_v2_0.AssociatedDetection.association_type:type_name -> sapient_msg.bsi_flex_335_v2_0.AssociationRelation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto != nil {
		return
	}
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_depIdxs,
		EnumInfos:         file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_enumTypes,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_depIdxs = nil
}
