// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/detection_report.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [START messages]
type DetectionReport struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ReportId *string                `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3,oneof" json:"report_id,omitempty"` // ULID for the message
	ObjectId *string                `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"` // ULID for the object detected in the environment
	TaskId   *string                `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`       // ULID of the task the ASM is currently performing
	State    *string                `protobuf:"bytes,4,opt,name=state,proto3,oneof" json:"state,omitempty"`                       // Whether a special case is in effect (e.g. object lost)
	// Types that are valid to be assigned to LocationOneof:
	//
	//	*DetectionReport_RangeBearing
	//	*DetectionReport_Location
	LocationOneof       isDetectionReport_LocationOneof                  `protobuf_oneof:"location_oneof"`
	DetectionConfidence *float32                                         `protobuf:"fixed32,7,opt,name=detection_confidence,json=detectionConfidence,proto3,oneof" json:"detection_confidence,omitempty"` // The confidence that the detection is present as a percentage (0-1)
	TrackInfo           []*DetectionReport_TrackObjectInfo               `protobuf:"bytes,8,rep,name=track_info,json=trackInfo,proto3" json:"track_info,omitempty"`                                       // Additional information about the track as defined in the ASM's registration message
	PredictionLocation  *DetectionReport_PredictedLocation               `protobuf:"bytes,9,opt,name=prediction_location,json=predictionLocation,proto3,oneof" json:"prediction_location,omitempty"`      // Location where the object is predicted to be at a future time
	ObjectInfo          []*DetectionReport_TrackObjectInfo               `protobuf:"bytes,10,rep,name=object_info,json=objectInfo,proto3" json:"object_info,omitempty"`                                   // Additional information about the detected object as defined in the ASM's registration message
	Classification      []*DetectionReport_DetectionReportClassification `protobuf:"bytes,11,rep,name=classification,proto3" json:"classification,omitempty"`                                             // Classification information about the detected object
	Behaviour           []*DetectionReport_Behaviour                     `protobuf:"bytes,12,rep,name=behaviour,proto3" json:"behaviour,omitempty"`                                                       // Behavioural information about the detected object
	AssociatedFile      []*AssociatedFile                                `protobuf:"bytes,13,rep,name=associated_file,json=associatedFile,proto3" json:"associated_file,omitempty"`                       // URLs to any additional files relating to the object which hosted on the network
	Signal              []*DetectionReport_Signal                        `protobuf:"bytes,14,rep,name=signal,proto3" json:"signal,omitempty"`                                                             // RF signal information about the detected object
	AssociatedDetection []*AssociatedDetection                           `protobuf:"bytes,15,rep,name=associated_detection,json=associatedDetection,proto3" json:"associated_detection,omitempty"`        // Other SAPIENT detections associated with this detection
	DerivedDetection    []*DetectionReport_DerivedDetection              `protobuf:"bytes,16,rep,name=derived_detection,json=derivedDetection,proto3" json:"derived_detection,omitempty"`                 // Other SAPIENT detections dervied from this detection
	// Types that are valid to be assigned to VelocityOneof:
	//
	//	*DetectionReport_EnuVelocity
	VelocityOneof isDetectionReport_VelocityOneof `protobuf_oneof:"velocity_oneof"`
	Colour        *string                         `protobuf:"bytes,22,opt,name=colour,proto3,oneof" json:"colour,omitempty"` // Colour of the object being reported
	Id            *string                         `protobuf:"bytes,23,opt,name=id,proto3,oneof" json:"id,omitempty"`         // ID of the object being reported (e.g. the tail number of aircraft)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionReport) Reset() {
	*x = DetectionReport{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReport) ProtoMessage() {}

func (x *DetectionReport) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionReport.ProtoReflect.Descriptor instead.
func (*DetectionReport) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescGZIP(), []int{0}
}

func (x *DetectionReport) GetReportId() string {
	if x != nil && x.ReportId != nil {
		return *x.ReportId
	}
	return ""
}

func (x *DetectionReport) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

func (x *DetectionReport) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *DetectionReport) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *DetectionReport) GetLocationOneof() isDetectionReport_LocationOneof {
	if x != nil {
		return x.LocationOneof
	}
	return nil
}

func (x *DetectionReport) GetRangeBearing() *RangeBearing {
	if x != nil {
		if x, ok := x.LocationOneof.(*DetectionReport_RangeBearing); ok {
			return x.RangeBearing
		}
	}
	return nil
}

func (x *DetectionReport) GetLocation() *Location {
	if x != nil {
		if x, ok := x.LocationOneof.(*DetectionReport_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *DetectionReport) GetDetectionConfidence() float32 {
	if x != nil && x.DetectionConfidence != nil {
		return *x.DetectionConfidence
	}
	return 0
}

func (x *DetectionReport) GetTrackInfo() []*DetectionReport_TrackObjectInfo {
	if x != nil {
		return x.TrackInfo
	}
	return nil
}

func (x *DetectionReport) GetPredictionLocation() *DetectionReport_PredictedLocation {
	if x != nil {
		return x.PredictionLocation
	}
	return nil
}

func (x *DetectionReport) GetObjectInfo() []*DetectionReport_TrackObjectInfo {
	if x != nil {
		return x.ObjectInfo
	}
	return nil
}

func (x *DetectionReport) GetClassification() []*DetectionReport_DetectionReportClassification {
	if x != nil {
		return x.Classification
	}
	return nil
}

func (x *DetectionReport) GetBehaviour() []*DetectionReport_Behaviour {
	if x != nil {
		return x.Behaviour
	}
	return nil
}

func (x *DetectionReport) GetAssociatedFile() []*AssociatedFile {
	if x != nil {
		return x.AssociatedFile
	}
	return nil
}

func (x *DetectionReport) GetSignal() []*DetectionReport_Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *DetectionReport) GetAssociatedDetection() []*AssociatedDetection {
	if x != nil {
		return x.AssociatedDetection
	}
	return nil
}

func (x *DetectionReport) GetDerivedDetection() []*DetectionReport_DerivedDetection {
	if x != nil {
		return x.DerivedDetection
	}
	return nil
}

func (x *DetectionReport) GetVelocityOneof() isDetectionReport_VelocityOneof {
	if x != nil {
		return x.VelocityOneof
	}
	return nil
}

func (x *DetectionReport) GetEnuVelocity() *ENUVelocity {
	if x != nil {
		if x, ok := x.VelocityOneof.(*DetectionReport_EnuVelocity); ok {
			return x.EnuVelocity
		}
	}
	return nil
}

func (x *DetectionReport) GetColour() string {
	if x != nil && x.Colour != nil {
		return *x.Colour
	}
	return ""
}

func (x *DetectionReport) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type isDetectionReport_LocationOneof interface {
	isDetectionReport_LocationOneof()
}

type DetectionReport_RangeBearing struct {
	RangeBearing *RangeBearing `protobuf:"bytes,5,opt,name=range_bearing,json=rangeBearing,proto3,oneof"` // Location of object being detected using an range-bearing coordinate system
}

type DetectionReport_Location struct {
	Location *Location `protobuf:"bytes,6,opt,name=location,proto3,oneof"` // Location of object being detected using an 'x-y-z' coordinate system
}

func (*DetectionReport_RangeBearing) isDetectionReport_LocationOneof() {}

func (*DetectionReport_Location) isDetectionReport_LocationOneof() {}

type isDetectionReport_VelocityOneof interface {
	isDetectionReport_VelocityOneof()
}

type DetectionReport_EnuVelocity struct {
	// RYPVelocity ryp_velocity = 17; // Velocity of object relative to sensor location and sensor pointing direction
	// GHCVelocity ghc_velocity = 18; // Velocity of object in global coordinates in the style of Air Traffic Management
	EnuVelocity *ENUVelocity `protobuf:"bytes,19,opt,name=enu_velocity,json=enuVelocity,proto3,oneof"` // Velocity of object as a vector in global cartesian coordinates
}

func (*DetectionReport_EnuVelocity) isDetectionReport_VelocityOneof() {}

type DetectionReport_PredictedLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PredictedLocationOneof:
	//
	//	*DetectionReport_PredictedLocation_RangeBearing
	//	*DetectionReport_PredictedLocation_Location
	PredictedLocationOneof isDetectionReport_PredictedLocation_PredictedLocationOneof `protobuf_oneof:"predicted_location_oneof"`
	PredictedTimestamp     *timestamppb.Timestamp                                     `protobuf:"bytes,3,opt,name=predicted_timestamp,json=predictedTimestamp,proto3,oneof" json:"predicted_timestamp,omitempty"` // The timestamp of when the detected object will be at the predicted location
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DetectionReport_PredictedLocation) Reset() {
	*x = DetectionReport_PredictedLocation{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionReport_PredictedLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReport_PredictedLocation) ProtoMessage() {}

func (x *DetectionReport_PredictedLocation) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionReport_PredictedLocation.ProtoReflect.Descriptor instead.
func (*DetectionReport_PredictedLocation) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DetectionReport_PredictedLocation) GetPredictedLocationOneof() isDetectionReport_PredictedLocation_PredictedLocationOneof {
	if x != nil {
		return x.PredictedLocationOneof
	}
	return nil
}

func (x *DetectionReport_PredictedLocation) GetRangeBearing() *RangeBearing {
	if x != nil {
		if x, ok := x.PredictedLocationOneof.(*DetectionReport_PredictedLocation_RangeBearing); ok {
			return x.RangeBearing
		}
	}
	return nil
}

func (x *DetectionReport_PredictedLocation) GetLocation() *Location {
	if x != nil {
		if x, ok := x.PredictedLocationOneof.(*DetectionReport_PredictedLocation_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *DetectionReport_PredictedLocation) GetPredictedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.PredictedTimestamp
	}
	return nil
}

type isDetectionReport_PredictedLocation_PredictedLocationOneof interface {
	isDetectionReport_PredictedLocation_PredictedLocationOneof()
}

type DetectionReport_PredictedLocation_RangeBearing struct {
	RangeBearing *RangeBearing `protobuf:"bytes,1,opt,name=range_bearing,json=rangeBearing,proto3,oneof"` // Predicted location of object being detected using an range-bearing coordinate system
}

type DetectionReport_PredictedLocation_Location struct {
	Location *Location `protobuf:"bytes,2,opt,name=location,proto3,oneof"` // Predicted location of object being detected using an 'x-y-z' coordinate system
}

func (*DetectionReport_PredictedLocation_RangeBearing) isDetectionReport_PredictedLocation_PredictedLocationOneof() {
}

func (*DetectionReport_PredictedLocation_Location) isDetectionReport_PredictedLocation_PredictedLocationOneof() {
}

type DetectionReport_TrackObjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`     // The type of object_info being reported (e.g. colour)
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`   // The value of the object_info being reported (e.g. red)
	Error         *float32               `protobuf:"fixed32,3,opt,name=error,proto3,oneof" json:"error,omitempty"` // Any error associated with the object_info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionReport_TrackObjectInfo) Reset() {
	*x = DetectionReport_TrackObjectInfo{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionReport_TrackObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReport_TrackObjectInfo) ProtoMessage() {}

func (x *DetectionReport_TrackObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionReport_TrackObjectInfo.ProtoReflect.Descriptor instead.
func (*DetectionReport_TrackObjectInfo) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DetectionReport_TrackObjectInfo) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *DetectionReport_TrackObjectInfo) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *DetectionReport_TrackObjectInfo) GetError() float32 {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return 0
}

type DetectionReport_DetectionReportClassification struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          *string                     `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`                   // Classification of the detected object being reported
	Confidence    *float32                    `protobuf:"fixed32,2,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`     // Confidence (0-1) that this is the correct classification of the detected object
	SubClass      []*DetectionReport_SubClass `protobuf:"bytes,3,rep,name=sub_class,json=subClass,proto3" json:"sub_class,omitempty"` // Any sub-classifications of the detected object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionReport_DetectionReportClassification) Reset() {
	*x = DetectionReport_DetectionReportClassification{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionReport_DetectionReportClassification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReport_DetectionReportClassification) ProtoMessage() {}

func (x *DetectionReport_DetectionReportClassification) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionReport_DetectionReportClassification.ProtoReflect.Descriptor instead.
func (*DetectionReport_DetectionReportClassification) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescGZIP(), []int{0, 2}
}

func (x *DetectionReport_DetectionReportClassification) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *DetectionReport_DetectionReportClassification) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *DetectionReport_DetectionReportClassification) GetSubClass() []*DetectionReport_SubClass {
	if x != nil {
		return x.SubClass
	}
	return nil
}

type DetectionReport_SubClass struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          *string                     `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`                   // Classification of the detected object being reported
	Confidence    *float32                    `protobuf:"fixed32,2,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`     // Confidence (0-1) that this is the correct classification of the detected object
	Level         *int32                      `protobuf:"varint,3,opt,name=level,proto3,oneof" json:"level,omitempty"`                // The level of sub-classification (top level is 0, the first sub-class is 1, etc.)
	SubClass      []*DetectionReport_SubClass `protobuf:"bytes,4,rep,name=sub_class,json=subClass,proto3" json:"sub_class,omitempty"` // Any sub-classifications of the detected object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionReport_SubClass) Reset() {
	*x = DetectionReport_SubClass{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionReport_SubClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReport_SubClass) ProtoMessage() {}

func (x *DetectionReport_SubClass) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionReport_SubClass.ProtoReflect.Descriptor instead.
func (*DetectionReport_SubClass) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescGZIP(), []int{0, 3}
}

func (x *DetectionReport_SubClass) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *DetectionReport_SubClass) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *DetectionReport_SubClass) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *DetectionReport_SubClass) GetSubClass() []*DetectionReport_SubClass {
	if x != nil {
		return x.SubClass
	}
	return nil
}

type DetectionReport_Behaviour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`               // Behviouar of the detected object being reported
	Confidence    *float32               `protobuf:"fixed32,2,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"` // Confidence (0-1) that this is the correct behvaiour of the detected object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionReport_Behaviour) Reset() {
	*x = DetectionReport_Behaviour{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionReport_Behaviour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReport_Behaviour) ProtoMessage() {}

func (x *DetectionReport_Behaviour) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionReport_Behaviour.ProtoReflect.Descriptor instead.
func (*DetectionReport_Behaviour) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescGZIP(), []int{0, 4}
}

func (x *DetectionReport_Behaviour) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *DetectionReport_Behaviour) GetConfidence() float32 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

type DetectionReport_Signal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Amplitude       *float32               `protobuf:"fixed32,1,opt,name=amplitude,proto3,oneof" json:"amplitude,omitempty"`                                    // Peak amplitude of the signal being reported
	StartFrequency  *float32               `protobuf:"fixed32,2,opt,name=start_frequency,json=startFrequency,proto3,oneof" json:"start_frequency,omitempty"`    // Lowest frequency of the band being reported
	CentreFrequency *float32               `protobuf:"fixed32,3,opt,name=centre_frequency,json=centreFrequency,proto3,oneof" json:"centre_frequency,omitempty"` // Centre frequency of the band being reported
	StopFrequency   *float32               `protobuf:"fixed32,4,opt,name=stop_frequency,json=stopFrequency,proto3,oneof" json:"stop_frequency,omitempty"`       // Highest frequency of the band being reported
	PulseDuration   *float32               `protobuf:"fixed32,5,opt,name=pulse_duration,json=pulseDuration,proto3,oneof" json:"pulse_duration,omitempty"`       // Pulse duration of the signal being reported
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DetectionReport_Signal) Reset() {
	*x = DetectionReport_Signal{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionReport_Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReport_Signal) ProtoMessage() {}

func (x *DetectionReport_Signal) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionReport_Signal.ProtoReflect.Descriptor instead.
func (*DetectionReport_Signal) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescGZIP(), []int{0, 5}
}

func (x *DetectionReport_Signal) GetAmplitude() float32 {
	if x != nil && x.Amplitude != nil {
		return *x.Amplitude
	}
	return 0
}

func (x *DetectionReport_Signal) GetStartFrequency() float32 {
	if x != nil && x.StartFrequency != nil {
		return *x.StartFrequency
	}
	return 0
}

func (x *DetectionReport_Signal) GetCentreFrequency() float32 {
	if x != nil && x.CentreFrequency != nil {
		return *x.CentreFrequency
	}
	return 0
}

func (x *DetectionReport_Signal) GetStopFrequency() float32 {
	if x != nil && x.StopFrequency != nil {
		return *x.StopFrequency
	}
	return 0
}

func (x *DetectionReport_Signal) GetPulseDuration() float32 {
	if x != nil && x.PulseDuration != nil {
		return *x.PulseDuration
	}
	return 0
}

type DetectionReport_DerivedDetection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`               // UTC timestamp the message was sent
	NodeId        *string                `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`       // UUID for the node where the assoicated detection has originiated
	ObjectId      *string                `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"` // ULID for the object detected in the environment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionReport_DerivedDetection) Reset() {
	*x = DetectionReport_DerivedDetection{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionReport_DerivedDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReport_DerivedDetection) ProtoMessage() {}

func (x *DetectionReport_DerivedDetection) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionReport_DerivedDetection.ProtoReflect.Descriptor instead.
func (*DetectionReport_DerivedDetection) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescGZIP(), []int{0, 6}
}

func (x *DetectionReport_DerivedDetection) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DetectionReport_DerivedDetection) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *DetectionReport_DerivedDetection) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

var File_sapient_msg_bsi_flex_335_v2_0_detection_report_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDesc = "" +
	"\n" +
	"4sapient_msg/bsi_flex_335_v2_0/detection_report.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fgoogle/protobuf/timestamp.proto\x1a3sapient_msg/bsi_flex_335_v2_0/associated_file.proto\x1a8sapient_msg/bsi_flex_335_v2_0/associated_detection.proto\x1a,sapient_msg/bsi_flex_335_v2_0/location.proto\x1a1sapient_msg/bsi_flex_335_v2_0/range_bearing.proto\x1a,sapient_msg/bsi_flex_335_v2_0/velocity.proto\x1a\x1fsapient_msg/proto_options.proto\"\xd2\x18\n" +
	"\x0fDetectionReport\x12*\n" +
	"\treport_id\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x10\x01H\x02R\breportId\x88\x01\x01\x12*\n" +
	"\tobject_id\x18\x02 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x10\x01H\x03R\bobjectId\x88\x01\x01\x12$\n" +
	"\atask_id\x18\x03 \x01(\tB\x06\x8a\xb5\x18\x02\x10\x01H\x04R\x06taskId\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x04 \x01(\tH\x05R\x05state\x88\x01\x01\x12R\n" +
	"\rrange_bearing\x18\x05 \x01(\v2+.sapient_msg.bsi_flex_335_v2_0.RangeBearingH\x00R\frangeBearing\x12E\n" +
	"\blocation\x18\x06 \x01(\v2'.sapient_msg.bsi_flex_335_v2_0.LocationH\x00R\blocation\x126\n" +
	"\x14detection_confidence\x18\a \x01(\x02H\x06R\x13detectionConfidence\x88\x01\x01\x12]\n" +
	"\n" +
	"track_info\x18\b \x03(\v2>.sapient_msg.bsi_flex_335_v2_0.DetectionReport.TrackObjectInfoR\ttrackInfo\x12v\n" +
	"\x13prediction_location\x18\t \x01(\v2@.sapient_msg.bsi_flex_335_v2_0.DetectionReport.PredictedLocationH\aR\x12predictionLocation\x88\x01\x01\x12_\n" +
	"\vobject_info\x18\n" +
	" \x03(\v2>.sapient_msg.bsi_flex_335_v2_0.DetectionReport.TrackObjectInfoR\n" +
	"objectInfo\x12t\n" +
	"\x0eclassification\x18\v \x03(\v2L.sapient_msg.bsi_flex_335_v2_0.DetectionReport.DetectionReportClassificationR\x0eclassification\x12V\n" +
	"\tbehaviour\x18\f \x03(\v28.sapient_msg.bsi_flex_335_v2_0.DetectionReport.BehaviourR\tbehaviour\x12V\n" +
	"\x0fassociated_file\x18\r \x03(\v2-.sapient_msg.bsi_flex_335_v2_0.AssociatedFileR\x0eassociatedFile\x12M\n" +
	"\x06signal\x18\x0e \x03(\v25.sapient_msg.bsi_flex_335_v2_0.DetectionReport.SignalR\x06signal\x12e\n" +
	"\x14associated_detection\x18\x0f \x03(\v22.sapient_msg.bsi_flex_335_v2_0.AssociatedDetectionR\x13associatedDetection\x12l\n" +
	"\x11derived_detection\x18\x10 \x03(\v2?.sapient_msg.bsi_flex_335_v2_0.DetectionReport.DerivedDetectionR\x10derivedDetection\x12O\n" +
	"\fenu_velocity\x18\x13 \x01(\v2*.sapient_msg.bsi_flex_335_v2_0.ENUVelocityH\x01R\venuVelocity\x12\x1b\n" +
	"\x06colour\x18\x16 \x01(\tH\bR\x06colour\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x17 \x01(\tH\tR\x02id\x88\x01\x01\x1a\xb4\x02\n" +
	"\x11PredictedLocation\x12R\n" +
	"\rrange_bearing\x18\x01 \x01(\v2+.sapient_msg.bsi_flex_335_v2_0.RangeBearingH\x00R\frangeBearing\x12E\n" +
	"\blocation\x18\x02 \x01(\v2'.sapient_msg.bsi_flex_335_v2_0.LocationH\x00R\blocation\x12P\n" +
	"\x13predicted_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x12predictedTimestamp\x88\x01\x01B\x1a\n" +
	"\x18predicted_location_oneofB\x16\n" +
	"\x14_predicted_timestamp\x1a\x8d\x01\n" +
	"\x0fTrackObjectInfo\x12\x1f\n" +
	"\x04type\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x00R\x04type\x88\x01\x01\x12!\n" +
	"\x05value\x18\x02 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x01R\x05value\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x03 \x01(\x02H\x02R\x05error\x88\x01\x01B\a\n" +
	"\x05_typeB\b\n" +
	"\x06_valueB\b\n" +
	"\x06_error\x1a\xd3\x01\n" +
	"\x1dDetectionReportClassification\x12\x1f\n" +
	"\x04type\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x00R\x04type\x88\x01\x01\x12#\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02H\x01R\n" +
	"confidence\x88\x01\x01\x12T\n" +
	"\tsub_class\x18\x03 \x03(\v27.sapient_msg.bsi_flex_335_v2_0.DetectionReport.SubClassR\bsubClassB\a\n" +
	"\x05_typeB\r\n" +
	"\v_confidence\x1a\xeb\x01\n" +
	"\bSubClass\x12\x1f\n" +
	"\x04type\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x00R\x04type\x88\x01\x01\x12#\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02H\x01R\n" +
	"confidence\x88\x01\x01\x12!\n" +
	"\x05level\x18\x03 \x01(\x05B\x06\x8a\xb5\x18\x02\b\x01H\x02R\x05level\x88\x01\x01\x12T\n" +
	"\tsub_class\x18\x04 \x03(\v27.sapient_msg.bsi_flex_335_v2_0.DetectionReport.SubClassR\bsubClassB\a\n" +
	"\x05_typeB\r\n" +
	"\v_confidenceB\b\n" +
	"\x06_level\x1ai\n" +
	"\tBehaviour\x12\x1f\n" +
	"\x04type\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x00R\x04type\x88\x01\x01\x12#\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02H\x01R\n" +
	"confidence\x88\x01\x01B\a\n" +
	"\x05_typeB\r\n" +
	"\v_confidence\x1a\xce\x02\n" +
	"\x06Signal\x12)\n" +
	"\tamplitude\x18\x01 \x01(\x02B\x06\x8a\xb5\x18\x02\b\x01H\x00R\tamplitude\x88\x01\x01\x12,\n" +
	"\x0fstart_frequency\x18\x02 \x01(\x02H\x01R\x0estartFrequency\x88\x01\x01\x126\n" +
	"\x10centre_frequency\x18\x03 \x01(\x02B\x06\x8a\xb5\x18\x02\b\x01H\x02R\x0fcentreFrequency\x88\x01\x01\x12*\n" +
	"\x0estop_frequency\x18\x04 \x01(\x02H\x03R\rstopFrequency\x88\x01\x01\x12*\n" +
	"\x0epulse_duration\x18\x05 \x01(\x02H\x04R\rpulseDuration\x88\x01\x01B\f\n" +
	"\n" +
	"_amplitudeB\x12\n" +
	"\x10_start_frequencyB\x13\n" +
	"\x11_centre_frequencyB\x11\n" +
	"\x0f_stop_frequencyB\x11\n" +
	"\x0f_pulse_duration\x1a\xcd\x01\n" +
	"\x10DerivedDetection\x12=\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ttimestamp\x88\x01\x01\x12&\n" +
	"\anode_id\x18\x02 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x18\x01H\x01R\x06nodeId\x88\x01\x01\x12*\n" +
	"\tobject_id\x18\x03 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x10\x01H\x02R\bobjectId\x88\x01\x01B\f\n" +
	"\n" +
	"_timestampB\n" +
	"\n" +
	"\b_node_idB\f\n" +
	"\n" +
	"_object_idB\x18\n" +
	"\x0elocation_oneof\x12\x06\x8a\xb5\x18\x02\b\x01B\x10\n" +
	"\x0evelocity_oneofB\f\n" +
	"\n" +
	"_report_idB\f\n" +
	"\n" +
	"_object_idB\n" +
	"\n" +
	"\b_task_idB\b\n" +
	"\x06_stateB\x17\n" +
	"\x15_detection_confidenceB\x16\n" +
	"\x14_prediction_locationB\t\n" +
	"\a_colourB\x05\n" +
	"\x03_idJ\x04\b\x11\x10\x12J\x04\b\x12\x10\x13J\x04\b\x14\x10\x15J\x04\b\x15\x10\x16B=\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\x14DetectionReportProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_goTypes = []any{
	(*DetectionReport)(nil),                               // 0: sapient_msg.bsi_flex_335_v2_0.DetectionReport
	(*DetectionReport_PredictedLocation)(nil),             // 1: sapient_msg.bsi_flex_335_v2_0.DetectionReport.PredictedLocation
	(*DetectionReport_TrackObjectInfo)(nil),               // 2: sapient_msg.bsi_flex_335_v2_0.DetectionReport.TrackObjectInfo
	(*DetectionReport_DetectionReportClassification)(nil), // 3: sapient_msg.bsi_flex_335_v2_0.DetectionReport.DetectionReportClassification
	(*DetectionReport_SubClass)(nil),                      // 4: sapient_msg.bsi_flex_335_v2_0.DetectionReport.SubClass
	(*DetectionReport_Behaviour)(nil),                     // 5: sapient_msg.bsi_flex_335_v2_0.DetectionReport.Behaviour
	(*DetectionReport_Signal)(nil),                        // 6: sapient_msg.bsi_flex_335_v2_0.DetectionReport.Signal
	(*DetectionReport_DerivedDetection)(nil),              // 7: sapient_msg.bsi_flex_335_v2_0.DetectionReport.DerivedDetection
	(*RangeBearing)(nil),                                  // 8: sapient_msg.bsi_flex_335_v2_0.RangeBearing
	(*Location)(nil),                                      // 9: sapient_msg.bsi_flex_335_v2_0.Location
	(*AssociatedFile)(nil),                                // 10: sapient_msg.bsi_flex_335_v2_0.AssociatedFile
	(*AssociatedDetection)(nil),                           // 11: sapient_msg.bsi_flex_335_v2_0.AssociatedDetection
	(*ENUVelocity)(nil),                                   // 12: sapient_msg.bsi_flex_335_v2_0.ENUVelocity
	(*timestamppb.Timestamp)(nil),                         // 13: google.protobuf.Timestamp
}
var file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_depIdxs = []int32{
	8,  // 0: sapient_msg.bsi_flex_335_v2_0.DetectionReport.range_bearing:type_name -> sapient_msg.bsi_flex_335_v2_0.RangeBearing
	9,  // 1: sapient_msg.bsi_flex_335_v2_0.DetectionReport.location:type_name -> sapient_msg.bsi_flex_335_v2_0.Location
	2,  // 2: sapient_msg.bsi_flex_335_v2_0.DetectionReport.track_info:type_name -> sapient_msg.bsi_flex_335_v2_0.DetectionReport.TrackObjectInfo
	1,  // 3: sapient_msg.bsi_flex_335_v2_0.DetectionReport.prediction_location:type_name -> sapient_msg.bsi_flex_335_v2_0.DetectionReport.PredictedLocation
	2,  // 4: sapient_msg.bsi_flex_335_v2_0.DetectionReport.object_info:type_name -> sapient_msg.bsi_flex_335_v2_0.DetectionReport.TrackObjectInfo
	3,  // 5: sapient_msg.bsi_flex_335_v2_0.DetectionReport.classification:type_name -> sapient_msg.bsi_flex_335_v2_0.DetectionReport.DetectionReportClassification
	5,  // 6: sapient_msg.bsi_flex_335_v2_0.DetectionReport.behaviour:type_name -> sapient_msg.bsi_flex_335_v2_0.DetectionReport.Behaviour
	10, // 7: sapient_msg.bsi_flex_335_v2_0.DetectionReport.associated_file:type_name -> sapient_msg.bsi_flex_335_v2_0.AssociatedFile
	6,  // 8: sapient_msg.bsi_flex_335_v2_0.DetectionReport.signal:type_name -> sapient_msg.bsi_flex_335_v2_0.DetectionReport.Signal
	11, // 9: sapient_msg.bsi_flex_335_v2_0.DetectionReport.associated_detection:type_name -> sapient_msg.bsi_flex_335_v2_0.AssociatedDetection
	7,  // 10: sapient_msg.bsi_flex_335_v2_0.DetectionReport.derived_detection:type_name -> sapient_msg.bsi_flex_335_v2_0.DetectionReport.DerivedDetection
	12, // 11: sapient_msg.bsi_flex_335_v2_0.DetectionReport.enu_velocity:type_name -> sapient_msg.bsi_flex_335_v2_0.ENUVelocity
	8,  // 12: sapient_msg.bsi_flex_335_v2_0.DetectionReport.PredictedLocation.range_bearing:type_name -> sapient_msg.bsi_flex_335_v2_0.RangeBearing
	9,  // 13: sapient_msg.bsi_flex_335_v2_0.DetectionReport.PredictedLocation.location:type_name -> sapient_msg.bsi_flex_335_v2_0.Location
	13, // 14: sapient_msg.bsi_flex_335_v2_0.DetectionReport.PredictedLocation.predicted_timestamp:type_name -> google.protobuf.Timestamp
	4,  // 15: sapient_msg.bsi_flex_335_v2_0.DetectionReport.DetectionReportClassification.sub_class:type_name -> sapient_msg.bsi_flex_335_v2_0.DetectionReport.SubClass
	4,  // 16: sapient_msg.bsi_flex_335_v2_0.DetectionReport.SubClass.sub_class:type_name -> sapient_msg.bsi_flex_335_v2_0.DetectionReport.SubClass
	13, // 17: sapient_msg.bsi_flex_335_v2_0.DetectionReport.DerivedDetection.timestamp:type_name -> google.protobuf.Timestamp
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_detection_report_proto != nil {
		return
	}
	file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_associated_detection_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_location_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_init()
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[0].OneofWrappers = []any{
		(*DetectionReport_RangeBearing)(nil),
		(*DetectionReport_Location)(nil),
		(*DetectionReport_EnuVelocity)(nil),
	}
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[1].OneofWrappers = []any{
		(*DetectionReport_PredictedLocation_RangeBearing)(nil),
		(*DetectionReport_PredictedLocation_Location)(nil),
	}
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[2].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[3].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[4].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[5].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[6].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_depIdxs,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_detection_report_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_depIdxs = nil
}
