// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/error.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [START messages]
type Error struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Packet []byte                 `protobuf:"bytes,1,opt,name=packet,proto3,oneof" json:"packet,omitempty"` // Packet which caused the error
	// optional string error_message = 2 [(field_options) = {is_mandatory: true}]; // Description of the error being reported
	ErrorMessage  []string `protobuf:"bytes,3,rep,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Description of the error being reported, this field is an array to allow multiple errors to be reported in one go
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetPacket() []byte {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *Error) GetErrorMessage() []string {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

var File_sapient_msg_bsi_flex_335_v2_0_error_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDesc = "" +
	"\n" +
	")sapient_msg/bsi_flex_335_v2_0/error.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fsapient_msg/proto_options.proto\"j\n" +
	"\x05Error\x12#\n" +
	"\x06packet\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x02\b\x01H\x00R\x06packet\x88\x01\x01\x12+\n" +
	"\rerror_message\x18\x03 \x03(\tB\x06\x8a\xb5\x18\x02\b\x01R\ferrorMessageB\t\n" +
	"\a_packetJ\x04\b\x02\x10\x03B3\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\n" +
	"ErrorProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_error_proto_goTypes = []any{
	(*Error)(nil), // 0: sapient_msg.bsi_flex_335_v2_0.Error
}
var file_sapient_msg_bsi_flex_335_v2_0_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_error_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_error_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_error_proto != nil {
		return
	}
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_error_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_error_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_error_proto_depIdxs,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_error_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_error_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_error_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_error_proto_depIdxs = nil
}
