// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/location.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationCoordinateSystem int32

const (
	LocationCoordinateSystem_LOCATION_COORDINATE_SYSTEM_UNSPECIFIED   LocationCoordinateSystem = 0 // Co-ordinate system/units not defined
	LocationCoordinateSystem_LOCATION_COORDINATE_SYSTEM_LAT_LNG_DEG_M LocationCoordinateSystem = 1 // Latitude/Longitude in decimal-degrees/metres
	LocationCoordinateSystem_LOCATION_COORDINATE_SYSTEM_LAT_LNG_RAD_M LocationCoordinateSystem = 2 // Latitude/Longitude in radians/metres
	// LOCATION_COORDINATE_SYSTEM_LAT_LNG_DEG_F = 3; // Latitude/Longitude in decimal-degrees/feet - DEPRECATED
	// LOCATION_COORDINATE_SYSTEM_LAT_LNG_RAD_F = 4; // Latitude/Longitude in radians/feet - DEPRECATED
	LocationCoordinateSystem_LOCATION_COORDINATE_SYSTEM_UTM_M LocationCoordinateSystem = 5 // UTM with altitude in metres
)

// Enum value maps for LocationCoordinateSystem.
var (
	LocationCoordinateSystem_name = map[int32]string{
		0: "LOCATION_COORDINATE_SYSTEM_UNSPECIFIED",
		1: "LOCATION_COORDINATE_SYSTEM_LAT_LNG_DEG_M",
		2: "LOCATION_COORDINATE_SYSTEM_LAT_LNG_RAD_M",
		5: "LOCATION_COORDINATE_SYSTEM_UTM_M",
	}
	LocationCoordinateSystem_value = map[string]int32{
		"LOCATION_COORDINATE_SYSTEM_UNSPECIFIED":   0,
		"LOCATION_COORDINATE_SYSTEM_LAT_LNG_DEG_M": 1,
		"LOCATION_COORDINATE_SYSTEM_LAT_LNG_RAD_M": 2,
		"LOCATION_COORDINATE_SYSTEM_UTM_M":         5,
	}
)

func (x LocationCoordinateSystem) Enum() *LocationCoordinateSystem {
	p := new(LocationCoordinateSystem)
	*p = x
	return p
}

func (x LocationCoordinateSystem) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationCoordinateSystem) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_location_proto_enumTypes[0].Descriptor()
}

func (LocationCoordinateSystem) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_location_proto_enumTypes[0]
}

func (x LocationCoordinateSystem) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationCoordinateSystem.Descriptor instead.
func (LocationCoordinateSystem) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDescGZIP(), []int{0}
}

type LocationDatum int32

const (
	LocationDatum_LOCATION_DATUM_UNSPECIFIED LocationDatum = 0 // Datum not defined
	LocationDatum_LOCATION_DATUM_WGS84_E     LocationDatum = 1 // WGS84 Ellipsoid
	LocationDatum_LOCATION_DATUM_WGS84_G     LocationDatum = 2 // WGS84 Geoid
)

// Enum value maps for LocationDatum.
var (
	LocationDatum_name = map[int32]string{
		0: "LOCATION_DATUM_UNSPECIFIED",
		1: "LOCATION_DATUM_WGS84_E",
		2: "LOCATION_DATUM_WGS84_G",
	}
	LocationDatum_value = map[string]int32{
		"LOCATION_DATUM_UNSPECIFIED": 0,
		"LOCATION_DATUM_WGS84_E":     1,
		"LOCATION_DATUM_WGS84_G":     2,
	}
)

func (x LocationDatum) Enum() *LocationDatum {
	p := new(LocationDatum)
	*p = x
	return p
}

func (x LocationDatum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationDatum) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_location_proto_enumTypes[1].Descriptor()
}

func (LocationDatum) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_location_proto_enumTypes[1]
}

func (x LocationDatum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationDatum.Descriptor instead.
func (LocationDatum) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDescGZIP(), []int{1}
}

// [START messages]
type LocationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"` // List of locations used to define a region
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationList) Reset() {
	*x = LocationList{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationList) ProtoMessage() {}

func (x *LocationList) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationList.ProtoReflect.Descriptor instead.
func (*LocationList) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDescGZIP(), []int{0}
}

func (x *LocationList) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

type Location struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	X                *float64                  `protobuf:"fixed64,1,opt,name=x,proto3,oneof" json:"x,omitempty"`                                                                                                                  // X-coordinate (normally longitude)
	Y                *float64                  `protobuf:"fixed64,2,opt,name=y,proto3,oneof" json:"y,omitempty"`                                                                                                                  // Y-coordinate (normally latitude)
	Z                *float64                  `protobuf:"fixed64,3,opt,name=z,proto3,oneof" json:"z,omitempty"`                                                                                                                  // Z-coordinate (normally altitude)
	XError           *float64                  `protobuf:"fixed64,4,opt,name=x_error,json=xError,proto3,oneof" json:"x_error,omitempty"`                                                                                          // X-coordinate error
	YError           *float64                  `protobuf:"fixed64,5,opt,name=y_error,json=yError,proto3,oneof" json:"y_error,omitempty"`                                                                                          // Y-coordinate error
	ZError           *float64                  `protobuf:"fixed64,6,opt,name=z_error,json=zError,proto3,oneof" json:"z_error,omitempty"`                                                                                          // Z-coordinate error
	CoordinateSystem *LocationCoordinateSystem `protobuf:"varint,7,opt,name=coordinate_system,json=coordinateSystem,proto3,enum=sapient_msg.bsi_flex_335_v2_0.LocationCoordinateSystem,oneof" json:"coordinate_system,omitempty"` // Coordinate system used
	Datum            *LocationDatum            `protobuf:"varint,8,opt,name=datum,proto3,enum=sapient_msg.bsi_flex_335_v2_0.LocationDatum,oneof" json:"datum,omitempty"`                                                          // Datum used
	UtmZone          *string                   `protobuf:"bytes,9,opt,name=utm_zone,json=utmZone,proto3,oneof" json:"utm_zone,omitempty"`                                                                                         // For reporting locations in an adjacent UTM zone
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Location) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Location) GetZ() float64 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *Location) GetXError() float64 {
	if x != nil && x.XError != nil {
		return *x.XError
	}
	return 0
}

func (x *Location) GetYError() float64 {
	if x != nil && x.YError != nil {
		return *x.YError
	}
	return 0
}

func (x *Location) GetZError() float64 {
	if x != nil && x.ZError != nil {
		return *x.ZError
	}
	return 0
}

func (x *Location) GetCoordinateSystem() LocationCoordinateSystem {
	if x != nil && x.CoordinateSystem != nil {
		return *x.CoordinateSystem
	}
	return LocationCoordinateSystem_LOCATION_COORDINATE_SYSTEM_UNSPECIFIED
}

func (x *Location) GetDatum() LocationDatum {
	if x != nil && x.Datum != nil {
		return *x.Datum
	}
	return LocationDatum_LOCATION_DATUM_UNSPECIFIED
}

func (x *Location) GetUtmZone() string {
	if x != nil && x.UtmZone != nil {
		return *x.UtmZone
	}
	return ""
}

var File_sapient_msg_bsi_flex_335_v2_0_location_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDesc = "" +
	"\n" +
	",sapient_msg/bsi_flex_335_v2_0/location.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fsapient_msg/proto_options.proto\"]\n" +
	"\fLocationList\x12M\n" +
	"\tlocations\x18\x01 \x03(\v2'.sapient_msg.bsi_flex_335_v2_0.LocationB\x06\x8a\xb5\x18\x02\b\x01R\tlocations\"\xf4\x03\n" +
	"\bLocation\x12\x19\n" +
	"\x01x\x18\x01 \x01(\x01B\x06\x8a\xb5\x18\x02\b\x01H\x00R\x01x\x88\x01\x01\x12\x19\n" +
	"\x01y\x18\x02 \x01(\x01B\x06\x8a\xb5\x18\x02\b\x01H\x01R\x01y\x88\x01\x01\x12\x11\n" +
	"\x01z\x18\x03 \x01(\x01H\x02R\x01z\x88\x01\x01\x12\x1c\n" +
	"\ax_error\x18\x04 \x01(\x01H\x03R\x06xError\x88\x01\x01\x12\x1c\n" +
	"\ay_error\x18\x05 \x01(\x01H\x04R\x06yError\x88\x01\x01\x12\x1c\n" +
	"\az_error\x18\x06 \x01(\x01H\x05R\x06zError\x88\x01\x01\x12q\n" +
	"\x11coordinate_system\x18\a \x01(\x0e27.sapient_msg.bsi_flex_335_v2_0.LocationCoordinateSystemB\x06\x8a\xb5\x18\x02\b\x01H\x06R\x10coordinateSystem\x88\x01\x01\x12O\n" +
	"\x05datum\x18\b \x01(\x0e2,.sapient_msg.bsi_flex_335_v2_0.LocationDatumB\x06\x8a\xb5\x18\x02\b\x01H\aR\x05datum\x88\x01\x01\x12\x1e\n" +
	"\butm_zone\x18\t \x01(\tH\bR\autmZone\x88\x01\x01B\x04\n" +
	"\x02_xB\x04\n" +
	"\x02_yB\x04\n" +
	"\x02_zB\n" +
	"\n" +
	"\b_x_errorB\n" +
	"\n" +
	"\b_y_errorB\n" +
	"\n" +
	"\b_z_errorB\x14\n" +
	"\x12_coordinate_systemB\b\n" +
	"\x06_datumB\v\n" +
	"\t_utm_zone*\xd4\x01\n" +
	"\x18LocationCoordinateSystem\x12*\n" +
	"&LOCATION_COORDINATE_SYSTEM_UNSPECIFIED\x10\x00\x12,\n" +
	"(LOCATION_COORDINATE_SYSTEM_LAT_LNG_DEG_M\x10\x01\x12,\n" +
	"(LOCATION_COORDINATE_SYSTEM_LAT_LNG_RAD_M\x10\x02\x12$\n" +
	" LOCATION_COORDINATE_SYSTEM_UTM_M\x10\x05\"\x04\b\x03\x10\x03\"\x04\b\x04\x10\x04*g\n" +
	"\rLocationDatum\x12\x1e\n" +
	"\x1aLOCATION_DATUM_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16LOCATION_DATUM_WGS84_E\x10\x01\x12\x1a\n" +
	"\x16LOCATION_DATUM_WGS84_G\x10\x02B6\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\rLocationProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_location_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sapient_msg_bsi_flex_335_v2_0_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sapient_msg_bsi_flex_335_v2_0_location_proto_goTypes = []any{
	(LocationCoordinateSystem)(0), // 0: sapient_msg.bsi_flex_335_v2_0.LocationCoordinateSystem
	(LocationDatum)(0),            // 1: sapient_msg.bsi_flex_335_v2_0.LocationDatum
	(*LocationList)(nil),          // 2: sapient_msg.bsi_flex_335_v2_0.LocationList
	(*Location)(nil),              // 3: sapient_msg.bsi_flex_335_v2_0.Location
}
var file_sapient_msg_bsi_flex_335_v2_0_location_proto_depIdxs = []int32{
	3, // 0: sapient_msg.bsi_flex_335_v2_0.LocationList.locations:type_name -> sapient_msg.bsi_flex_335_v2_0.Location
	0, // 1: sapient_msg.bsi_flex_335_v2_0.Location.coordinate_system:type_name -> sapient_msg.bsi_flex_335_v2_0.LocationCoordinateSystem
	1, // 2: sapient_msg.bsi_flex_335_v2_0.Location.datum:type_name -> sapient_msg.bsi_flex_335_v2_0.LocationDatum
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_location_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_location_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_location_proto != nil {
		return
	}
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_location_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_location_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_location_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_location_proto_depIdxs,
		EnumInfos:         file_sapient_msg_bsi_flex_335_v2_0_location_proto_enumTypes,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_location_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_location_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_location_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_location_proto_depIdxs = nil
}
