// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/proto_options.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [START messages]
type FileOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StandardVersion string                 `protobuf:"bytes,1,opt,name=standard_version,json=standardVersion,proto3" json:"standard_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_sapient_msg_proto_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_proto_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_sapient_msg_proto_options_proto_rawDescGZIP(), []int{0}
}

func (x *FileOptions) GetStandardVersion() string {
	if x != nil {
		return x.StandardVersion
	}
	return ""
}

type ValidationOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsMandatory      *bool                  `protobuf:"varint,1,opt,name=is_mandatory,json=isMandatory,proto3,oneof" json:"is_mandatory,omitempty"`
	IsUlid           *bool                  `protobuf:"varint,2,opt,name=is_ulid,json=isUlid,proto3,oneof" json:"is_ulid,omitempty"`
	IsUuid           *bool                  `protobuf:"varint,3,opt,name=is_uuid,json=isUuid,proto3,oneof" json:"is_uuid,omitempty"`
	XmlName          *string                `protobuf:"bytes,4,opt,name=xml_name,json=xmlName,proto3,oneof" json:"xml_name,omitempty"`
	XmlIsAttribute   *bool                  `protobuf:"varint,5,opt,name=xml_is_attribute,json=xmlIsAttribute,proto3,oneof" json:"xml_is_attribute,omitempty"`
	XmlIgnore        *bool                  `protobuf:"varint,6,opt,name=xml_ignore,json=xmlIgnore,proto3,oneof" json:"xml_ignore,omitempty"`
	XmlSinglyNested  *string                `protobuf:"bytes,7,opt,name=xml_singly_nested,json=xmlSinglyNested,proto3,oneof" json:"xml_singly_nested,omitempty"`
	XmlIsParentValue *bool                  `protobuf:"varint,8,opt,name=xml_is_parent_value,json=xmlIsParentValue,proto3,oneof" json:"xml_is_parent_value,omitempty"`
	EnumName         *string                `protobuf:"bytes,9,opt,name=enum_name,json=enumName,proto3,oneof" json:"enum_name,omitempty"`
	IsProtoTime      *bool                  `protobuf:"varint,10,opt,name=is_proto_time,json=isProtoTime,proto3,oneof" json:"is_proto_time,omitempty"`
	XmlTentative     *bool                  `protobuf:"varint,11,opt,name=xml_tentative,json=xmlTentative,proto3,oneof" json:"xml_tentative,omitempty"`
	IsTime           *bool                  `protobuf:"varint,12,opt,name=is_time,json=isTime,proto3,oneof" json:"is_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidationOptions) Reset() {
	*x = ValidationOptions{}
	mi := &file_sapient_msg_proto_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationOptions) ProtoMessage() {}

func (x *ValidationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_proto_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationOptions.ProtoReflect.Descriptor instead.
func (*ValidationOptions) Descriptor() ([]byte, []int) {
	return file_sapient_msg_proto_options_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationOptions) GetIsMandatory() bool {
	if x != nil && x.IsMandatory != nil {
		return *x.IsMandatory
	}
	return false
}

func (x *ValidationOptions) GetIsUlid() bool {
	if x != nil && x.IsUlid != nil {
		return *x.IsUlid
	}
	return false
}

func (x *ValidationOptions) GetIsUuid() bool {
	if x != nil && x.IsUuid != nil {
		return *x.IsUuid
	}
	return false
}

func (x *ValidationOptions) GetXmlName() string {
	if x != nil && x.XmlName != nil {
		return *x.XmlName
	}
	return ""
}

func (x *ValidationOptions) GetXmlIsAttribute() bool {
	if x != nil && x.XmlIsAttribute != nil {
		return *x.XmlIsAttribute
	}
	return false
}

func (x *ValidationOptions) GetXmlIgnore() bool {
	if x != nil && x.XmlIgnore != nil {
		return *x.XmlIgnore
	}
	return false
}

func (x *ValidationOptions) GetXmlSinglyNested() string {
	if x != nil && x.XmlSinglyNested != nil {
		return *x.XmlSinglyNested
	}
	return ""
}

func (x *ValidationOptions) GetXmlIsParentValue() bool {
	if x != nil && x.XmlIsParentValue != nil {
		return *x.XmlIsParentValue
	}
	return false
}

func (x *ValidationOptions) GetEnumName() string {
	if x != nil && x.EnumName != nil {
		return *x.EnumName
	}
	return ""
}

func (x *ValidationOptions) GetIsProtoTime() bool {
	if x != nil && x.IsProtoTime != nil {
		return *x.IsProtoTime
	}
	return false
}

func (x *ValidationOptions) GetXmlTentative() bool {
	if x != nil && x.XmlTentative != nil {
		return *x.XmlTentative
	}
	return false
}

func (x *ValidationOptions) GetIsTime() bool {
	if x != nil && x.IsTime != nil {
		return *x.IsTime
	}
	return false
}

type MessageOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	XmlMessageName   *string                `protobuf:"bytes,50001,opt,name=xml_message_name,json=xmlMessageName,proto3,oneof" json:"xml_message_name,omitempty"`
	IsSapientMessage *bool                  `protobuf:"varint,50002,opt,name=is_sapient_message,json=isSapientMessage,proto3,oneof" json:"is_sapient_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_sapient_msg_proto_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_proto_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_sapient_msg_proto_options_proto_rawDescGZIP(), []int{2}
}

func (x *MessageOptions) GetXmlMessageName() string {
	if x != nil && x.XmlMessageName != nil {
		return *x.XmlMessageName
	}
	return ""
}

func (x *MessageOptions) GetIsSapientMessage() bool {
	if x != nil && x.IsSapientMessage != nil {
		return *x.IsSapientMessage
	}
	return false
}

var file_sapient_msg_proto_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         100001,
		Name:          "sapient_msg.file_options",
		Tag:           "bytes,100001,opt,name=file_options",
		Filename:      "sapient_msg/proto_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*ValidationOptions)(nil),
		Field:         50001,
		Name:          "sapient_msg.enum_options",
		Tag:           "bytes,50001,opt,name=enum_options",
		Filename:      "sapient_msg/proto_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*ValidationOptions)(nil),
		Field:         50001,
		Name:          "sapient_msg.oneof_options",
		Tag:           "bytes,50001,opt,name=oneof_options",
		Filename:      "sapient_msg/proto_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ValidationOptions)(nil),
		Field:         50001,
		Name:          "sapient_msg.field_options",
		Tag:           "bytes,50001,opt,name=field_options",
		Filename:      "sapient_msg/proto_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         50001,
		Name:          "sapient_msg.message_options",
		Tag:           "bytes,50001,opt,name=message_options",
		Filename:      "sapient_msg/proto_options.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional sapient_msg.FileOptions file_options = 100001;
	E_FileOptions = &file_sapient_msg_proto_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional sapient_msg.ValidationOptions enum_options = 50001;
	E_EnumOptions = &file_sapient_msg_proto_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional sapient_msg.ValidationOptions oneof_options = 50001;
	E_OneofOptions = &file_sapient_msg_proto_options_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional sapient_msg.ValidationOptions field_options = 50001;
	E_FieldOptions = &file_sapient_msg_proto_options_proto_extTypes[3]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional sapient_msg.MessageOptions message_options = 50001;
	E_MessageOptions = &file_sapient_msg_proto_options_proto_extTypes[4]
)

var File_sapient_msg_proto_options_proto protoreflect.FileDescriptor

const file_sapient_msg_proto_options_proto_rawDesc = "" +
	"\n" +
	"\x1fsapient_msg/proto_options.proto\x12\vsapient_msg\x1a google/protobuf/descriptor.proto\"8\n" +
	"\vFileOptions\x12)\n" +
	"\x10standard_version\x18\x01 \x01(\tR\x0fstandardVersion\"\xa8\x05\n" +
	"\x11ValidationOptions\x12&\n" +
	"\fis_mandatory\x18\x01 \x01(\bH\x00R\visMandatory\x88\x01\x01\x12\x1c\n" +
	"\ais_ulid\x18\x02 \x01(\bH\x01R\x06isUlid\x88\x01\x01\x12\x1c\n" +
	"\ais_uuid\x18\x03 \x01(\bH\x02R\x06isUuid\x88\x01\x01\x12\x1e\n" +
	"\bxml_name\x18\x04 \x01(\tH\x03R\axmlName\x88\x01\x01\x12-\n" +
	"\x10xml_is_attribute\x18\x05 \x01(\bH\x04R\x0exmlIsAttribute\x88\x01\x01\x12\"\n" +
	"\n" +
	"xml_ignore\x18\x06 \x01(\bH\x05R\txmlIgnore\x88\x01\x01\x12/\n" +
	"\x11xml_singly_nested\x18\a \x01(\tH\x06R\x0fxmlSinglyNested\x88\x01\x01\x122\n" +
	"\x13xml_is_parent_value\x18\b \x01(\bH\aR\x10xmlIsParentValue\x88\x01\x01\x12 \n" +
	"\tenum_name\x18\t \x01(\tH\bR\benumName\x88\x01\x01\x12'\n" +
	"\ris_proto_time\x18\n" +
	" \x01(\bH\tR\visProtoTime\x88\x01\x01\x12(\n" +
	"\rxml_tentative\x18\v \x01(\bH\n" +
	"R\fxmlTentative\x88\x01\x01\x12\x1c\n" +
	"\ais_time\x18\f \x01(\bH\vR\x06isTime\x88\x01\x01B\x0f\n" +
	"\r_is_mandatoryB\n" +
	"\n" +
	"\b_is_ulidB\n" +
	"\n" +
	"\b_is_uuidB\v\n" +
	"\t_xml_nameB\x13\n" +
	"\x11_xml_is_attributeB\r\n" +
	"\v_xml_ignoreB\x14\n" +
	"\x12_xml_singly_nestedB\x16\n" +
	"\x14_xml_is_parent_valueB\f\n" +
	"\n" +
	"_enum_nameB\x10\n" +
	"\x0e_is_proto_timeB\x10\n" +
	"\x0e_xml_tentativeB\n" +
	"\n" +
	"\b_is_time\"\xa2\x01\n" +
	"\x0eMessageOptions\x12/\n" +
	"\x10xml_message_name\x18ц\x03 \x01(\tH\x00R\x0exmlMessageName\x88\x01\x01\x123\n" +
	"\x12is_sapient_message\x18҆\x03 \x01(\bH\x01R\x10isSapientMessage\x88\x01\x01B\x13\n" +
	"\x11_xml_message_nameB\x15\n" +
	"\x13_is_sapient_message:[\n" +
	"\ffile_options\x12\x1c.google.protobuf.FileOptions\x18\xa1\x8d\x06 \x01(\v2\x18.sapient_msg.FileOptionsR\vfileOptions:i\n" +
	"\fenum_options\x12!.google.protobuf.EnumValueOptions\x18ц\x03 \x01(\v2\x1e.sapient_msg.ValidationOptionsR\venumOptions\x88\x01\x01:g\n" +
	"\roneof_options\x12\x1d.google.protobuf.OneofOptions\x18ц\x03 \x01(\v2\x1e.sapient_msg.ValidationOptionsR\foneofOptions\x88\x01\x01:g\n" +
	"\rfield_options\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\x1e.sapient_msg.ValidationOptionsR\ffieldOptions\x88\x01\x01:j\n" +
	"\x0fmessage_options\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\v2\x1b.sapient_msg.MessageOptionsR\x0emessageOptions\x88\x01\x01B-\n" +
	"\x16uk.gov.dstl.sapientmsgB\x11ProtoOptionsProtoP\x01b\x06proto3"

var (
	file_sapient_msg_proto_options_proto_rawDescOnce sync.Once
	file_sapient_msg_proto_options_proto_rawDescData []byte
)

func file_sapient_msg_proto_options_proto_rawDescGZIP() []byte {
	file_sapient_msg_proto_options_proto_rawDescOnce.Do(func() {
		file_sapient_msg_proto_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_proto_options_proto_rawDesc), len(file_sapient_msg_proto_options_proto_rawDesc)))
	})
	return file_sapient_msg_proto_options_proto_rawDescData
}

var file_sapient_msg_proto_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sapient_msg_proto_options_proto_goTypes = []any{
	(*FileOptions)(nil),                   // 0: sapient_msg.FileOptions
	(*ValidationOptions)(nil),             // 1: sapient_msg.ValidationOptions
	(*MessageOptions)(nil),                // 2: sapient_msg.MessageOptions
	(*descriptorpb.FileOptions)(nil),      // 3: google.protobuf.FileOptions
	(*descriptorpb.EnumValueOptions)(nil), // 4: google.protobuf.EnumValueOptions
	(*descriptorpb.OneofOptions)(nil),     // 5: google.protobuf.OneofOptions
	(*descriptorpb.FieldOptions)(nil),     // 6: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil),   // 7: google.protobuf.MessageOptions
}
var file_sapient_msg_proto_options_proto_depIdxs = []int32{
	3,  // 0: sapient_msg.file_options:extendee -> google.protobuf.FileOptions
	4,  // 1: sapient_msg.enum_options:extendee -> google.protobuf.EnumValueOptions
	5,  // 2: sapient_msg.oneof_options:extendee -> google.protobuf.OneofOptions
	6,  // 3: sapient_msg.field_options:extendee -> google.protobuf.FieldOptions
	7,  // 4: sapient_msg.message_options:extendee -> google.protobuf.MessageOptions
	0,  // 5: sapient_msg.file_options:type_name -> sapient_msg.FileOptions
	1,  // 6: sapient_msg.enum_options:type_name -> sapient_msg.ValidationOptions
	1,  // 7: sapient_msg.oneof_options:type_name -> sapient_msg.ValidationOptions
	1,  // 8: sapient_msg.field_options:type_name -> sapient_msg.ValidationOptions
	2,  // 9: sapient_msg.message_options:type_name -> sapient_msg.MessageOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	5,  // [5:10] is the sub-list for extension type_name
	0,  // [0:5] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_sapient_msg_proto_options_proto_init() }
func file_sapient_msg_proto_options_proto_init() {
	if File_sapient_msg_proto_options_proto != nil {
		return
	}
	file_sapient_msg_proto_options_proto_msgTypes[1].OneofWrappers = []any{}
	file_sapient_msg_proto_options_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_proto_options_proto_rawDesc), len(file_sapient_msg_proto_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_proto_options_proto_goTypes,
		DependencyIndexes: file_sapient_msg_proto_options_proto_depIdxs,
		MessageInfos:      file_sapient_msg_proto_options_proto_msgTypes,
		ExtensionInfos:    file_sapient_msg_proto_options_proto_extTypes,
	}.Build()
	File_sapient_msg_proto_options_proto = out.File
	file_sapient_msg_proto_options_proto_goTypes = nil
	file_sapient_msg_proto_options_proto_depIdxs = nil
}
