// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/range_bearing.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RangeBearingCoordinateSystem int32

const (
	RangeBearingCoordinateSystem_RANGE_BEARING_COORDINATE_SYSTEM_UNSPECIFIED RangeBearingCoordinateSystem = 0 // Co-ordinate system/units not defined
	RangeBearingCoordinateSystem_RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_M   RangeBearingCoordinateSystem = 1 // Values in decimal-degrees and meters
	RangeBearingCoordinateSystem_RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_M   RangeBearingCoordinateSystem = 2 // Values in radians and meters
	RangeBearingCoordinateSystem_RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_KM  RangeBearingCoordinateSystem = 3 // Values in decimal-degrees and kilometers
	RangeBearingCoordinateSystem_RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_KM  RangeBearingCoordinateSystem = 4 // Values in radians and kilometers
)

// Enum value maps for RangeBearingCoordinateSystem.
var (
	RangeBearingCoordinateSystem_name = map[int32]string{
		0: "RANGE_BEARING_COORDINATE_SYSTEM_UNSPECIFIED",
		1: "RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_M",
		2: "RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_M",
		3: "RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_KM",
		4: "RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_KM",
	}
	RangeBearingCoordinateSystem_value = map[string]int32{
		"RANGE_BEARING_COORDINATE_SYSTEM_UNSPECIFIED": 0,
		"RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_M":   1,
		"RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_M":   2,
		"RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_KM":  3,
		"RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_KM":  4,
	}
)

func (x RangeBearingCoordinateSystem) Enum() *RangeBearingCoordinateSystem {
	p := new(RangeBearingCoordinateSystem)
	*p = x
	return p
}

func (x RangeBearingCoordinateSystem) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeBearingCoordinateSystem) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_enumTypes[0].Descriptor()
}

func (RangeBearingCoordinateSystem) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_enumTypes[0]
}

func (x RangeBearingCoordinateSystem) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeBearingCoordinateSystem.Descriptor instead.
func (RangeBearingCoordinateSystem) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDescGZIP(), []int{0}
}

type RangeBearingDatum int32

const (
	RangeBearingDatum_RANGE_BEARING_DATUM_UNSPECIFIED RangeBearingDatum = 0 // Datum not defined
	RangeBearingDatum_RANGE_BEARING_DATUM_TRUE        RangeBearingDatum = 1 // True North
	RangeBearingDatum_RANGE_BEARING_DATUM_MAGNETIC    RangeBearingDatum = 2 // Magnetic North
	RangeBearingDatum_RANGE_BEARING_DATUM_GRID        RangeBearingDatum = 3 // Grid North
	RangeBearingDatum_RANGE_BEARING_DATUM_PLATFORM    RangeBearingDatum = 4 // 'North' is the heading of the platform carrying the node
)

// Enum value maps for RangeBearingDatum.
var (
	RangeBearingDatum_name = map[int32]string{
		0: "RANGE_BEARING_DATUM_UNSPECIFIED",
		1: "RANGE_BEARING_DATUM_TRUE",
		2: "RANGE_BEARING_DATUM_MAGNETIC",
		3: "RANGE_BEARING_DATUM_GRID",
		4: "RANGE_BEARING_DATUM_PLATFORM",
	}
	RangeBearingDatum_value = map[string]int32{
		"RANGE_BEARING_DATUM_UNSPECIFIED": 0,
		"RANGE_BEARING_DATUM_TRUE":        1,
		"RANGE_BEARING_DATUM_MAGNETIC":    2,
		"RANGE_BEARING_DATUM_GRID":        3,
		"RANGE_BEARING_DATUM_PLATFORM":    4,
	}
)

func (x RangeBearingDatum) Enum() *RangeBearingDatum {
	p := new(RangeBearingDatum)
	*p = x
	return p
}

func (x RangeBearingDatum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeBearingDatum) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_enumTypes[1].Descriptor()
}

func (RangeBearingDatum) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_enumTypes[1]
}

func (x RangeBearingDatum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeBearingDatum.Descriptor instead.
func (RangeBearingDatum) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDescGZIP(), []int{1}
}

// [START messages]
type RangeBearing struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	Elevation        *float64                      `protobuf:"fixed64,1,opt,name=elevation,proto3,oneof" json:"elevation,omitempty"`                                                                                                      // Elevation in relation to node's horizon
	Azimuth          *float64                      `protobuf:"fixed64,2,opt,name=azimuth,proto3,oneof" json:"azimuth,omitempty"`                                                                                                          // Azimuth in relation to the node's north
	Range            *float64                      `protobuf:"fixed64,3,opt,name=range,proto3,oneof" json:"range,omitempty"`                                                                                                              // Range from the node's location
	ElevationError   *float64                      `protobuf:"fixed64,4,opt,name=elevation_error,json=elevationError,proto3,oneof" json:"elevation_error,omitempty"`                                                                      // Elevation error
	AzimuthError     *float64                      `protobuf:"fixed64,5,opt,name=azimuth_error,json=azimuthError,proto3,oneof" json:"azimuth_error,omitempty"`                                                                            // Azimuth error
	RangeError       *float64                      `protobuf:"fixed64,6,opt,name=range_error,json=rangeError,proto3,oneof" json:"range_error,omitempty"`                                                                                  // Range Error
	CoordinateSystem *RangeBearingCoordinateSystem `protobuf:"varint,7,opt,name=coordinate_system,json=coordinateSystem,proto3,enum=sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystem,oneof" json:"coordinate_system,omitempty"` // Units used by the range bearing
	Datum            *RangeBearingDatum            `protobuf:"varint,8,opt,name=datum,proto3,enum=sapient_msg.bsi_flex_335_v2_0.RangeBearingDatum,oneof" json:"datum,omitempty"`                                                          // Datum or 'north' used by the range bearing
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RangeBearing) Reset() {
	*x = RangeBearing{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeBearing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeBearing) ProtoMessage() {}

func (x *RangeBearing) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeBearing.ProtoReflect.Descriptor instead.
func (*RangeBearing) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDescGZIP(), []int{0}
}

func (x *RangeBearing) GetElevation() float64 {
	if x != nil && x.Elevation != nil {
		return *x.Elevation
	}
	return 0
}

func (x *RangeBearing) GetAzimuth() float64 {
	if x != nil && x.Azimuth != nil {
		return *x.Azimuth
	}
	return 0
}

func (x *RangeBearing) GetRange() float64 {
	if x != nil && x.Range != nil {
		return *x.Range
	}
	return 0
}

func (x *RangeBearing) GetElevationError() float64 {
	if x != nil && x.ElevationError != nil {
		return *x.ElevationError
	}
	return 0
}

func (x *RangeBearing) GetAzimuthError() float64 {
	if x != nil && x.AzimuthError != nil {
		return *x.AzimuthError
	}
	return 0
}

func (x *RangeBearing) GetRangeError() float64 {
	if x != nil && x.RangeError != nil {
		return *x.RangeError
	}
	return 0
}

func (x *RangeBearing) GetCoordinateSystem() RangeBearingCoordinateSystem {
	if x != nil && x.CoordinateSystem != nil {
		return *x.CoordinateSystem
	}
	return RangeBearingCoordinateSystem_RANGE_BEARING_COORDINATE_SYSTEM_UNSPECIFIED
}

func (x *RangeBearing) GetDatum() RangeBearingDatum {
	if x != nil && x.Datum != nil {
		return *x.Datum
	}
	return RangeBearingDatum_RANGE_BEARING_DATUM_UNSPECIFIED
}

type RangeBearingCone struct {
	state                 protoimpl.MessageState        `protogen:"open.v1"`
	Elevation             *float64                      `protobuf:"fixed64,1,opt,name=elevation,proto3,oneof" json:"elevation,omitempty"`                                                                                                       // Elevation in relation to node's horizon
	Azimuth               *float64                      `protobuf:"fixed64,2,opt,name=azimuth,proto3,oneof" json:"azimuth,omitempty"`                                                                                                           // Azimuth in relation to the node's north
	Range                 *float64                      `protobuf:"fixed64,3,opt,name=range,proto3,oneof" json:"range,omitempty"`                                                                                                               // Range from the node's location
	HorizontalExtent      *float64                      `protobuf:"fixed64,4,opt,name=horizontal_extent,json=horizontalExtent,proto3,oneof" json:"horizontal_extent,omitempty"`                                                                 // Horizontal extent angle in degrees
	VerticalExtent        *float64                      `protobuf:"fixed64,5,opt,name=vertical_extent,json=verticalExtent,proto3,oneof" json:"vertical_extent,omitempty"`                                                                       // Vertical extent angle in degrees
	HorizontalExtentError *float64                      `protobuf:"fixed64,6,opt,name=horizontal_extent_error,json=horizontalExtentError,proto3,oneof" json:"horizontal_extent_error,omitempty"`                                                // Error in the horizontal extent
	VerticalExtentError   *float64                      `protobuf:"fixed64,7,opt,name=vertical_extent_error,json=verticalExtentError,proto3,oneof" json:"vertical_extent_error,omitempty"`                                                      // Error in the vertical extent
	ElevationError        *float64                      `protobuf:"fixed64,8,opt,name=elevation_error,json=elevationError,proto3,oneof" json:"elevation_error,omitempty"`                                                                       // Elevation error
	AzimuthError          *float64                      `protobuf:"fixed64,9,opt,name=azimuth_error,json=azimuthError,proto3,oneof" json:"azimuth_error,omitempty"`                                                                             // Azimuth error
	RangeError            *float64                      `protobuf:"fixed64,10,opt,name=range_error,json=rangeError,proto3,oneof" json:"range_error,omitempty"`                                                                                  // Range Error
	CoordinateSystem      *RangeBearingCoordinateSystem `protobuf:"varint,11,opt,name=coordinate_system,json=coordinateSystem,proto3,enum=sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystem,oneof" json:"coordinate_system,omitempty"` // Units used by the range bearing
	Datum                 *RangeBearingDatum            `protobuf:"varint,12,opt,name=datum,proto3,enum=sapient_msg.bsi_flex_335_v2_0.RangeBearingDatum,oneof" json:"datum,omitempty"`                                                          // Datum or 'north' used by the range bearing
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RangeBearingCone) Reset() {
	*x = RangeBearingCone{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeBearingCone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeBearingCone) ProtoMessage() {}

func (x *RangeBearingCone) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeBearingCone.ProtoReflect.Descriptor instead.
func (*RangeBearingCone) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDescGZIP(), []int{1}
}

func (x *RangeBearingCone) GetElevation() float64 {
	if x != nil && x.Elevation != nil {
		return *x.Elevation
	}
	return 0
}

func (x *RangeBearingCone) GetAzimuth() float64 {
	if x != nil && x.Azimuth != nil {
		return *x.Azimuth
	}
	return 0
}

func (x *RangeBearingCone) GetRange() float64 {
	if x != nil && x.Range != nil {
		return *x.Range
	}
	return 0
}

func (x *RangeBearingCone) GetHorizontalExtent() float64 {
	if x != nil && x.HorizontalExtent != nil {
		return *x.HorizontalExtent
	}
	return 0
}

func (x *RangeBearingCone) GetVerticalExtent() float64 {
	if x != nil && x.VerticalExtent != nil {
		return *x.VerticalExtent
	}
	return 0
}

func (x *RangeBearingCone) GetHorizontalExtentError() float64 {
	if x != nil && x.HorizontalExtentError != nil {
		return *x.HorizontalExtentError
	}
	return 0
}

func (x *RangeBearingCone) GetVerticalExtentError() float64 {
	if x != nil && x.VerticalExtentError != nil {
		return *x.VerticalExtentError
	}
	return 0
}

func (x *RangeBearingCone) GetElevationError() float64 {
	if x != nil && x.ElevationError != nil {
		return *x.ElevationError
	}
	return 0
}

func (x *RangeBearingCone) GetAzimuthError() float64 {
	if x != nil && x.AzimuthError != nil {
		return *x.AzimuthError
	}
	return 0
}

func (x *RangeBearingCone) GetRangeError() float64 {
	if x != nil && x.RangeError != nil {
		return *x.RangeError
	}
	return 0
}

func (x *RangeBearingCone) GetCoordinateSystem() RangeBearingCoordinateSystem {
	if x != nil && x.CoordinateSystem != nil {
		return *x.CoordinateSystem
	}
	return RangeBearingCoordinateSystem_RANGE_BEARING_COORDINATE_SYSTEM_UNSPECIFIED
}

func (x *RangeBearingCone) GetDatum() RangeBearingDatum {
	if x != nil && x.Datum != nil {
		return *x.Datum
	}
	return RangeBearingDatum_RANGE_BEARING_DATUM_UNSPECIFIED
}

type LocationOrRangeBearing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to FovOneof:
	//
	//	*LocationOrRangeBearing_RangeBearing
	//	*LocationOrRangeBearing_LocationList
	FovOneof      isLocationOrRangeBearing_FovOneof `protobuf_oneof:"fov_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationOrRangeBearing) Reset() {
	*x = LocationOrRangeBearing{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationOrRangeBearing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationOrRangeBearing) ProtoMessage() {}

func (x *LocationOrRangeBearing) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationOrRangeBearing.ProtoReflect.Descriptor instead.
func (*LocationOrRangeBearing) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDescGZIP(), []int{2}
}

func (x *LocationOrRangeBearing) GetFovOneof() isLocationOrRangeBearing_FovOneof {
	if x != nil {
		return x.FovOneof
	}
	return nil
}

func (x *LocationOrRangeBearing) GetRangeBearing() *RangeBearingCone {
	if x != nil {
		if x, ok := x.FovOneof.(*LocationOrRangeBearing_RangeBearing); ok {
			return x.RangeBearing
		}
	}
	return nil
}

func (x *LocationOrRangeBearing) GetLocationList() *LocationList {
	if x != nil {
		if x, ok := x.FovOneof.(*LocationOrRangeBearing_LocationList); ok {
			return x.LocationList
		}
	}
	return nil
}

type isLocationOrRangeBearing_FovOneof interface {
	isLocationOrRangeBearing_FovOneof()
}

type LocationOrRangeBearing_RangeBearing struct {
	RangeBearing *RangeBearingCone `protobuf:"bytes,1,opt,name=range_bearing,json=rangeBearing,proto3,oneof"` // Location in Spherical coordinates
}

type LocationOrRangeBearing_LocationList struct {
	LocationList *LocationList `protobuf:"bytes,2,opt,name=location_list,json=locationList,proto3,oneof"` // Location in Geo coordinates
}

func (*LocationOrRangeBearing_RangeBearing) isLocationOrRangeBearing_FovOneof() {}

func (*LocationOrRangeBearing_LocationList) isLocationOrRangeBearing_FovOneof() {}

var File_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDesc = "" +
	"\n" +
	"1sapient_msg/bsi_flex_335_v2_0/range_bearing.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a,sapient_msg/bsi_flex_335_v2_0/location.proto\x1a\x1fsapient_msg/proto_options.proto\"\xaf\x04\n" +
	"\fRangeBearing\x12!\n" +
	"\televation\x18\x01 \x01(\x01H\x00R\televation\x88\x01\x01\x12\x1d\n" +
	"\aazimuth\x18\x02 \x01(\x01H\x01R\aazimuth\x88\x01\x01\x12\x19\n" +
	"\x05range\x18\x03 \x01(\x01H\x02R\x05range\x88\x01\x01\x12,\n" +
	"\x0felevation_error\x18\x04 \x01(\x01H\x03R\x0eelevationError\x88\x01\x01\x12(\n" +
	"\razimuth_error\x18\x05 \x01(\x01H\x04R\fazimuthError\x88\x01\x01\x12$\n" +
	"\vrange_error\x18\x06 \x01(\x01H\x05R\n" +
	"rangeError\x88\x01\x01\x12u\n" +
	"\x11coordinate_system\x18\a \x01(\x0e2;.sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystemB\x06\x8a\xb5\x18\x02\b\x01H\x06R\x10coordinateSystem\x88\x01\x01\x12S\n" +
	"\x05datum\x18\b \x01(\x0e20.sapient_msg.bsi_flex_335_v2_0.RangeBearingDatumB\x06\x8a\xb5\x18\x02\b\x01H\aR\x05datum\x88\x01\x01B\f\n" +
	"\n" +
	"_elevationB\n" +
	"\n" +
	"\b_azimuthB\b\n" +
	"\x06_rangeB\x12\n" +
	"\x10_elevation_errorB\x10\n" +
	"\x0e_azimuth_errorB\x0e\n" +
	"\f_range_errorB\x14\n" +
	"\x12_coordinate_systemB\b\n" +
	"\x06_datum\"\xe9\x06\n" +
	"\x10RangeBearingCone\x12!\n" +
	"\televation\x18\x01 \x01(\x01H\x00R\televation\x88\x01\x01\x12\x1d\n" +
	"\aazimuth\x18\x02 \x01(\x01H\x01R\aazimuth\x88\x01\x01\x12\x19\n" +
	"\x05range\x18\x03 \x01(\x01H\x02R\x05range\x88\x01\x01\x120\n" +
	"\x11horizontal_extent\x18\x04 \x01(\x01H\x03R\x10horizontalExtent\x88\x01\x01\x12,\n" +
	"\x0fvertical_extent\x18\x05 \x01(\x01H\x04R\x0everticalExtent\x88\x01\x01\x12;\n" +
	"\x17horizontal_extent_error\x18\x06 \x01(\x01H\x05R\x15horizontalExtentError\x88\x01\x01\x127\n" +
	"\x15vertical_extent_error\x18\a \x01(\x01H\x06R\x13verticalExtentError\x88\x01\x01\x12,\n" +
	"\x0felevation_error\x18\b \x01(\x01H\aR\x0eelevationError\x88\x01\x01\x12(\n" +
	"\razimuth_error\x18\t \x01(\x01H\bR\fazimuthError\x88\x01\x01\x12$\n" +
	"\vrange_error\x18\n" +
	" \x01(\x01H\tR\n" +
	"rangeError\x88\x01\x01\x12u\n" +
	"\x11coordinate_system\x18\v \x01(\x0e2;.sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystemB\x06\x8a\xb5\x18\x02\b\x01H\n" +
	"R\x10coordinateSystem\x88\x01\x01\x12S\n" +
	"\x05datum\x18\f \x01(\x0e20.sapient_msg.bsi_flex_335_v2_0.RangeBearingDatumB\x06\x8a\xb5\x18\x02\b\x01H\vR\x05datum\x88\x01\x01B\f\n" +
	"\n" +
	"_elevationB\n" +
	"\n" +
	"\b_azimuthB\b\n" +
	"\x06_rangeB\x14\n" +
	"\x12_horizontal_extentB\x12\n" +
	"\x10_vertical_extentB\x1a\n" +
	"\x18_horizontal_extent_errorB\x18\n" +
	"\x16_vertical_extent_errorB\x12\n" +
	"\x10_elevation_errorB\x10\n" +
	"\x0e_azimuth_errorB\x0e\n" +
	"\f_range_errorB\x14\n" +
	"\x12_coordinate_systemB\b\n" +
	"\x06_datum\"\xd9\x01\n" +
	"\x16LocationOrRangeBearing\x12V\n" +
	"\rrange_bearing\x18\x01 \x01(\v2/.sapient_msg.bsi_flex_335_v2_0.RangeBearingConeH\x00R\frangeBearing\x12R\n" +
	"\rlocation_list\x18\x02 \x01(\v2+.sapient_msg.bsi_flex_335_v2_0.LocationListH\x00R\flocationListB\x13\n" +
	"\tfov_oneof\x12\x06\x8a\xb5\x18\x02\b\x01*\x99\x02\n" +
	"\x1cRangeBearingCoordinateSystem\x12/\n" +
	"+RANGE_BEARING_COORDINATE_SYSTEM_UNSPECIFIED\x10\x00\x12-\n" +
	")RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_M\x10\x01\x12-\n" +
	")RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_M\x10\x02\x12.\n" +
	"*RANGE_BEARING_COORDINATE_SYSTEM_DEGREES_KM\x10\x03\x12.\n" +
	"*RANGE_BEARING_COORDINATE_SYSTEM_RADIANS_KM\x10\x04\"\x04\b\x05\x10\x05\"\x04\b\x06\x10\x06*\xb8\x01\n" +
	"\x11RangeBearingDatum\x12#\n" +
	"\x1fRANGE_BEARING_DATUM_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RANGE_BEARING_DATUM_TRUE\x10\x01\x12 \n" +
	"\x1cRANGE_BEARING_DATUM_MAGNETIC\x10\x02\x12\x1c\n" +
	"\x18RANGE_BEARING_DATUM_GRID\x10\x03\x12 \n" +
	"\x1cRANGE_BEARING_DATUM_PLATFORM\x10\x04B:\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\x11RangeBearingProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_goTypes = []any{
	(RangeBearingCoordinateSystem)(0), // 0: sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystem
	(RangeBearingDatum)(0),            // 1: sapient_msg.bsi_flex_335_v2_0.RangeBearingDatum
	(*RangeBearing)(nil),              // 2: sapient_msg.bsi_flex_335_v2_0.RangeBearing
	(*RangeBearingCone)(nil),          // 3: sapient_msg.bsi_flex_335_v2_0.RangeBearingCone
	(*LocationOrRangeBearing)(nil),    // 4: sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing
	(*LocationList)(nil),              // 5: sapient_msg.bsi_flex_335_v2_0.LocationList
}
var file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_depIdxs = []int32{
	0, // 0: sapient_msg.bsi_flex_335_v2_0.RangeBearing.coordinate_system:type_name -> sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystem
	1, // 1: sapient_msg.bsi_flex_335_v2_0.RangeBearing.datum:type_name -> sapient_msg.bsi_flex_335_v2_0.RangeBearingDatum
	0, // 2: sapient_msg.bsi_flex_335_v2_0.RangeBearingCone.coordinate_system:type_name -> sapient_msg.bsi_flex_335_v2_0.RangeBearingCoordinateSystem
	1, // 3: sapient_msg.bsi_flex_335_v2_0.RangeBearingCone.datum:type_name -> sapient_msg.bsi_flex_335_v2_0.RangeBearingDatum
	3, // 4: sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing.range_bearing:type_name -> sapient_msg.bsi_flex_335_v2_0.RangeBearingCone
	5, // 5: sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing.location_list:type_name -> sapient_msg.bsi_flex_335_v2_0.LocationList
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto != nil {
		return
	}
	file_sapient_msg_bsi_flex_335_v2_0_location_proto_init()
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_msgTypes[0].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_msgTypes[1].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_msgTypes[2].OneofWrappers = []any{
		(*LocationOrRangeBearing_RangeBearing)(nil),
		(*LocationOrRangeBearing_LocationList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_depIdxs,
		EnumInfos:         file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_enumTypes,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_depIdxs = nil
}
