// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/registration_ack.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [START messages]
type RegistrationAck struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Acceptance *bool                  `protobuf:"varint,1,opt,name=acceptance,proto3,oneof" json:"acceptance,omitempty"` // This value shall be 0 if the registration is rejected, or 1 if the registration is accepted
	// optional string ack_response_reason = 2; // This field can be used to communicate the reason for non-registration
	AckResponseReason []string `protobuf:"bytes,3,rep,name=ack_response_reason,json=ackResponseReason,proto3" json:"ack_response_reason,omitempty"` // This field can be used to communicate the (operational) reason(s) for rejecting the Registration Message (one per array element)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegistrationAck) Reset() {
	*x = RegistrationAck{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationAck) ProtoMessage() {}

func (x *RegistrationAck) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationAck.ProtoReflect.Descriptor instead.
func (*RegistrationAck) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationAck) GetAcceptance() bool {
	if x != nil && x.Acceptance != nil {
		return *x.Acceptance
	}
	return false
}

func (x *RegistrationAck) GetAckResponseReason() []string {
	if x != nil {
		return x.AckResponseReason
	}
	return nil
}

var File_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDesc = "" +
	"\n" +
	"4sapient_msg/bsi_flex_335_v2_0/registration_ack.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fsapient_msg/proto_options.proto\"\x83\x01\n" +
	"\x0fRegistrationAck\x12+\n" +
	"\n" +
	"acceptance\x18\x01 \x01(\bB\x06\x8a\xb5\x18\x02\b\x01H\x00R\n" +
	"acceptance\x88\x01\x01\x12.\n" +
	"\x13ack_response_reason\x18\x03 \x03(\tR\x11ackResponseReasonB\r\n" +
	"\v_acceptanceJ\x04\b\x02\x10\x03B=\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\x14RegistrationAckProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_goTypes = []any{
	(*RegistrationAck)(nil), // 0: sapient_msg.bsi_flex_335_v2_0.RegistrationAck
}
var file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto != nil {
		return
	}
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_depIdxs,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_depIdxs = nil
}
