// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/sapient_message.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [START messages]
type SapientMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`                              // UTC timestamp the message was sent
	NodeId        *string                `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`                      // UUID for the node which is sending the message
	DestinationId *string                `protobuf:"bytes,3,opt,name=destination_id,json=destinationId,proto3,oneof" json:"destination_id,omitempty"` // UUID for the node being tasked
	// Types that are valid to be assigned to Content:
	//
	//	*SapientMessage_Registration
	//	*SapientMessage_RegistrationAck
	//	*SapientMessage_StatusReport
	//	*SapientMessage_DetectionReport
	//	*SapientMessage_Task
	//	*SapientMessage_TaskAck
	//	*SapientMessage_Alert
	//	*SapientMessage_AlertAck
	//	*SapientMessage_Error
	Content               isSapientMessage_Content `protobuf_oneof:"content"`
	AdditionalInformation *string                  `protobuf:"bytes,13,opt,name=additional_information,json=additionalInformation,proto3,oneof" json:"additional_information,omitempty"` // space for additional information
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SapientMessage) Reset() {
	*x = SapientMessage{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SapientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SapientMessage) ProtoMessage() {}

func (x *SapientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SapientMessage.ProtoReflect.Descriptor instead.
func (*SapientMessage) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDescGZIP(), []int{0}
}

func (x *SapientMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SapientMessage) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *SapientMessage) GetDestinationId() string {
	if x != nil && x.DestinationId != nil {
		return *x.DestinationId
	}
	return ""
}

func (x *SapientMessage) GetContent() isSapientMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SapientMessage) GetRegistration() *Registration {
	if x != nil {
		if x, ok := x.Content.(*SapientMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *SapientMessage) GetRegistrationAck() *RegistrationAck {
	if x != nil {
		if x, ok := x.Content.(*SapientMessage_RegistrationAck); ok {
			return x.RegistrationAck
		}
	}
	return nil
}

func (x *SapientMessage) GetStatusReport() *StatusReport {
	if x != nil {
		if x, ok := x.Content.(*SapientMessage_StatusReport); ok {
			return x.StatusReport
		}
	}
	return nil
}

func (x *SapientMessage) GetDetectionReport() *DetectionReport {
	if x != nil {
		if x, ok := x.Content.(*SapientMessage_DetectionReport); ok {
			return x.DetectionReport
		}
	}
	return nil
}

func (x *SapientMessage) GetTask() *Task {
	if x != nil {
		if x, ok := x.Content.(*SapientMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *SapientMessage) GetTaskAck() *TaskAck {
	if x != nil {
		if x, ok := x.Content.(*SapientMessage_TaskAck); ok {
			return x.TaskAck
		}
	}
	return nil
}

func (x *SapientMessage) GetAlert() *Alert {
	if x != nil {
		if x, ok := x.Content.(*SapientMessage_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

func (x *SapientMessage) GetAlertAck() *AlertAck {
	if x != nil {
		if x, ok := x.Content.(*SapientMessage_AlertAck); ok {
			return x.AlertAck
		}
	}
	return nil
}

func (x *SapientMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Content.(*SapientMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *SapientMessage) GetAdditionalInformation() string {
	if x != nil && x.AdditionalInformation != nil {
		return *x.AdditionalInformation
	}
	return ""
}

type isSapientMessage_Content interface {
	isSapientMessage_Content()
}

type SapientMessage_Registration struct {
	Registration *Registration `protobuf:"bytes,4,opt,name=registration,proto3,oneof"` // SAPIENT Registration message
}

type SapientMessage_RegistrationAck struct {
	RegistrationAck *RegistrationAck `protobuf:"bytes,5,opt,name=registration_ack,json=registrationAck,proto3,oneof"` // SAPIENT Registration Acknowledgement message
}

type SapientMessage_StatusReport struct {
	StatusReport *StatusReport `protobuf:"bytes,6,opt,name=status_report,json=statusReport,proto3,oneof"` // SAPIENT Status Report message
}

type SapientMessage_DetectionReport struct {
	DetectionReport *DetectionReport `protobuf:"bytes,7,opt,name=detection_report,json=detectionReport,proto3,oneof"` // SAPIENT Detection Report message
}

type SapientMessage_Task struct {
	Task *Task `protobuf:"bytes,8,opt,name=task,proto3,oneof"` // SAPIENT Task message
}

type SapientMessage_TaskAck struct {
	TaskAck *TaskAck `protobuf:"bytes,9,opt,name=task_ack,json=taskAck,proto3,oneof"` // SAPIENT Task Acknowledgement message
}

type SapientMessage_Alert struct {
	Alert *Alert `protobuf:"bytes,10,opt,name=alert,proto3,oneof"` // SAPIENT Alert message
}

type SapientMessage_AlertAck struct {
	AlertAck *AlertAck `protobuf:"bytes,11,opt,name=alert_ack,json=alertAck,proto3,oneof"` // SAPIENT Alert Acknowledgment message
}

type SapientMessage_Error struct {
	Error *Error `protobuf:"bytes,12,opt,name=error,proto3,oneof"` // SAPIENT Error message
}

func (*SapientMessage_Registration) isSapientMessage_Content() {}

func (*SapientMessage_RegistrationAck) isSapientMessage_Content() {}

func (*SapientMessage_StatusReport) isSapientMessage_Content() {}

func (*SapientMessage_DetectionReport) isSapientMessage_Content() {}

func (*SapientMessage_Task) isSapientMessage_Content() {}

func (*SapientMessage_TaskAck) isSapientMessage_Content() {}

func (*SapientMessage_Alert) isSapientMessage_Content() {}

func (*SapientMessage_AlertAck) isSapientMessage_Content() {}

func (*SapientMessage_Error) isSapientMessage_Content() {}

var File_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDesc = "" +
	"\n" +
	"3sapient_msg/bsi_flex_335_v2_0/sapient_message.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)sapient_msg/bsi_flex_335_v2_0/alert.proto\x1a-sapient_msg/bsi_flex_335_v2_0/alert_ack.proto\x1a4sapient_msg/bsi_flex_335_v2_0/detection_report.proto\x1a)sapient_msg/bsi_flex_335_v2_0/error.proto\x1a\x1fsapient_msg/proto_options.proto\x1a0sapient_msg/bsi_flex_335_v2_0/registration.proto\x1a4sapient_msg/bsi_flex_335_v2_0/registration_ack.proto\x1a1sapient_msg/bsi_flex_335_v2_0/status_report.proto\x1a(sapient_msg/bsi_flex_335_v2_0/task.proto\x1a,sapient_msg/bsi_flex_335_v2_0/task_ack.proto\"\xef\a\n" +
	"\x0eSapientMessage\x12E\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x06\x8a\xb5\x18\x02\b\x01H\x01R\ttimestamp\x88\x01\x01\x12&\n" +
	"\anode_id\x18\x02 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x18\x01H\x02R\x06nodeId\x88\x01\x01\x122\n" +
	"\x0edestination_id\x18\x03 \x01(\tB\x06\x8a\xb5\x18\x02\x18\x01H\x03R\rdestinationId\x88\x01\x01\x12Q\n" +
	"\fregistration\x18\x04 \x01(\v2+.sapient_msg.bsi_flex_335_v2_0.RegistrationH\x00R\fregistration\x12[\n" +
	"\x10registration_ack\x18\x05 \x01(\v2..sapient_msg.bsi_flex_335_v2_0.RegistrationAckH\x00R\x0fregistrationAck\x12R\n" +
	"\rstatus_report\x18\x06 \x01(\v2+.sapient_msg.bsi_flex_335_v2_0.StatusReportH\x00R\fstatusReport\x12[\n" +
	"\x10detection_report\x18\a \x01(\v2..sapient_msg.bsi_flex_335_v2_0.DetectionReportH\x00R\x0fdetectionReport\x129\n" +
	"\x04task\x18\b \x01(\v2#.sapient_msg.bsi_flex_335_v2_0.TaskH\x00R\x04task\x12C\n" +
	"\btask_ack\x18\t \x01(\v2&.sapient_msg.bsi_flex_335_v2_0.TaskAckH\x00R\ataskAck\x12<\n" +
	"\x05alert\x18\n" +
	" \x01(\v2$.sapient_msg.bsi_flex_335_v2_0.AlertH\x00R\x05alert\x12F\n" +
	"\talert_ack\x18\v \x01(\v2'.sapient_msg.bsi_flex_335_v2_0.AlertAckH\x00R\balertAck\x12<\n" +
	"\x05error\x18\f \x01(\v2$.sapient_msg.bsi_flex_335_v2_0.ErrorH\x00R\x05error\x12:\n" +
	"\x16additional_information\x18\r \x01(\tH\x04R\x15additionalInformation\x88\x01\x01B\x11\n" +
	"\acontent\x12\x06\x8a\xb5\x18\x02\b\x01B\f\n" +
	"\n" +
	"_timestampB\n" +
	"\n" +
	"\b_node_idB\x11\n" +
	"\x0f_destination_idB\x19\n" +
	"\x17_additional_informationBS\x8a\xea0\x13\n" +
	"\x11BSI_Flex_335_v2.0\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\x13SapientMessageProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_goTypes = []any{
	(*SapientMessage)(nil),        // 0: sapient_msg.bsi_flex_335_v2_0.SapientMessage
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*Registration)(nil),          // 2: sapient_msg.bsi_flex_335_v2_0.Registration
	(*RegistrationAck)(nil),       // 3: sapient_msg.bsi_flex_335_v2_0.RegistrationAck
	(*StatusReport)(nil),          // 4: sapient_msg.bsi_flex_335_v2_0.StatusReport
	(*DetectionReport)(nil),       // 5: sapient_msg.bsi_flex_335_v2_0.DetectionReport
	(*Task)(nil),                  // 6: sapient_msg.bsi_flex_335_v2_0.Task
	(*TaskAck)(nil),               // 7: sapient_msg.bsi_flex_335_v2_0.TaskAck
	(*Alert)(nil),                 // 8: sapient_msg.bsi_flex_335_v2_0.Alert
	(*AlertAck)(nil),              // 9: sapient_msg.bsi_flex_335_v2_0.AlertAck
	(*Error)(nil),                 // 10: sapient_msg.bsi_flex_335_v2_0.Error
}
var file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_depIdxs = []int32{
	1,  // 0: sapient_msg.bsi_flex_335_v2_0.SapientMessage.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 1: sapient_msg.bsi_flex_335_v2_0.SapientMessage.registration:type_name -> sapient_msg.bsi_flex_335_v2_0.Registration
	3,  // 2: sapient_msg.bsi_flex_335_v2_0.SapientMessage.registration_ack:type_name -> sapient_msg.bsi_flex_335_v2_0.RegistrationAck
	4,  // 3: sapient_msg.bsi_flex_335_v2_0.SapientMessage.status_report:type_name -> sapient_msg.bsi_flex_335_v2_0.StatusReport
	5,  // 4: sapient_msg.bsi_flex_335_v2_0.SapientMessage.detection_report:type_name -> sapient_msg.bsi_flex_335_v2_0.DetectionReport
	6,  // 5: sapient_msg.bsi_flex_335_v2_0.SapientMessage.task:type_name -> sapient_msg.bsi_flex_335_v2_0.Task
	7,  // 6: sapient_msg.bsi_flex_335_v2_0.SapientMessage.task_ack:type_name -> sapient_msg.bsi_flex_335_v2_0.TaskAck
	8,  // 7: sapient_msg.bsi_flex_335_v2_0.SapientMessage.alert:type_name -> sapient_msg.bsi_flex_335_v2_0.Alert
	9,  // 8: sapient_msg.bsi_flex_335_v2_0.SapientMessage.alert_ack:type_name -> sapient_msg.bsi_flex_335_v2_0.AlertAck
	10, // 9: sapient_msg.bsi_flex_335_v2_0.SapientMessage.error:type_name -> sapient_msg.bsi_flex_335_v2_0.Error
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto != nil {
		return
	}
	file_sapient_msg_bsi_flex_335_v2_0_alert_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_alert_ack_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_detection_report_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_error_proto_init()
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_registration_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_registration_ack_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_msgTypes[0].OneofWrappers = []any{
		(*SapientMessage_Registration)(nil),
		(*SapientMessage_RegistrationAck)(nil),
		(*SapientMessage_StatusReport)(nil),
		(*SapientMessage_DetectionReport)(nil),
		(*SapientMessage_Task)(nil),
		(*SapientMessage_TaskAck)(nil),
		(*SapientMessage_Alert)(nil),
		(*SapientMessage_AlertAck)(nil),
		(*SapientMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_depIdxs,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_sapient_message_proto_depIdxs = nil
}
