// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/status_report.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusReport_System int32

const (
	StatusReport_SYSTEM_UNSPECIFIED StatusReport_System = 0 // The system state is unset
	StatusReport_SYSTEM_OK          StatusReport_System = 1 // The system is operating normally
	StatusReport_SYSTEM_WARNING     StatusReport_System = 2 // There is a potential issue with the system
	StatusReport_SYSTEM_ERROR       StatusReport_System = 3 // There is an issue with the system
	// SYSTEM_TAMPER = 4; // The system has been tampered with - DEPRECIATED
	StatusReport_SYSTEM_GOODBYE StatusReport_System = 5 // The system is about to disconnect
)

// Enum value maps for StatusReport_System.
var (
	StatusReport_System_name = map[int32]string{
		0: "SYSTEM_UNSPECIFIED",
		1: "SYSTEM_OK",
		2: "SYSTEM_WARNING",
		3: "SYSTEM_ERROR",
		5: "SYSTEM_GOODBYE",
	}
	StatusReport_System_value = map[string]int32{
		"SYSTEM_UNSPECIFIED": 0,
		"SYSTEM_OK":          1,
		"SYSTEM_WARNING":     2,
		"SYSTEM_ERROR":       3,
		"SYSTEM_GOODBYE":     5,
	}
)

func (x StatusReport_System) Enum() *StatusReport_System {
	p := new(StatusReport_System)
	*p = x
	return p
}

func (x StatusReport_System) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusReport_System) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[0].Descriptor()
}

func (StatusReport_System) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[0]
}

func (x StatusReport_System) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusReport_System.Descriptor instead.
func (StatusReport_System) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescGZIP(), []int{0, 0}
}

type StatusReport_PowerSource int32

const (
	StatusReport_POWERSOURCE_UNSPECIFIED      StatusReport_PowerSource = 0 // The PowerSource is unset
	StatusReport_POWERSOURCE_OTHER            StatusReport_PowerSource = 1 // The power source is of a different type listed in this enumeration
	StatusReport_POWERSOURCE_MAINS            StatusReport_PowerSource = 2 // The power source is the mains (fixed infrastructure)
	StatusReport_POWERSOURCE_INTERNAL_BATTERY StatusReport_PowerSource = 3 // The power source is a battery contained within the node
	StatusReport_POWERSOURCE_EXTERNAL_BATTERY StatusReport_PowerSource = 4 // The power source is a battery external to the node
	StatusReport_POWERSOURCE_GENERATOR        StatusReport_PowerSource = 5 // The power source is a generator
	StatusReport_POWERSOURCE_SOLAR_PV         StatusReport_PowerSource = 6 // The power source is a solar photovoltaic panel/array
	StatusReport_POWERSOURCE_WIND_TURBINE     StatusReport_PowerSource = 7 // The power source is a wind turbine
	StatusReport_POWERSOURCE_FUEL_CELL        StatusReport_PowerSource = 8 // The power source is a fuel cell
)

// Enum value maps for StatusReport_PowerSource.
var (
	StatusReport_PowerSource_name = map[int32]string{
		0: "POWERSOURCE_UNSPECIFIED",
		1: "POWERSOURCE_OTHER",
		2: "POWERSOURCE_MAINS",
		3: "POWERSOURCE_INTERNAL_BATTERY",
		4: "POWERSOURCE_EXTERNAL_BATTERY",
		5: "POWERSOURCE_GENERATOR",
		6: "POWERSOURCE_SOLAR_PV",
		7: "POWERSOURCE_WIND_TURBINE",
		8: "POWERSOURCE_FUEL_CELL",
	}
	StatusReport_PowerSource_value = map[string]int32{
		"POWERSOURCE_UNSPECIFIED":      0,
		"POWERSOURCE_OTHER":            1,
		"POWERSOURCE_MAINS":            2,
		"POWERSOURCE_INTERNAL_BATTERY": 3,
		"POWERSOURCE_EXTERNAL_BATTERY": 4,
		"POWERSOURCE_GENERATOR":        5,
		"POWERSOURCE_SOLAR_PV":         6,
		"POWERSOURCE_WIND_TURBINE":     7,
		"POWERSOURCE_FUEL_CELL":        8,
	}
)

func (x StatusReport_PowerSource) Enum() *StatusReport_PowerSource {
	p := new(StatusReport_PowerSource)
	*p = x
	return p
}

func (x StatusReport_PowerSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusReport_PowerSource) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[1].Descriptor()
}

func (StatusReport_PowerSource) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[1]
}

func (x StatusReport_PowerSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusReport_PowerSource.Descriptor instead.
func (StatusReport_PowerSource) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescGZIP(), []int{0, 1}
}

type StatusReport_PowerStatus int32

const (
	StatusReport_POWERSTATUS_UNSPECIFIED StatusReport_PowerStatus = 0 // The PowerStatus is unset
	StatusReport_POWERSTATUS_OK          StatusReport_PowerStatus = 1 // The power status is normal
	StatusReport_POWERSTATUS_FAULT       StatusReport_PowerStatus = 2 // There is a fault with the power source
)

// Enum value maps for StatusReport_PowerStatus.
var (
	StatusReport_PowerStatus_name = map[int32]string{
		0: "POWERSTATUS_UNSPECIFIED",
		1: "POWERSTATUS_OK",
		2: "POWERSTATUS_FAULT",
	}
	StatusReport_PowerStatus_value = map[string]int32{
		"POWERSTATUS_UNSPECIFIED": 0,
		"POWERSTATUS_OK":          1,
		"POWERSTATUS_FAULT":       2,
	}
)

func (x StatusReport_PowerStatus) Enum() *StatusReport_PowerStatus {
	p := new(StatusReport_PowerStatus)
	*p = x
	return p
}

func (x StatusReport_PowerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusReport_PowerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[2].Descriptor()
}

func (StatusReport_PowerStatus) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[2]
}

func (x StatusReport_PowerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusReport_PowerStatus.Descriptor instead.
func (StatusReport_PowerStatus) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescGZIP(), []int{0, 2}
}

type StatusReport_Info int32

const (
	StatusReport_INFO_UNSPECIFIED StatusReport_Info = 0 // Unset enum
	StatusReport_INFO_NEW         StatusReport_Info = 1 // New information about the system is being presented
	StatusReport_INFO_UNCHANGED   StatusReport_Info = 2 // The existing information about the system is up-to-date
)

// Enum value maps for StatusReport_Info.
var (
	StatusReport_Info_name = map[int32]string{
		0: "INFO_UNSPECIFIED",
		1: "INFO_NEW",
		2: "INFO_UNCHANGED",
	}
	StatusReport_Info_value = map[string]int32{
		"INFO_UNSPECIFIED": 0,
		"INFO_NEW":         1,
		"INFO_UNCHANGED":   2,
	}
)

func (x StatusReport_Info) Enum() *StatusReport_Info {
	p := new(StatusReport_Info)
	*p = x
	return p
}

func (x StatusReport_Info) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusReport_Info) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[3].Descriptor()
}

func (StatusReport_Info) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[3]
}

func (x StatusReport_Info) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusReport_Info.Descriptor instead.
func (StatusReport_Info) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescGZIP(), []int{0, 3}
}

type StatusReport_StatusType int32

const (
	StatusReport_STATUS_TYPE_UNSPECIFIED        StatusReport_StatusType = 0  // No status type has been set
	StatusReport_STATUS_TYPE_INTERNAL_FAULT     StatusReport_StatusType = 1  // The node has an internal fault
	StatusReport_STATUS_TYPE_EXTERNAL_FAULT     StatusReport_StatusType = 2  // External influences have caused a fault with the node
	StatusReport_STATUS_TYPE_ILLUMINATION       StatusReport_StatusType = 3  //
	StatusReport_STATUS_TYPE_WEATHER            StatusReport_StatusType = 4  //
	StatusReport_STATUS_TYPE_CLUTTER            StatusReport_StatusType = 5  //
	StatusReport_STATUS_TYPE_EXPOSURE           StatusReport_StatusType = 6  //
	StatusReport_STATUS_TYPE_MOTION_SENSITIVITY StatusReport_StatusType = 7  //
	StatusReport_STATUS_TYPE_PTZ_STATUS         StatusReport_StatusType = 8  //
	StatusReport_STATUS_TYPE_PD                 StatusReport_StatusType = 9  //
	StatusReport_STATUS_TYPE_FAR                StatusReport_StatusType = 10 //
	StatusReport_STATUS_TYPE_NOT_DETECTING      StatusReport_StatusType = 11 // The node is not detecting
	StatusReport_STATUS_TYPE_PLATFORM           StatusReport_StatusType = 12 // A report about a platform node
	StatusReport_STATUS_TYPE_OTHER              StatusReport_StatusType = 13 //
)

// Enum value maps for StatusReport_StatusType.
var (
	StatusReport_StatusType_name = map[int32]string{
		0:  "STATUS_TYPE_UNSPECIFIED",
		1:  "STATUS_TYPE_INTERNAL_FAULT",
		2:  "STATUS_TYPE_EXTERNAL_FAULT",
		3:  "STATUS_TYPE_ILLUMINATION",
		4:  "STATUS_TYPE_WEATHER",
		5:  "STATUS_TYPE_CLUTTER",
		6:  "STATUS_TYPE_EXPOSURE",
		7:  "STATUS_TYPE_MOTION_SENSITIVITY",
		8:  "STATUS_TYPE_PTZ_STATUS",
		9:  "STATUS_TYPE_PD",
		10: "STATUS_TYPE_FAR",
		11: "STATUS_TYPE_NOT_DETECTING",
		12: "STATUS_TYPE_PLATFORM",
		13: "STATUS_TYPE_OTHER",
	}
	StatusReport_StatusType_value = map[string]int32{
		"STATUS_TYPE_UNSPECIFIED":        0,
		"STATUS_TYPE_INTERNAL_FAULT":     1,
		"STATUS_TYPE_EXTERNAL_FAULT":     2,
		"STATUS_TYPE_ILLUMINATION":       3,
		"STATUS_TYPE_WEATHER":            4,
		"STATUS_TYPE_CLUTTER":            5,
		"STATUS_TYPE_EXPOSURE":           6,
		"STATUS_TYPE_MOTION_SENSITIVITY": 7,
		"STATUS_TYPE_PTZ_STATUS":         8,
		"STATUS_TYPE_PD":                 9,
		"STATUS_TYPE_FAR":                10,
		"STATUS_TYPE_NOT_DETECTING":      11,
		"STATUS_TYPE_PLATFORM":           12,
		"STATUS_TYPE_OTHER":              13,
	}
)

func (x StatusReport_StatusType) Enum() *StatusReport_StatusType {
	p := new(StatusReport_StatusType)
	*p = x
	return p
}

func (x StatusReport_StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusReport_StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[4].Descriptor()
}

func (StatusReport_StatusType) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[4]
}

func (x StatusReport_StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusReport_StatusType.Descriptor instead.
func (StatusReport_StatusType) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescGZIP(), []int{0, 4}
}

type StatusReport_StatusLevel int32

const (
	StatusReport_STATUS_LEVEL_UNSPECIFIED StatusReport_StatusLevel = 0 // No status level has been set
	// STATUS_LEVEL_SENSOR_STATUS = 1; // Information about the current node state
	StatusReport_STATUS_LEVEL_INFORMATION_STATUS StatusReport_StatusLevel = 2 // Information about the environment that might affect this or other nodes
	StatusReport_STATUS_LEVEL_WARNING_STATUS     StatusReport_StatusLevel = 3 // Information about performance degregation of the node
	StatusReport_STATUS_LEVEL_ERROR_STATUS       StatusReport_StatusLevel = 4 // Information about severely affecting this node's capabilities
)

// Enum value maps for StatusReport_StatusLevel.
var (
	StatusReport_StatusLevel_name = map[int32]string{
		0: "STATUS_LEVEL_UNSPECIFIED",
		2: "STATUS_LEVEL_INFORMATION_STATUS",
		3: "STATUS_LEVEL_WARNING_STATUS",
		4: "STATUS_LEVEL_ERROR_STATUS",
	}
	StatusReport_StatusLevel_value = map[string]int32{
		"STATUS_LEVEL_UNSPECIFIED":        0,
		"STATUS_LEVEL_INFORMATION_STATUS": 2,
		"STATUS_LEVEL_WARNING_STATUS":     3,
		"STATUS_LEVEL_ERROR_STATUS":       4,
	}
)

func (x StatusReport_StatusLevel) Enum() *StatusReport_StatusLevel {
	p := new(StatusReport_StatusLevel)
	*p = x
	return p
}

func (x StatusReport_StatusLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusReport_StatusLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[5].Descriptor()
}

func (StatusReport_StatusLevel) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes[5]
}

func (x StatusReport_StatusLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusReport_StatusLevel.Descriptor instead.
func (StatusReport_StatusLevel) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescGZIP(), []int{0, 5}
}

// [START messages]
type StatusReport struct {
	state        protoimpl.MessageState  `protogen:"open.v1"`
	ReportId     *string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3,oneof" json:"report_id,omitempty"`                                     // ULID for the message
	System       *StatusReport_System    `protobuf:"varint,2,opt,name=system,proto3,enum=sapient_msg.bsi_flex_335_v2_0.StatusReport_System,oneof" json:"system,omitempty"` // Current ASM status
	Info         *StatusReport_Info      `protobuf:"varint,3,opt,name=info,proto3,enum=sapient_msg.bsi_flex_335_v2_0.StatusReport_Info,oneof" json:"info,omitempty"`       // State of the information in this message
	ActiveTaskId *string                 `protobuf:"bytes,4,opt,name=active_task_id,json=activeTaskId,proto3,oneof" json:"active_task_id,omitempty"`                       // ULID of the task the ASM is currently performing
	Mode         *string                 `protobuf:"bytes,5,opt,name=mode,proto3,oneof" json:"mode,omitempty"`                                                             // The current mode of the ASM
	Power        *StatusReport_Power     `protobuf:"bytes,6,opt,name=power,proto3,oneof" json:"power,omitempty"`                                                           // The power supply of the ASM
	NodeLocation *Location               `protobuf:"bytes,7,opt,name=node_location,json=nodeLocation,proto3,oneof" json:"node_location,omitempty"`                         // Current ASM location
	FieldOfView  *LocationOrRangeBearing `protobuf:"bytes,8,opt,name=field_of_view,json=fieldOfView,proto3,oneof" json:"field_of_view,omitempty"`                          // Area currently visible to ASM
	// optional LocationOrRangeBearing coverage = 9; // Area that the ASM can cover
	Obscuration   []*LocationOrRangeBearing `protobuf:"bytes,10,rep,name=obscuration,proto3" json:"obscuration,omitempty"` // Area that the ASM cannot cover
	Status        []*StatusReport_Status    `protobuf:"bytes,11,rep,name=status,proto3" json:"status,omitempty"`           // Information about the ASM or the envionrment
	Coverage      []*LocationOrRangeBearing `protobuf:"bytes,12,rep,name=coverage,proto3" json:"coverage,omitempty"`       // The coverage field has been made repeated so that a Fusion Node can report the total coverage from its child/edge nodes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescGZIP(), []int{0}
}

func (x *StatusReport) GetReportId() string {
	if x != nil && x.ReportId != nil {
		return *x.ReportId
	}
	return ""
}

func (x *StatusReport) GetSystem() StatusReport_System {
	if x != nil && x.System != nil {
		return *x.System
	}
	return StatusReport_SYSTEM_UNSPECIFIED
}

func (x *StatusReport) GetInfo() StatusReport_Info {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return StatusReport_INFO_UNSPECIFIED
}

func (x *StatusReport) GetActiveTaskId() string {
	if x != nil && x.ActiveTaskId != nil {
		return *x.ActiveTaskId
	}
	return ""
}

func (x *StatusReport) GetMode() string {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return ""
}

func (x *StatusReport) GetPower() *StatusReport_Power {
	if x != nil {
		return x.Power
	}
	return nil
}

func (x *StatusReport) GetNodeLocation() *Location {
	if x != nil {
		return x.NodeLocation
	}
	return nil
}

func (x *StatusReport) GetFieldOfView() *LocationOrRangeBearing {
	if x != nil {
		return x.FieldOfView
	}
	return nil
}

func (x *StatusReport) GetObscuration() []*LocationOrRangeBearing {
	if x != nil {
		return x.Obscuration
	}
	return nil
}

func (x *StatusReport) GetStatus() []*StatusReport_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StatusReport) GetCoverage() []*LocationOrRangeBearing {
	if x != nil {
		return x.Coverage
	}
	return nil
}

type StatusReport_Power struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// optional string source = 1; // Power source (e.g. battery/mains)
	// optional string status = 2; // Power supply status
	Level         *int32                   `protobuf:"varint,3,opt,name=level,proto3,oneof" json:"level,omitempty"`                                                         // Battery level 0-100
	Source        StatusReport_PowerSource `protobuf:"varint,4,opt,name=source,proto3,enum=sapient_msg.bsi_flex_335_v2_0.StatusReport_PowerSource" json:"source,omitempty"` // The power source being used by the node
	Status        StatusReport_PowerStatus `protobuf:"varint,5,opt,name=status,proto3,enum=sapient_msg.bsi_flex_335_v2_0.StatusReport_PowerStatus" json:"status,omitempty"` // The status of the power source being used by the node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport_Power) Reset() {
	*x = StatusReport_Power{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport_Power) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport_Power) ProtoMessage() {}

func (x *StatusReport_Power) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport_Power.ProtoReflect.Descriptor instead.
func (*StatusReport_Power) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescGZIP(), []int{0, 0}
}

func (x *StatusReport_Power) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *StatusReport_Power) GetSource() StatusReport_PowerSource {
	if x != nil {
		return x.Source
	}
	return StatusReport_POWERSOURCE_UNSPECIFIED
}

func (x *StatusReport_Power) GetStatus() StatusReport_PowerStatus {
	if x != nil {
		return x.Status
	}
	return StatusReport_POWERSTATUS_UNSPECIFIED
}

type StatusReport_Status struct {
	state       protoimpl.MessageState    `protogen:"open.v1"`
	StatusLevel *StatusReport_StatusLevel `protobuf:"varint,1,opt,name=status_level,json=statusLevel,proto3,enum=sapient_msg.bsi_flex_335_v2_0.StatusReport_StatusLevel,oneof" json:"status_level,omitempty"` // Information level being reported
	// optional string status_type = 2 [(field_options) = {is_mandatory: true}]; // Type of the information being reported (e.g. Weather)
	StatusValue   *string                  `protobuf:"bytes,3,opt,name=status_value,json=statusValue,proto3,oneof" json:"status_value,omitempty"`                                                          // Value of the information being reported (e.g. Raining)
	StatusType    *StatusReport_StatusType `protobuf:"varint,4,opt,name=status_type,json=statusType,proto3,enum=sapient_msg.bsi_flex_335_v2_0.StatusReport_StatusType,oneof" json:"status_type,omitempty"` // Type of the information being reported (e.g. Weather)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport_Status) Reset() {
	*x = StatusReport_Status{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport_Status) ProtoMessage() {}

func (x *StatusReport_Status) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport_Status.ProtoReflect.Descriptor instead.
func (*StatusReport_Status) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescGZIP(), []int{0, 1}
}

func (x *StatusReport_Status) GetStatusLevel() StatusReport_StatusLevel {
	if x != nil && x.StatusLevel != nil {
		return *x.StatusLevel
	}
	return StatusReport_STATUS_LEVEL_UNSPECIFIED
}

func (x *StatusReport_Status) GetStatusValue() string {
	if x != nil && x.StatusValue != nil {
		return *x.StatusValue
	}
	return ""
}

func (x *StatusReport_Status) GetStatusType() StatusReport_StatusType {
	if x != nil && x.StatusType != nil {
		return *x.StatusType
	}
	return StatusReport_STATUS_TYPE_UNSPECIFIED
}

var File_sapient_msg_bsi_flex_335_v2_0_status_report_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDesc = "" +
	"\n" +
	"1sapient_msg/bsi_flex_335_v2_0/status_report.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a,sapient_msg/bsi_flex_335_v2_0/location.proto\x1a1sapient_msg/bsi_flex_335_v2_0/range_bearing.proto\x1a\x1fsapient_msg/proto_options.proto\"\xf1\x13\n" +
	"\fStatusReport\x12*\n" +
	"\treport_id\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x10\x01H\x00R\breportId\x88\x01\x01\x12W\n" +
	"\x06system\x18\x02 \x01(\x0e22.sapient_msg.bsi_flex_335_v2_0.StatusReport.SystemB\x06\x8a\xb5\x18\x02\b\x01H\x01R\x06system\x88\x01\x01\x12Q\n" +
	"\x04info\x18\x03 \x01(\x0e20.sapient_msg.bsi_flex_335_v2_0.StatusReport.InfoB\x06\x8a\xb5\x18\x02\b\x01H\x02R\x04info\x88\x01\x01\x121\n" +
	"\x0eactive_task_id\x18\x04 \x01(\tB\x06\x8a\xb5\x18\x02\x10\x01H\x03R\factiveTaskId\x88\x01\x01\x12\x1f\n" +
	"\x04mode\x18\x05 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x04R\x04mode\x88\x01\x01\x12L\n" +
	"\x05power\x18\x06 \x01(\v21.sapient_msg.bsi_flex_335_v2_0.StatusReport.PowerH\x05R\x05power\x88\x01\x01\x12Q\n" +
	"\rnode_location\x18\a \x01(\v2'.sapient_msg.bsi_flex_335_v2_0.LocationH\x06R\fnodeLocation\x88\x01\x01\x12^\n" +
	"\rfield_of_view\x18\b \x01(\v25.sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearingH\aR\vfieldOfView\x88\x01\x01\x12W\n" +
	"\vobscuration\x18\n" +
	" \x03(\v25.sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearingR\vobscuration\x12J\n" +
	"\x06status\x18\v \x03(\v22.sapient_msg.bsi_flex_335_v2_0.StatusReport.StatusR\x06status\x12Q\n" +
	"\bcoverage\x18\f \x03(\v25.sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearingR\bcoverage\x1a\xda\x01\n" +
	"\x05Power\x12\x19\n" +
	"\x05level\x18\x03 \x01(\x05H\x00R\x05level\x88\x01\x01\x12O\n" +
	"\x06source\x18\x04 \x01(\x0e27.sapient_msg.bsi_flex_335_v2_0.StatusReport.PowerSourceR\x06source\x12O\n" +
	"\x06status\x18\x05 \x01(\x0e27.sapient_msg.bsi_flex_335_v2_0.StatusReport.PowerStatusR\x06statusB\b\n" +
	"\x06_levelJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\x1a\xaf\x02\n" +
	"\x06Status\x12_\n" +
	"\fstatus_level\x18\x01 \x01(\x0e27.sapient_msg.bsi_flex_335_v2_0.StatusReport.StatusLevelH\x00R\vstatusLevel\x88\x01\x01\x12&\n" +
	"\fstatus_value\x18\x03 \x01(\tH\x01R\vstatusValue\x88\x01\x01\x12d\n" +
	"\vstatus_type\x18\x04 \x01(\x0e26.sapient_msg.bsi_flex_335_v2_0.StatusReport.StatusTypeB\x06\x8a\xb5\x18\x02\b\x01H\x02R\n" +
	"statusType\x88\x01\x01B\x0f\n" +
	"\r_status_levelB\x0f\n" +
	"\r_status_valueB\x0e\n" +
	"\f_status_typeJ\x04\b\x02\x10\x03\"o\n" +
	"\x06System\x12\x16\n" +
	"\x12SYSTEM_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSYSTEM_OK\x10\x01\x12\x12\n" +
	"\x0eSYSTEM_WARNING\x10\x02\x12\x10\n" +
	"\fSYSTEM_ERROR\x10\x03\x12\x12\n" +
	"\x0eSYSTEM_GOODBYE\x10\x05\"\x04\b\x04\x10\x04\"\x8a\x02\n" +
	"\vPowerSource\x12\x1b\n" +
	"\x17POWERSOURCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11POWERSOURCE_OTHER\x10\x01\x12\x15\n" +
	"\x11POWERSOURCE_MAINS\x10\x02\x12 \n" +
	"\x1cPOWERSOURCE_INTERNAL_BATTERY\x10\x03\x12 \n" +
	"\x1cPOWERSOURCE_EXTERNAL_BATTERY\x10\x04\x12\x19\n" +
	"\x15POWERSOURCE_GENERATOR\x10\x05\x12\x18\n" +
	"\x14POWERSOURCE_SOLAR_PV\x10\x06\x12\x1c\n" +
	"\x18POWERSOURCE_WIND_TURBINE\x10\a\x12\x19\n" +
	"\x15POWERSOURCE_FUEL_CELL\x10\b\"U\n" +
	"\vPowerStatus\x12\x1b\n" +
	"\x17POWERSTATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePOWERSTATUS_OK\x10\x01\x12\x15\n" +
	"\x11POWERSTATUS_FAULT\x10\x02\">\n" +
	"\x04Info\x12\x14\n" +
	"\x10INFO_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bINFO_NEW\x10\x01\x12\x12\n" +
	"\x0eINFO_UNCHANGED\x10\x02\"\x8c\x03\n" +
	"\n" +
	"StatusType\x12\x1b\n" +
	"\x17STATUS_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSTATUS_TYPE_INTERNAL_FAULT\x10\x01\x12\x1e\n" +
	"\x1aSTATUS_TYPE_EXTERNAL_FAULT\x10\x02\x12\x1c\n" +
	"\x18STATUS_TYPE_ILLUMINATION\x10\x03\x12\x17\n" +
	"\x13STATUS_TYPE_WEATHER\x10\x04\x12\x17\n" +
	"\x13STATUS_TYPE_CLUTTER\x10\x05\x12\x18\n" +
	"\x14STATUS_TYPE_EXPOSURE\x10\x06\x12\"\n" +
	"\x1eSTATUS_TYPE_MOTION_SENSITIVITY\x10\a\x12\x1a\n" +
	"\x16STATUS_TYPE_PTZ_STATUS\x10\b\x12\x12\n" +
	"\x0eSTATUS_TYPE_PD\x10\t\x12\x13\n" +
	"\x0fSTATUS_TYPE_FAR\x10\n" +
	"\x12\x1d\n" +
	"\x19STATUS_TYPE_NOT_DETECTING\x10\v\x12\x18\n" +
	"\x14STATUS_TYPE_PLATFORM\x10\f\x12\x15\n" +
	"\x11STATUS_TYPE_OTHER\x10\r\"\x96\x01\n" +
	"\vStatusLevel\x12\x1c\n" +
	"\x18STATUS_LEVEL_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSTATUS_LEVEL_INFORMATION_STATUS\x10\x02\x12\x1f\n" +
	"\x1bSTATUS_LEVEL_WARNING_STATUS\x10\x03\x12\x1d\n" +
	"\x19STATUS_LEVEL_ERROR_STATUS\x10\x04\"\x04\b\x01\x10\x01B\f\n" +
	"\n" +
	"_report_idB\t\n" +
	"\a_systemB\a\n" +
	"\x05_infoB\x11\n" +
	"\x0f_active_task_idB\a\n" +
	"\x05_modeB\b\n" +
	"\x06_powerB\x10\n" +
	"\x0e_node_locationB\x10\n" +
	"\x0e_field_of_viewJ\x04\b\t\x10\n" +
	"B:\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\x11StatusReportProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_goTypes = []any{
	(StatusReport_System)(0),       // 0: sapient_msg.bsi_flex_335_v2_0.StatusReport.System
	(StatusReport_PowerSource)(0),  // 1: sapient_msg.bsi_flex_335_v2_0.StatusReport.PowerSource
	(StatusReport_PowerStatus)(0),  // 2: sapient_msg.bsi_flex_335_v2_0.StatusReport.PowerStatus
	(StatusReport_Info)(0),         // 3: sapient_msg.bsi_flex_335_v2_0.StatusReport.Info
	(StatusReport_StatusType)(0),   // 4: sapient_msg.bsi_flex_335_v2_0.StatusReport.StatusType
	(StatusReport_StatusLevel)(0),  // 5: sapient_msg.bsi_flex_335_v2_0.StatusReport.StatusLevel
	(*StatusReport)(nil),           // 6: sapient_msg.bsi_flex_335_v2_0.StatusReport
	(*StatusReport_Power)(nil),     // 7: sapient_msg.bsi_flex_335_v2_0.StatusReport.Power
	(*StatusReport_Status)(nil),    // 8: sapient_msg.bsi_flex_335_v2_0.StatusReport.Status
	(*Location)(nil),               // 9: sapient_msg.bsi_flex_335_v2_0.Location
	(*LocationOrRangeBearing)(nil), // 10: sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing
}
var file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_depIdxs = []int32{
	0,  // 0: sapient_msg.bsi_flex_335_v2_0.StatusReport.system:type_name -> sapient_msg.bsi_flex_335_v2_0.StatusReport.System
	3,  // 1: sapient_msg.bsi_flex_335_v2_0.StatusReport.info:type_name -> sapient_msg.bsi_flex_335_v2_0.StatusReport.Info
	7,  // 2: sapient_msg.bsi_flex_335_v2_0.StatusReport.power:type_name -> sapient_msg.bsi_flex_335_v2_0.StatusReport.Power
	9,  // 3: sapient_msg.bsi_flex_335_v2_0.StatusReport.node_location:type_name -> sapient_msg.bsi_flex_335_v2_0.Location
	10, // 4: sapient_msg.bsi_flex_335_v2_0.StatusReport.field_of_view:type_name -> sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing
	10, // 5: sapient_msg.bsi_flex_335_v2_0.StatusReport.obscuration:type_name -> sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing
	8,  // 6: sapient_msg.bsi_flex_335_v2_0.StatusReport.status:type_name -> sapient_msg.bsi_flex_335_v2_0.StatusReport.Status
	10, // 7: sapient_msg.bsi_flex_335_v2_0.StatusReport.coverage:type_name -> sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing
	1,  // 8: sapient_msg.bsi_flex_335_v2_0.StatusReport.Power.source:type_name -> sapient_msg.bsi_flex_335_v2_0.StatusReport.PowerSource
	2,  // 9: sapient_msg.bsi_flex_335_v2_0.StatusReport.Power.status:type_name -> sapient_msg.bsi_flex_335_v2_0.StatusReport.PowerStatus
	5,  // 10: sapient_msg.bsi_flex_335_v2_0.StatusReport.Status.status_level:type_name -> sapient_msg.bsi_flex_335_v2_0.StatusReport.StatusLevel
	4,  // 11: sapient_msg.bsi_flex_335_v2_0.StatusReport.Status.status_type:type_name -> sapient_msg.bsi_flex_335_v2_0.StatusReport.StatusType
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_status_report_proto != nil {
		return
	}
	file_sapient_msg_bsi_flex_335_v2_0_location_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_init()
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_msgTypes[0].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_msgTypes[1].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_depIdxs,
		EnumInfos:         file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_enumTypes,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_status_report_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_status_report_proto_depIdxs = nil
}
