// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/task_ack.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskAck_TaskStatus int32

const (
	TaskAck_TASK_STATUS_UNSPECIFIED TaskAck_TaskStatus = 0 // Unset enum
	TaskAck_TASK_STATUS_ACCEPTED    TaskAck_TaskStatus = 1 // Task was accepted
	TaskAck_TASK_STATUS_REJECTED    TaskAck_TaskStatus = 2 // Task was rejected (reason should also be present in the message)
	TaskAck_TASK_STATUS_COMPLETED   TaskAck_TaskStatus = 3 // Task has been completed
	TaskAck_TASK_STATUS_FAILED      TaskAck_TaskStatus = 4 // A node has previously accepted a task but has been unable to successfully complete it.
)

// Enum value maps for TaskAck_TaskStatus.
var (
	TaskAck_TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_ACCEPTED",
		2: "TASK_STATUS_REJECTED",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_FAILED",
	}
	TaskAck_TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_ACCEPTED":    1,
		"TASK_STATUS_REJECTED":    2,
		"TASK_STATUS_COMPLETED":   3,
		"TASK_STATUS_FAILED":      4,
	}
)

func (x TaskAck_TaskStatus) Enum() *TaskAck_TaskStatus {
	p := new(TaskAck_TaskStatus)
	*p = x
	return p
}

func (x TaskAck_TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskAck_TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_enumTypes[0].Descriptor()
}

func (TaskAck_TaskStatus) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_enumTypes[0]
}

func (x TaskAck_TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskAck_TaskStatus.Descriptor instead.
func (TaskAck_TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDescGZIP(), []int{0, 0}
}

// [START messages]
type TaskAck struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TaskId     *string                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`                                                                    // ULID of task that is being acknowledged
	TaskStatus *TaskAck_TaskStatus    `protobuf:"varint,2,opt,name=task_status,json=taskStatus,proto3,enum=sapient_msg.bsi_flex_335_v2_0.TaskAck_TaskStatus,oneof" json:"task_status,omitempty"` // Status of the task (accepted or rejected)
	// optional string reason = 3; // Reason for the rejection if task is rejected or completed
	AssociatedFile *AssociatedFile `protobuf:"bytes,4,opt,name=associated_file,json=associatedFile,proto3,oneof" json:"associated_file,omitempty"` // File associated with task being acknowledged
	Reason         []string        `protobuf:"bytes,5,rep,name=reason,proto3" json:"reason,omitempty"`                                             // Reason(s) for the rejection if task is rejected, completed, or failed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskAck) Reset() {
	*x = TaskAck{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAck) ProtoMessage() {}

func (x *TaskAck) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAck.ProtoReflect.Descriptor instead.
func (*TaskAck) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDescGZIP(), []int{0}
}

func (x *TaskAck) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *TaskAck) GetTaskStatus() TaskAck_TaskStatus {
	if x != nil && x.TaskStatus != nil {
		return *x.TaskStatus
	}
	return TaskAck_TASK_STATUS_UNSPECIFIED
}

func (x *TaskAck) GetAssociatedFile() *AssociatedFile {
	if x != nil {
		return x.AssociatedFile
	}
	return nil
}

func (x *TaskAck) GetReason() []string {
	if x != nil {
		return x.Reason
	}
	return nil
}

var File_sapient_msg_bsi_flex_335_v2_0_task_ack_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDesc = "" +
	"\n" +
	",sapient_msg/bsi_flex_335_v2_0/task_ack.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a3sapient_msg/bsi_flex_335_v2_0/associated_file.proto\x1a\x1fsapient_msg/proto_options.proto\"\xd0\x03\n" +
	"\aTaskAck\x12&\n" +
	"\atask_id\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x10\x01H\x00R\x06taskId\x88\x01\x01\x12_\n" +
	"\vtask_status\x18\x02 \x01(\x0e21.sapient_msg.bsi_flex_335_v2_0.TaskAck.TaskStatusB\x06\x8a\xb5\x18\x02\b\x01H\x01R\n" +
	"taskStatus\x88\x01\x01\x12[\n" +
	"\x0fassociated_file\x18\x04 \x01(\v2-.sapient_msg.bsi_flex_335_v2_0.AssociatedFileH\x02R\x0eassociatedFile\x88\x01\x01\x12\x16\n" +
	"\x06reason\x18\x05 \x03(\tR\x06reason\"\x90\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_STATUS_ACCEPTED\x10\x01\x12\x18\n" +
	"\x14TASK_STATUS_REJECTED\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04B\n" +
	"\n" +
	"\b_task_idB\x0e\n" +
	"\f_task_statusB\x12\n" +
	"\x10_associated_fileJ\x04\b\x03\x10\x04B5\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\fTaskAckProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_goTypes = []any{
	(TaskAck_TaskStatus)(0), // 0: sapient_msg.bsi_flex_335_v2_0.TaskAck.TaskStatus
	(*TaskAck)(nil),         // 1: sapient_msg.bsi_flex_335_v2_0.TaskAck
	(*AssociatedFile)(nil),  // 2: sapient_msg.bsi_flex_335_v2_0.AssociatedFile
}
var file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_depIdxs = []int32{
	0, // 0: sapient_msg.bsi_flex_335_v2_0.TaskAck.task_status:type_name -> sapient_msg.bsi_flex_335_v2_0.TaskAck.TaskStatus
	2, // 1: sapient_msg.bsi_flex_335_v2_0.TaskAck.associated_file:type_name -> sapient_msg.bsi_flex_335_v2_0.AssociatedFile
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_task_ack_proto != nil {
		return
	}
	file_sapient_msg_bsi_flex_335_v2_0_associated_file_proto_init()
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_depIdxs,
		EnumInfos:         file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_enumTypes,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_task_ack_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_task_ack_proto_depIdxs = nil
}
