// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/task.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task_Control int32

const (
	Task_CONTROL_UNSPECIFIED Task_Control = 0 // No control set
	Task_CONTROL_START       Task_Control = 1 // Initialise/start the task
	Task_CONTROL_STOP        Task_Control = 2 // Stop the task, remove the definition and revert to the previous task
	Task_CONTROL_PAUSE       Task_Control = 3 // Stop the task, keep the definition for later use and revert to previous task
)

// Enum value maps for Task_Control.
var (
	Task_Control_name = map[int32]string{
		0: "CONTROL_UNSPECIFIED",
		1: "CONTROL_START",
		2: "CONTROL_STOP",
		3: "CONTROL_PAUSE",
	}
	Task_Control_value = map[string]int32{
		"CONTROL_UNSPECIFIED": 0,
		"CONTROL_START":       1,
		"CONTROL_STOP":        2,
		"CONTROL_PAUSE":       3,
	}
)

func (x Task_Control) Enum() *Task_Control {
	p := new(Task_Control)
	*p = x
	return p
}

func (x Task_Control) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_Control) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_enumTypes[0].Descriptor()
}

func (Task_Control) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_task_proto_enumTypes[0]
}

func (x Task_Control) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_Control.Descriptor instead.
func (Task_Control) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescGZIP(), []int{0, 0}
}

type Task_DiscreteThreshold int32

const (
	Task_DISCRETE_THRESHOLD_UNSPECIFIED Task_DiscreteThreshold = 0 // Threshold not set
	Task_DISCRETE_THRESHOLD_LOW         Task_DiscreteThreshold = 1 // Threshold set to low
	Task_DISCRETE_THRESHOLD_MEDIUM      Task_DiscreteThreshold = 2 // Threshold set to medium
	Task_DISCRETE_THRESHOLD_HIGH        Task_DiscreteThreshold = 3 // Threshold set to high
)

// Enum value maps for Task_DiscreteThreshold.
var (
	Task_DiscreteThreshold_name = map[int32]string{
		0: "DISCRETE_THRESHOLD_UNSPECIFIED",
		1: "DISCRETE_THRESHOLD_LOW",
		2: "DISCRETE_THRESHOLD_MEDIUM",
		3: "DISCRETE_THRESHOLD_HIGH",
	}
	Task_DiscreteThreshold_value = map[string]int32{
		"DISCRETE_THRESHOLD_UNSPECIFIED": 0,
		"DISCRETE_THRESHOLD_LOW":         1,
		"DISCRETE_THRESHOLD_MEDIUM":      2,
		"DISCRETE_THRESHOLD_HIGH":        3,
	}
)

func (x Task_DiscreteThreshold) Enum() *Task_DiscreteThreshold {
	p := new(Task_DiscreteThreshold)
	*p = x
	return p
}

func (x Task_DiscreteThreshold) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_DiscreteThreshold) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_enumTypes[1].Descriptor()
}

func (Task_DiscreteThreshold) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_task_proto_enumTypes[1]
}

func (x Task_DiscreteThreshold) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_DiscreteThreshold.Descriptor instead.
func (Task_DiscreteThreshold) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescGZIP(), []int{0, 1}
}

// Note: enum RegionType also features in registration.proto, if making changes to this enumeration, identical changes must be made
// in the same enumeration in registration.proto. Users should be aware, future versions of the SAPIENT proto files may be
// restructured so that enum RegionType only appears once.
type Task_RegionType int32

const (
	Task_REGION_TYPE_UNSPECIFIED            Task_RegionType = 0 // No region type set
	Task_REGION_TYPE_AREA_OF_INTEREST       Task_RegionType = 1 // Region is of particular interest
	Task_REGION_TYPE_IGNORE                 Task_RegionType = 2 // Region to be ignored
	Task_REGION_TYPE_BOUNDARY               Task_RegionType = 3 // Region defines the boundary of the area of operations
	Task_REGION_TYPE_MOBILE_NODE_NO_GO_AREA Task_RegionType = 4 // Region defines an area that mobile nodes shall not enter
	Task_REGION_TYPE_MOBILE_NODE_GO_AREA    Task_RegionType = 5 //Region defines an area that mobile nodes shall remain within
)

// Enum value maps for Task_RegionType.
var (
	Task_RegionType_name = map[int32]string{
		0: "REGION_TYPE_UNSPECIFIED",
		1: "REGION_TYPE_AREA_OF_INTEREST",
		2: "REGION_TYPE_IGNORE",
		3: "REGION_TYPE_BOUNDARY",
		4: "REGION_TYPE_MOBILE_NODE_NO_GO_AREA",
		5: "REGION_TYPE_MOBILE_NODE_GO_AREA",
	}
	Task_RegionType_value = map[string]int32{
		"REGION_TYPE_UNSPECIFIED":            0,
		"REGION_TYPE_AREA_OF_INTEREST":       1,
		"REGION_TYPE_IGNORE":                 2,
		"REGION_TYPE_BOUNDARY":               3,
		"REGION_TYPE_MOBILE_NODE_NO_GO_AREA": 4,
		"REGION_TYPE_MOBILE_NODE_GO_AREA":    5,
	}
)

func (x Task_RegionType) Enum() *Task_RegionType {
	p := new(Task_RegionType)
	*p = x
	return p
}

func (x Task_RegionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_RegionType) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_enumTypes[2].Descriptor()
}

func (Task_RegionType) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_task_proto_enumTypes[2]
}

func (x Task_RegionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_RegionType.Descriptor instead.
func (Task_RegionType) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescGZIP(), []int{0, 2}
}

type Task struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          *string                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`                                      // ULID for the task being sent
	TaskName        *string                `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3,oneof" json:"task_name,omitempty"`                                // Name of the task being requested
	TaskDescription *string                `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,proto3,oneof" json:"task_description,omitempty"`           // Description of the task being requested
	TaskStartTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=task_start_time,json=taskStartTime,proto3,oneof" json:"task_start_time,omitempty"`               // Time the task is requested to start at
	TaskEndTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=task_end_time,json=taskEndTime,proto3,oneof" json:"task_end_time,omitempty"`                     // Time the task is requested to end at
	Control         *Task_Control          `protobuf:"varint,6,opt,name=control,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Task_Control,oneof" json:"control,omitempty"` // Control action being requested
	Region          []*Task_Region         `protobuf:"bytes,7,rep,name=region,proto3" json:"region,omitempty"`                                                          // Area tasking is to be applied (such as a system implementing geo-fencing)
	Command         *Task_Command          `protobuf:"bytes,8,opt,name=command,proto3,oneof" json:"command,omitempty"`                                                  // Command being requested as part the task
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *Task) GetTaskName() string {
	if x != nil && x.TaskName != nil {
		return *x.TaskName
	}
	return ""
}

func (x *Task) GetTaskDescription() string {
	if x != nil && x.TaskDescription != nil {
		return *x.TaskDescription
	}
	return ""
}

func (x *Task) GetTaskStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TaskStartTime
	}
	return nil
}

func (x *Task) GetTaskEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TaskEndTime
	}
	return nil
}

func (x *Task) GetControl() Task_Control {
	if x != nil && x.Control != nil {
		return *x.Control
	}
	return Task_CONTROL_UNSPECIFIED
}

func (x *Task) GetRegion() []*Task_Region {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *Task) GetCommand() *Task_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type Task_Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*Task_Command_Request
	//	*Task_Command_DetectionThreshold
	//	*Task_Command_DetectionReportRate
	//	*Task_Command_ClassificationThreshold
	//	*Task_Command_ModeChange
	//	*Task_Command_LookAt
	//	*Task_Command_MoveTo
	//	*Task_Command_Patrol
	//	*Task_Command_Follow
	Command          isTask_Command_Command `protobuf_oneof:"command"`
	CommandParameter *string                `protobuf:"bytes,8,opt,name=command_parameter,json=commandParameter,proto3,oneof" json:"command_parameter,omitempty"` // Parameter string for some commands
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Task_Command) Reset() {
	*x = Task_Command{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Command) ProtoMessage() {}

func (x *Task_Command) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Command.ProtoReflect.Descriptor instead.
func (*Task_Command) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Task_Command) GetCommand() isTask_Command_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Task_Command) GetRequest() string {
	if x != nil {
		if x, ok := x.Command.(*Task_Command_Request); ok {
			return x.Request
		}
	}
	return ""
}

func (x *Task_Command) GetDetectionThreshold() Task_DiscreteThreshold {
	if x != nil {
		if x, ok := x.Command.(*Task_Command_DetectionThreshold); ok {
			return x.DetectionThreshold
		}
	}
	return Task_DISCRETE_THRESHOLD_UNSPECIFIED
}

func (x *Task_Command) GetDetectionReportRate() Task_DiscreteThreshold {
	if x != nil {
		if x, ok := x.Command.(*Task_Command_DetectionReportRate); ok {
			return x.DetectionReportRate
		}
	}
	return Task_DISCRETE_THRESHOLD_UNSPECIFIED
}

func (x *Task_Command) GetClassificationThreshold() Task_DiscreteThreshold {
	if x != nil {
		if x, ok := x.Command.(*Task_Command_ClassificationThreshold); ok {
			return x.ClassificationThreshold
		}
	}
	return Task_DISCRETE_THRESHOLD_UNSPECIFIED
}

func (x *Task_Command) GetModeChange() string {
	if x != nil {
		if x, ok := x.Command.(*Task_Command_ModeChange); ok {
			return x.ModeChange
		}
	}
	return ""
}

func (x *Task_Command) GetLookAt() *LocationOrRangeBearing {
	if x != nil {
		if x, ok := x.Command.(*Task_Command_LookAt); ok {
			return x.LookAt
		}
	}
	return nil
}

func (x *Task_Command) GetMoveTo() *LocationList {
	if x != nil {
		if x, ok := x.Command.(*Task_Command_MoveTo); ok {
			return x.MoveTo
		}
	}
	return nil
}

func (x *Task_Command) GetPatrol() *LocationList {
	if x != nil {
		if x, ok := x.Command.(*Task_Command_Patrol); ok {
			return x.Patrol
		}
	}
	return nil
}

func (x *Task_Command) GetFollow() *FollowObject {
	if x != nil {
		if x, ok := x.Command.(*Task_Command_Follow); ok {
			return x.Follow
		}
	}
	return nil
}

func (x *Task_Command) GetCommandParameter() string {
	if x != nil && x.CommandParameter != nil {
		return *x.CommandParameter
	}
	return ""
}

type isTask_Command_Command interface {
	isTask_Command_Command()
}

type Task_Command_Request struct {
	Request string `protobuf:"bytes,1,opt,name=request,proto3,oneof"` // The request being asked for
}

type Task_Command_DetectionThreshold struct {
	DetectionThreshold Task_DiscreteThreshold `protobuf:"varint,2,opt,name=detection_threshold,json=detectionThreshold,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Task_DiscreteThreshold,oneof"` // The requested sensitivity of sensor during the task
}

type Task_Command_DetectionReportRate struct {
	DetectionReportRate Task_DiscreteThreshold `protobuf:"varint,3,opt,name=detection_report_rate,json=detectionReportRate,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Task_DiscreteThreshold,oneof"` // The requested reporting rate of sensor during the task
}

type Task_Command_ClassificationThreshold struct {
	ClassificationThreshold Task_DiscreteThreshold `protobuf:"varint,4,opt,name=classification_threshold,json=classificationThreshold,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Task_DiscreteThreshold,oneof"` // The requested classification sensitivity of sensor during the task
}

type Task_Command_ModeChange struct {
	ModeChange string `protobuf:"bytes,5,opt,name=mode_change,json=modeChange,proto3,oneof"` // Mode change for the ASM
}

type Task_Command_LookAt struct {
	LookAt *LocationOrRangeBearing `protobuf:"bytes,6,opt,name=look_at,json=lookAt,proto3,oneof"` // LookAt command for tasking pointing ASMs
}

type Task_Command_MoveTo struct {
	MoveTo *LocationList `protobuf:"bytes,9,opt,name=move_to,json=moveTo,proto3,oneof"` //command for instructing a mobile node to move to a new location
}

type Task_Command_Patrol struct {
	Patrol *LocationList `protobuf:"bytes,10,opt,name=patrol,proto3,oneof"` // command for instructing a mobile node to continually patrol a route until instructed otherwise
}

type Task_Command_Follow struct {
	Follow *FollowObject `protobuf:"bytes,11,opt,name=follow,proto3,oneof"` //command for instructing a mobile node to follow a moving object until instructed otherwise
}

func (*Task_Command_Request) isTask_Command_Command() {}

func (*Task_Command_DetectionThreshold) isTask_Command_Command() {}

func (*Task_Command_DetectionReportRate) isTask_Command_Command() {}

func (*Task_Command_ClassificationThreshold) isTask_Command_Command() {}

func (*Task_Command_ModeChange) isTask_Command_Command() {}

func (*Task_Command_LookAt) isTask_Command_Command() {}

func (*Task_Command_MoveTo) isTask_Command_Command() {}

func (*Task_Command_Patrol) isTask_Command_Command() {}

func (*Task_Command_Follow) isTask_Command_Command() {}

type Task_Region struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Type            *Task_RegionType        `protobuf:"varint,1,opt,name=type,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Task_RegionType,oneof" json:"type,omitempty"` // Type of region
	RegionId        *string                 `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3,oneof" json:"region_id,omitempty"`                             // Unique ID of region
	RegionName      *string                 `protobuf:"bytes,3,opt,name=region_name,json=regionName,proto3,oneof" json:"region_name,omitempty"`                       // Name of region
	RegionArea      *LocationOrRangeBearing `protobuf:"bytes,4,opt,name=region_area,json=regionArea,proto3,oneof" json:"region_area,omitempty"`                       // Area that defines the region
	ClassFilter     []*Task_ClassFilter     `protobuf:"bytes,5,rep,name=class_filter,json=classFilter,proto3" json:"class_filter,omitempty"`                          // Filter for classifications detected in the region
	BehaviourFilter []*Task_BehaviourFilter `protobuf:"bytes,6,rep,name=behaviour_filter,json=behaviourFilter,proto3" json:"behaviour_filter,omitempty"`              // Filter for behaviours detected in the region
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Task_Region) Reset() {
	*x = Task_Region{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Region) ProtoMessage() {}

func (x *Task_Region) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Region.ProtoReflect.Descriptor instead.
func (*Task_Region) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Task_Region) GetType() Task_RegionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Task_REGION_TYPE_UNSPECIFIED
}

func (x *Task_Region) GetRegionId() string {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return ""
}

func (x *Task_Region) GetRegionName() string {
	if x != nil && x.RegionName != nil {
		return *x.RegionName
	}
	return ""
}

func (x *Task_Region) GetRegionArea() *LocationOrRangeBearing {
	if x != nil {
		return x.RegionArea
	}
	return nil
}

func (x *Task_Region) GetClassFilter() []*Task_ClassFilter {
	if x != nil {
		return x.ClassFilter
	}
	return nil
}

func (x *Task_Region) GetBehaviourFilter() []*Task_BehaviourFilter {
	if x != nil {
		return x.BehaviourFilter
	}
	return nil
}

type Task_ClassFilter struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Parameter      *Task_Parameter         `protobuf:"bytes,1,opt,name=parameter,proto3,oneof" json:"parameter,omitempty"`                                                          // Parameter to filter on
	Type           *string                 `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`                                                                    // Type of classification to filter on
	SubClassFilter []*Task_SubClassFilter  `protobuf:"bytes,3,rep,name=sub_class_filter,json=subClassFilter,proto3" json:"sub_class_filter,omitempty"`                              // Sub-classes to filter on
	Priority       *Task_DiscreteThreshold `protobuf:"varint,4,opt,name=priority,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Task_DiscreteThreshold,oneof" json:"priority,omitempty"` // Priority of filter
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task_ClassFilter) Reset() {
	*x = Task_ClassFilter{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_ClassFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_ClassFilter) ProtoMessage() {}

func (x *Task_ClassFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_ClassFilter.ProtoReflect.Descriptor instead.
func (*Task_ClassFilter) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Task_ClassFilter) GetParameter() *Task_Parameter {
	if x != nil {
		return x.Parameter
	}
	return nil
}

func (x *Task_ClassFilter) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Task_ClassFilter) GetSubClassFilter() []*Task_SubClassFilter {
	if x != nil {
		return x.SubClassFilter
	}
	return nil
}

func (x *Task_ClassFilter) GetPriority() Task_DiscreteThreshold {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return Task_DISCRETE_THRESHOLD_UNSPECIFIED
}

type Task_SubClassFilter struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Parameter      *Task_Parameter         `protobuf:"bytes,1,opt,name=parameter,proto3,oneof" json:"parameter,omitempty"`                                                          // Parameter to filter on
	Type           *string                 `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`                                                                    // Type of classification to filter on
	SubClassFilter []*Task_SubClassFilter  `protobuf:"bytes,3,rep,name=sub_class_filter,json=subClassFilter,proto3" json:"sub_class_filter,omitempty"`                              // Sub-classes to filter on
	Priority       *Task_DiscreteThreshold `protobuf:"varint,4,opt,name=priority,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Task_DiscreteThreshold,oneof" json:"priority,omitempty"` // Priority of filter
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task_SubClassFilter) Reset() {
	*x = Task_SubClassFilter{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_SubClassFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_SubClassFilter) ProtoMessage() {}

func (x *Task_SubClassFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_SubClassFilter.ProtoReflect.Descriptor instead.
func (*Task_SubClassFilter) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Task_SubClassFilter) GetParameter() *Task_Parameter {
	if x != nil {
		return x.Parameter
	}
	return nil
}

func (x *Task_SubClassFilter) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Task_SubClassFilter) GetSubClassFilter() []*Task_SubClassFilter {
	if x != nil {
		return x.SubClassFilter
	}
	return nil
}

func (x *Task_SubClassFilter) GetPriority() Task_DiscreteThreshold {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return Task_DISCRETE_THRESHOLD_UNSPECIFIED
}

type Task_BehaviourFilter struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Parameter     *Task_Parameter         `protobuf:"bytes,1,opt,name=parameter,proto3,oneof" json:"parameter,omitempty"`                                                          // Parameter to filter on
	Type          *string                 `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`                                                                    // Type of behaviour to filter on
	Priority      *Task_DiscreteThreshold `protobuf:"varint,3,opt,name=priority,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Task_DiscreteThreshold,oneof" json:"priority,omitempty"` // Priority of filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_BehaviourFilter) Reset() {
	*x = Task_BehaviourFilter{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_BehaviourFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_BehaviourFilter) ProtoMessage() {}

func (x *Task_BehaviourFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_BehaviourFilter.ProtoReflect.Descriptor instead.
func (*Task_BehaviourFilter) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Task_BehaviourFilter) GetParameter() *Task_Parameter {
	if x != nil {
		return x.Parameter
	}
	return nil
}

func (x *Task_BehaviourFilter) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Task_BehaviourFilter) GetPriority() Task_DiscreteThreshold {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return Task_DISCRETE_THRESHOLD_UNSPECIFIED
}

type Task_Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`                                                      // Name of the parameter to filter
	Operator      *Operator              `protobuf:"varint,2,opt,name=operator,proto3,enum=sapient_msg.bsi_flex_335_v2_0.Operator,oneof" json:"operator,omitempty"` // Operator to be filtered on
	Value         *float32               `protobuf:"fixed32,3,opt,name=value,proto3,oneof" json:"value,omitempty"`                                                  // Threshold
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_Parameter) Reset() {
	*x = Task_Parameter{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Parameter) ProtoMessage() {}

func (x *Task_Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Parameter.ProtoReflect.Descriptor instead.
func (*Task_Parameter) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Task_Parameter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Task_Parameter) GetOperator() Operator {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return Operator_OPERATOR_UNSPECIFIED
}

func (x *Task_Parameter) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

var File_sapient_msg_bsi_flex_335_v2_0_task_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDesc = "" +
	"\n" +
	"(sapient_msg/bsi_flex_335_v2_0/task.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,sapient_msg/bsi_flex_335_v2_0/location.proto\x1a1sapient_msg/bsi_flex_335_v2_0/range_bearing.proto\x1a*sapient_msg/bsi_flex_335_v2_0/follow.proto\x1a0sapient_msg/bsi_flex_335_v2_0/registration.proto\x1a\x1fsapient_msg/proto_options.proto\"\xd9\x1b\n" +
	"\x04Task\x12&\n" +
	"\atask_id\x18\x01 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x10\x01H\x00R\x06taskId\x88\x01\x01\x12 \n" +
	"\ttask_name\x18\x02 \x01(\tH\x01R\btaskName\x88\x01\x01\x12.\n" +
	"\x10task_description\x18\x03 \x01(\tH\x02R\x0ftaskDescription\x88\x01\x01\x12G\n" +
	"\x0ftask_start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\rtaskStartTime\x88\x01\x01\x12C\n" +
	"\rtask_end_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\vtaskEndTime\x88\x01\x01\x12R\n" +
	"\acontrol\x18\x06 \x01(\x0e2+.sapient_msg.bsi_flex_335_v2_0.Task.ControlB\x06\x8a\xb5\x18\x02\b\x01H\x05R\acontrol\x88\x01\x01\x12B\n" +
	"\x06region\x18\a \x03(\v2*.sapient_msg.bsi_flex_335_v2_0.Task.RegionR\x06region\x12J\n" +
	"\acommand\x18\b \x01(\v2+.sapient_msg.bsi_flex_335_v2_0.Task.CommandH\x06R\acommand\x88\x01\x01\x1a\x9c\x06\n" +
	"\aCommand\x12\x1a\n" +
	"\arequest\x18\x01 \x01(\tH\x00R\arequest\x12h\n" +
	"\x13detection_threshold\x18\x02 \x01(\x0e25.sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThresholdH\x00R\x12detectionThreshold\x12k\n" +
	"\x15detection_report_rate\x18\x03 \x01(\x0e25.sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThresholdH\x00R\x13detectionReportRate\x12r\n" +
	"\x18classification_threshold\x18\x04 \x01(\x0e25.sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThresholdH\x00R\x17classificationThreshold\x12!\n" +
	"\vmode_change\x18\x05 \x01(\tH\x00R\n" +
	"modeChange\x12P\n" +
	"\alook_at\x18\x06 \x01(\v25.sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearingH\x00R\x06lookAt\x12F\n" +
	"\amove_to\x18\t \x01(\v2+.sapient_msg.bsi_flex_335_v2_0.LocationListH\x00R\x06moveTo\x12E\n" +
	"\x06patrol\x18\n" +
	" \x01(\v2+.sapient_msg.bsi_flex_335_v2_0.LocationListH\x00R\x06patrol\x12E\n" +
	"\x06follow\x18\v \x01(\v2+.sapient_msg.bsi_flex_335_v2_0.FollowObjectH\x00R\x06follow\x120\n" +
	"\x11command_parameter\x18\b \x01(\tH\x01R\x10commandParameter\x88\x01\x01B\x11\n" +
	"\acommand\x12\x06\x8a\xb5\x18\x02\b\x01B\x14\n" +
	"\x12_command_parameterJ\x04\b\a\x10\b\x1a\x83\x04\n" +
	"\x06Region\x12O\n" +
	"\x04type\x18\x01 \x01(\x0e2..sapient_msg.bsi_flex_335_v2_0.Task.RegionTypeB\x06\x8a\xb5\x18\x02\b\x01H\x00R\x04type\x88\x01\x01\x12*\n" +
	"\tregion_id\x18\x02 \x01(\tB\b\x8a\xb5\x18\x04\b\x01\x10\x01H\x01R\bregionId\x88\x01\x01\x12,\n" +
	"\vregion_name\x18\x03 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x02R\n" +
	"regionName\x88\x01\x01\x12c\n" +
	"\vregion_area\x18\x04 \x01(\v25.sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearingB\x06\x8a\xb5\x18\x02\b\x01H\x03R\n" +
	"regionArea\x88\x01\x01\x12R\n" +
	"\fclass_filter\x18\x05 \x03(\v2/.sapient_msg.bsi_flex_335_v2_0.Task.ClassFilterR\vclassFilter\x12^\n" +
	"\x10behaviour_filter\x18\x06 \x03(\v23.sapient_msg.bsi_flex_335_v2_0.Task.BehaviourFilterR\x0fbehaviourFilterB\a\n" +
	"\x05_typeB\f\n" +
	"\n" +
	"_region_idB\x0e\n" +
	"\f_region_nameB\x0e\n" +
	"\f_region_area\x1a\xe2\x02\n" +
	"\vClassFilter\x12X\n" +
	"\tparameter\x18\x01 \x01(\v2-.sapient_msg.bsi_flex_335_v2_0.Task.ParameterB\x06\x8a\xb5\x18\x02\b\x01H\x00R\tparameter\x88\x01\x01\x12\x1f\n" +
	"\x04type\x18\x02 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x01R\x04type\x88\x01\x01\x12\\\n" +
	"\x10sub_class_filter\x18\x03 \x03(\v22.sapient_msg.bsi_flex_335_v2_0.Task.SubClassFilterR\x0esubClassFilter\x12V\n" +
	"\bpriority\x18\x04 \x01(\x0e25.sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThresholdH\x02R\bpriority\x88\x01\x01B\f\n" +
	"\n" +
	"_parameterB\a\n" +
	"\x05_typeB\v\n" +
	"\t_priority\x1a\xe5\x02\n" +
	"\x0eSubClassFilter\x12X\n" +
	"\tparameter\x18\x01 \x01(\v2-.sapient_msg.bsi_flex_335_v2_0.Task.ParameterB\x06\x8a\xb5\x18\x02\b\x01H\x00R\tparameter\x88\x01\x01\x12\x1f\n" +
	"\x04type\x18\x02 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x01R\x04type\x88\x01\x01\x12\\\n" +
	"\x10sub_class_filter\x18\x03 \x03(\v22.sapient_msg.bsi_flex_335_v2_0.Task.SubClassFilterR\x0esubClassFilter\x12V\n" +
	"\bpriority\x18\x04 \x01(\x0e25.sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThresholdH\x02R\bpriority\x88\x01\x01B\f\n" +
	"\n" +
	"_parameterB\a\n" +
	"\x05_typeB\v\n" +
	"\t_priority\x1a\x80\x02\n" +
	"\x0fBehaviourFilter\x12X\n" +
	"\tparameter\x18\x01 \x01(\v2-.sapient_msg.bsi_flex_335_v2_0.Task.ParameterB\x06\x8a\xb5\x18\x02\b\x01H\x00R\tparameter\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x01R\x04type\x88\x01\x01\x12V\n" +
	"\bpriority\x18\x03 \x01(\x0e25.sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThresholdH\x02R\bpriority\x88\x01\x01B\f\n" +
	"\n" +
	"_parameterB\a\n" +
	"\x05_typeB\v\n" +
	"\t_priority\x1a\xc1\x01\n" +
	"\tParameter\x12\x1f\n" +
	"\x04name\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02\b\x01H\x00R\x04name\x88\x01\x01\x12P\n" +
	"\boperator\x18\x02 \x01(\x0e2'.sapient_msg.bsi_flex_335_v2_0.OperatorB\x06\x8a\xb5\x18\x02\b\x01H\x01R\boperator\x88\x01\x01\x12!\n" +
	"\x05value\x18\x03 \x01(\x02B\x06\x8a\xb5\x18\x02\b\x01H\x02R\x05value\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_operatorB\b\n" +
	"\x06_value\"`\n" +
	"\aControl\x12\x17\n" +
	"\x13CONTROL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCONTROL_START\x10\x01\x12\x10\n" +
	"\fCONTROL_STOP\x10\x02\x12\x11\n" +
	"\rCONTROL_PAUSE\x10\x03\"\x04\b\x04\x10\x04\"\x8f\x01\n" +
	"\x11DiscreteThreshold\x12\"\n" +
	"\x1eDISCRETE_THRESHOLD_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DISCRETE_THRESHOLD_LOW\x10\x01\x12\x1d\n" +
	"\x19DISCRETE_THRESHOLD_MEDIUM\x10\x02\x12\x1b\n" +
	"\x17DISCRETE_THRESHOLD_HIGH\x10\x03\"\xca\x01\n" +
	"\n" +
	"RegionType\x12\x1b\n" +
	"\x17REGION_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cREGION_TYPE_AREA_OF_INTEREST\x10\x01\x12\x16\n" +
	"\x12REGION_TYPE_IGNORE\x10\x02\x12\x18\n" +
	"\x14REGION_TYPE_BOUNDARY\x10\x03\x12&\n" +
	"\"REGION_TYPE_MOBILE_NODE_NO_GO_AREA\x10\x04\x12#\n" +
	"\x1fREGION_TYPE_MOBILE_NODE_GO_AREA\x10\x05B\n" +
	"\n" +
	"\b_task_idB\f\n" +
	"\n" +
	"_task_nameB\x13\n" +
	"\x11_task_descriptionB\x12\n" +
	"\x10_task_start_timeB\x10\n" +
	"\x0e_task_end_timeB\n" +
	"\n" +
	"\b_controlB\n" +
	"\n" +
	"\b_commandB2\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\tTaskProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_task_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sapient_msg_bsi_flex_335_v2_0_task_proto_goTypes = []any{
	(Task_Control)(0),              // 0: sapient_msg.bsi_flex_335_v2_0.Task.Control
	(Task_DiscreteThreshold)(0),    // 1: sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThreshold
	(Task_RegionType)(0),           // 2: sapient_msg.bsi_flex_335_v2_0.Task.RegionType
	(*Task)(nil),                   // 3: sapient_msg.bsi_flex_335_v2_0.Task
	(*Task_Command)(nil),           // 4: sapient_msg.bsi_flex_335_v2_0.Task.Command
	(*Task_Region)(nil),            // 5: sapient_msg.bsi_flex_335_v2_0.Task.Region
	(*Task_ClassFilter)(nil),       // 6: sapient_msg.bsi_flex_335_v2_0.Task.ClassFilter
	(*Task_SubClassFilter)(nil),    // 7: sapient_msg.bsi_flex_335_v2_0.Task.SubClassFilter
	(*Task_BehaviourFilter)(nil),   // 8: sapient_msg.bsi_flex_335_v2_0.Task.BehaviourFilter
	(*Task_Parameter)(nil),         // 9: sapient_msg.bsi_flex_335_v2_0.Task.Parameter
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
	(*LocationOrRangeBearing)(nil), // 11: sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing
	(*LocationList)(nil),           // 12: sapient_msg.bsi_flex_335_v2_0.LocationList
	(*FollowObject)(nil),           // 13: sapient_msg.bsi_flex_335_v2_0.FollowObject
	(Operator)(0),                  // 14: sapient_msg.bsi_flex_335_v2_0.Operator
}
var file_sapient_msg_bsi_flex_335_v2_0_task_proto_depIdxs = []int32{
	10, // 0: sapient_msg.bsi_flex_335_v2_0.Task.task_start_time:type_name -> google.protobuf.Timestamp
	10, // 1: sapient_msg.bsi_flex_335_v2_0.Task.task_end_time:type_name -> google.protobuf.Timestamp
	0,  // 2: sapient_msg.bsi_flex_335_v2_0.Task.control:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.Control
	5,  // 3: sapient_msg.bsi_flex_335_v2_0.Task.region:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.Region
	4,  // 4: sapient_msg.bsi_flex_335_v2_0.Task.command:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.Command
	1,  // 5: sapient_msg.bsi_flex_335_v2_0.Task.Command.detection_threshold:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThreshold
	1,  // 6: sapient_msg.bsi_flex_335_v2_0.Task.Command.detection_report_rate:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThreshold
	1,  // 7: sapient_msg.bsi_flex_335_v2_0.Task.Command.classification_threshold:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThreshold
	11, // 8: sapient_msg.bsi_flex_335_v2_0.Task.Command.look_at:type_name -> sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing
	12, // 9: sapient_msg.bsi_flex_335_v2_0.Task.Command.move_to:type_name -> sapient_msg.bsi_flex_335_v2_0.LocationList
	12, // 10: sapient_msg.bsi_flex_335_v2_0.Task.Command.patrol:type_name -> sapient_msg.bsi_flex_335_v2_0.LocationList
	13, // 11: sapient_msg.bsi_flex_335_v2_0.Task.Command.follow:type_name -> sapient_msg.bsi_flex_335_v2_0.FollowObject
	2,  // 12: sapient_msg.bsi_flex_335_v2_0.Task.Region.type:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.RegionType
	11, // 13: sapient_msg.bsi_flex_335_v2_0.Task.Region.region_area:type_name -> sapient_msg.bsi_flex_335_v2_0.LocationOrRangeBearing
	6,  // 14: sapient_msg.bsi_flex_335_v2_0.Task.Region.class_filter:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.ClassFilter
	8,  // 15: sapient_msg.bsi_flex_335_v2_0.Task.Region.behaviour_filter:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.BehaviourFilter
	9,  // 16: sapient_msg.bsi_flex_335_v2_0.Task.ClassFilter.parameter:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.Parameter
	7,  // 17: sapient_msg.bsi_flex_335_v2_0.Task.ClassFilter.sub_class_filter:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.SubClassFilter
	1,  // 18: sapient_msg.bsi_flex_335_v2_0.Task.ClassFilter.priority:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThreshold
	9,  // 19: sapient_msg.bsi_flex_335_v2_0.Task.SubClassFilter.parameter:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.Parameter
	7,  // 20: sapient_msg.bsi_flex_335_v2_0.Task.SubClassFilter.sub_class_filter:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.SubClassFilter
	1,  // 21: sapient_msg.bsi_flex_335_v2_0.Task.SubClassFilter.priority:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThreshold
	9,  // 22: sapient_msg.bsi_flex_335_v2_0.Task.BehaviourFilter.parameter:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.Parameter
	1,  // 23: sapient_msg.bsi_flex_335_v2_0.Task.BehaviourFilter.priority:type_name -> sapient_msg.bsi_flex_335_v2_0.Task.DiscreteThreshold
	14, // 24: sapient_msg.bsi_flex_335_v2_0.Task.Parameter.operator:type_name -> sapient_msg.bsi_flex_335_v2_0.Operator
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_task_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_task_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_task_proto != nil {
		return
	}
	file_sapient_msg_bsi_flex_335_v2_0_location_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_range_bearing_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_follow_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_registration_proto_init()
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[0].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[1].OneofWrappers = []any{
		(*Task_Command_Request)(nil),
		(*Task_Command_DetectionThreshold)(nil),
		(*Task_Command_DetectionReportRate)(nil),
		(*Task_Command_ClassificationThreshold)(nil),
		(*Task_Command_ModeChange)(nil),
		(*Task_Command_LookAt)(nil),
		(*Task_Command_MoveTo)(nil),
		(*Task_Command_Patrol)(nil),
		(*Task_Command_Follow)(nil),
	}
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[2].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[3].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[4].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[5].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_task_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_task_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_task_proto_depIdxs,
		EnumInfos:         file_sapient_msg_bsi_flex_335_v2_0_task_proto_enumTypes,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_task_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_task_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_task_proto_depIdxs = nil
}
