// Dstl (c) Crown Copyright 2024
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sapient_msg/bsi_flex_335_v2_0/velocity.proto

package sapientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This specifies the units of the scalar speed component of velocity being reported
type SpeedUnits int32

const (
	SpeedUnits_SPEED_UNITS_UNSPECIFIED SpeedUnits = 0 // Units not defined
	SpeedUnits_SPEED_UNITS_MS          SpeedUnits = 1 // Meters per second
	SpeedUnits_SPEED_UNITS_KPH         SpeedUnits = 2 // Kilometers per hour
)

// Enum value maps for SpeedUnits.
var (
	SpeedUnits_name = map[int32]string{
		0: "SPEED_UNITS_UNSPECIFIED",
		1: "SPEED_UNITS_MS",
		2: "SPEED_UNITS_KPH",
	}
	SpeedUnits_value = map[string]int32{
		"SPEED_UNITS_UNSPECIFIED": 0,
		"SPEED_UNITS_MS":          1,
		"SPEED_UNITS_KPH":         2,
	}
)

func (x SpeedUnits) Enum() *SpeedUnits {
	p := new(SpeedUnits)
	*p = x
	return p
}

func (x SpeedUnits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpeedUnits) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_enumTypes[0].Descriptor()
}

func (SpeedUnits) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_enumTypes[0]
}

func (x SpeedUnits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpeedUnits.Descriptor instead.
func (SpeedUnits) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDescGZIP(), []int{0}
}

// Provide velocity as a vector in global cartesian coordinates
// This is a revision of the TIE22 LocationVelocity encoding velocity as per the Location field but with eastings, northings and up for clarity.
// This aligns with the Location (Cartesian) coordinates system.
type ENUVelocity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EastRate       *float64               `protobuf:"fixed64,1,opt,name=east_rate,json=eastRate,proto3,oneof" json:"east_rate,omitempty"`                     // Velocity in the east-axis (x)
	NorthRate      *float64               `protobuf:"fixed64,2,opt,name=north_rate,json=northRate,proto3,oneof" json:"north_rate,omitempty"`                  // Velocity in the north-axis (y)
	UpRate         *float64               `protobuf:"fixed64,3,opt,name=up_rate,json=upRate,proto3,oneof" json:"up_rate,omitempty"`                           // Velocity in the up-axis (z)
	EastRateError  *float64               `protobuf:"fixed64,4,opt,name=east_rate_error,json=eastRateError,proto3,oneof" json:"east_rate_error,omitempty"`    // Error in the velocity in the east-axis
	NorthRateError *float64               `protobuf:"fixed64,5,opt,name=north_rate_error,json=northRateError,proto3,oneof" json:"north_rate_error,omitempty"` // Error in the velocity in the north-axis
	UpRateError    *float64               `protobuf:"fixed64,6,opt,name=up_rate_error,json=upRateError,proto3,oneof" json:"up_rate_error,omitempty"`          // Error in the velocity in the up-axis
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ENUVelocity) Reset() {
	*x = ENUVelocity{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ENUVelocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ENUVelocity) ProtoMessage() {}

func (x *ENUVelocity) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ENUVelocity.ProtoReflect.Descriptor instead.
func (*ENUVelocity) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDescGZIP(), []int{0}
}

func (x *ENUVelocity) GetEastRate() float64 {
	if x != nil && x.EastRate != nil {
		return *x.EastRate
	}
	return 0
}

func (x *ENUVelocity) GetNorthRate() float64 {
	if x != nil && x.NorthRate != nil {
		return *x.NorthRate
	}
	return 0
}

func (x *ENUVelocity) GetUpRate() float64 {
	if x != nil && x.UpRate != nil {
		return *x.UpRate
	}
	return 0
}

func (x *ENUVelocity) GetEastRateError() float64 {
	if x != nil && x.EastRateError != nil {
		return *x.EastRateError
	}
	return 0
}

func (x *ENUVelocity) GetNorthRateError() float64 {
	if x != nil && x.NorthRateError != nil {
		return *x.NorthRateError
	}
	return 0
}

func (x *ENUVelocity) GetUpRateError() float64 {
	if x != nil && x.UpRateError != nil {
		return *x.UpRateError
	}
	return 0
}

// Specify units when ENUVelocity is in use
type ENUVelocityUnits struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EastNorthRateUnits *SpeedUnits            `protobuf:"varint,1,opt,name=east_north_rate_units,json=eastNorthRateUnits,proto3,enum=sapient_msg.bsi_flex_335_v2_0.SpeedUnits,oneof" json:"east_north_rate_units,omitempty"` // Units that velocity is reported in for east and north axis
	UpRateUnits        *SpeedUnits            `protobuf:"varint,2,opt,name=up_rate_units,json=upRateUnits,proto3,enum=sapient_msg.bsi_flex_335_v2_0.SpeedUnits,oneof" json:"up_rate_units,omitempty"`                        // Units that velocity is reported in for up axis
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ENUVelocityUnits) Reset() {
	*x = ENUVelocityUnits{}
	mi := &file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ENUVelocityUnits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ENUVelocityUnits) ProtoMessage() {}

func (x *ENUVelocityUnits) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ENUVelocityUnits.ProtoReflect.Descriptor instead.
func (*ENUVelocityUnits) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDescGZIP(), []int{1}
}

func (x *ENUVelocityUnits) GetEastNorthRateUnits() SpeedUnits {
	if x != nil && x.EastNorthRateUnits != nil {
		return *x.EastNorthRateUnits
	}
	return SpeedUnits_SPEED_UNITS_UNSPECIFIED
}

func (x *ENUVelocityUnits) GetUpRateUnits() SpeedUnits {
	if x != nil && x.UpRateUnits != nil {
		return *x.UpRateUnits
	}
	return SpeedUnits_SPEED_UNITS_UNSPECIFIED
}

var File_sapient_msg_bsi_flex_335_v2_0_velocity_proto protoreflect.FileDescriptor

const file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDesc = "" +
	"\n" +
	",sapient_msg/bsi_flex_335_v2_0/velocity.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fsapient_msg/proto_options.proto\"\xea\x02\n" +
	"\vENUVelocity\x12(\n" +
	"\teast_rate\x18\x01 \x01(\x01B\x06\x8a\xb5\x18\x02\b\x01H\x00R\beastRate\x88\x01\x01\x12*\n" +
	"\n" +
	"north_rate\x18\x02 \x01(\x01B\x06\x8a\xb5\x18\x02\b\x01H\x01R\tnorthRate\x88\x01\x01\x12\x1c\n" +
	"\aup_rate\x18\x03 \x01(\x01H\x02R\x06upRate\x88\x01\x01\x12+\n" +
	"\x0feast_rate_error\x18\x04 \x01(\x01H\x03R\reastRateError\x88\x01\x01\x12-\n" +
	"\x10north_rate_error\x18\x05 \x01(\x01H\x04R\x0enorthRateError\x88\x01\x01\x12'\n" +
	"\rup_rate_error\x18\x06 \x01(\x01H\x05R\vupRateError\x88\x01\x01B\f\n" +
	"\n" +
	"_east_rateB\r\n" +
	"\v_north_rateB\n" +
	"\n" +
	"\b_up_rateB\x12\n" +
	"\x10_east_rate_errorB\x13\n" +
	"\x11_north_rate_errorB\x10\n" +
	"\x0e_up_rate_error\"\xfd\x01\n" +
	"\x10ENUVelocityUnits\x12i\n" +
	"\x15east_north_rate_units\x18\x01 \x01(\x0e2).sapient_msg.bsi_flex_335_v2_0.SpeedUnitsB\x06\x8a\xb5\x18\x02\b\x01H\x00R\x12eastNorthRateUnits\x88\x01\x01\x12R\n" +
	"\rup_rate_units\x18\x02 \x01(\x0e2).sapient_msg.bsi_flex_335_v2_0.SpeedUnitsH\x01R\vupRateUnits\x88\x01\x01B\x18\n" +
	"\x16_east_north_rate_unitsB\x10\n" +
	"\x0e_up_rate_units*^\n" +
	"\n" +
	"SpeedUnits\x12\x1b\n" +
	"\x17SPEED_UNITS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSPEED_UNITS_MS\x10\x01\x12\x13\n" +
	"\x0fSPEED_UNITS_KPH\x10\x02\"\x04\b\x03\x10\x03\"\x04\b\x04\x10\x04B6\n" +
	"#uk.gov.dstl.sapientmsg.bsiflex335v2B\rVelocityProtoP\x01b\x06proto3"

var (
	file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDescData []byte
)

func file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDesc)))
	})
	return file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_goTypes = []any{
	(SpeedUnits)(0),          // 0: sapient_msg.bsi_flex_335_v2_0.SpeedUnits
	(*ENUVelocity)(nil),      // 1: sapient_msg.bsi_flex_335_v2_0.ENUVelocity
	(*ENUVelocityUnits)(nil), // 2: sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits
}
var file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_depIdxs = []int32{
	0, // 0: sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits.east_north_rate_units:type_name -> sapient_msg.bsi_flex_335_v2_0.SpeedUnits
	0, // 1: sapient_msg.bsi_flex_335_v2_0.ENUVelocityUnits.up_rate_units:type_name -> sapient_msg.bsi_flex_335_v2_0.SpeedUnits
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_init() }
func file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_init() {
	if File_sapient_msg_bsi_flex_335_v2_0_velocity_proto != nil {
		return
	}
	file_sapient_msg_proto_options_proto_init()
	file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_msgTypes[0].OneofWrappers = []any{}
	file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDesc), len(file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_depIdxs,
		EnumInfos:         file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_enumTypes,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v2_0_velocity_proto = out.File
	file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v2_0_velocity_proto_depIdxs = nil
}
