// Spec 012 — Node.js seller transport.
// Configures a js-libp2p host with a WSS listener on 127.0.0.1:LISTEN_PORT
// (loopback-only per R0.12). Uses a fresh secp256k1 keypair each run so the
// browser's bootstrap must be regenerated per demo session.
//
// Traces: FR-B05, FR-B06, FR-B08 (JS side).

// Node < 21.12 / < 20.12 polyfill for libp2p@3 upgrader.
type WithResolversShim = {
  withResolvers?: <T>() => {
    promise: Promise<T>
    resolve: (v: T | PromiseLike<T>) => void
    reject: (e?: unknown) => void
  }
}
if (typeof (Promise as unknown as WithResolversShim).withResolvers !== 'function') {
  ;(Promise as unknown as WithResolversShim).withResolvers = function polyfillWithResolvers<T>(): {
    promise: Promise<T>
    resolve: (v: T | PromiseLike<T>) => void
    reject: (e?: unknown) => void
  } {
    let resolve!: (v: T | PromiseLike<T>) => void
    let reject!: (e?: unknown) => void
    const promise = new Promise<T>((res, rej) => { resolve = res; reject = rej })
    return { promise, resolve, reject }
  }
}

import { createLibp2p, type Libp2p } from 'libp2p'
import { webSockets } from '@libp2p/websockets'
import { noise } from '@chainsafe/libp2p-noise'
import { yamux } from '@chainsafe/libp2p-yamux'
import { identify } from '@libp2p/identify'
import { generateKeyPair } from '@libp2p/crypto/keys'
import { NeuronPrivateKey } from '../keylib/private-key.js'

export interface SellerHost {
  readonly libp2p: Libp2p
  readonly privateKey: NeuronPrivateKey
  readonly evmAddress: string
  readonly peerId: string
  readonly wssMultiaddr: string
}

export interface StartOptions {
  readonly port?: number
  readonly hostBind?: string
  /**
   * Public multiaddr hosts to advertise in bootstrap.json. When set, the
   * corresponding `/ip4/<host>/tcp/<port>/ws/p2p/<peerId>` multiaddr is used
   * as the browser-facing dial target instead of libp2p's inferred list.
   *
   * The PeerID suffix is filled in automatically from the running host — the
   * operator only supplies the host portion (e.g. "203.0.113.42" or a DNS
   * name). Accepts comma-separated list via `SELLER_ANNOUNCE` env var; the
   * first entry becomes the bootstrap's `sellerWSSMultiaddr`.
   *
   * Default: none (libp2p's own advertised list is used; behaves as before).
   */
  readonly announceHosts?: string[]
}

/**
 * Start the Node.js seller libp2p host. Returns a handle whose PeerID is
 * derived from a fresh secp256k1 key generated by Spec 002's keylib — so the
 * seller's signing identity (used by the TopicMessage envelope layer) is the
 * same key that secures the Noise handshake.
 */
export async function startSellerHost(opts: StartOptions = {}): Promise<SellerHost> {
  const port = opts.port ?? Number(process.env.SELLER_PORT ?? 8080)
  const bind = opts.hostBind ?? process.env.SELLER_BIND ?? '127.0.0.1'
  const announceHosts = opts.announceHosts
    ?? (process.env.SELLER_ANNOUNCE
      ? process.env.SELLER_ANNOUNCE.split(',').map((s) => s.trim()).filter((s) => s.length > 0)
      : [])

  // Generate a single secp256k1 private key and wrap it both for libp2p
  // (PeerID + Noise identity) and Spec 002's keylib (TopicMessage envelope
  // signing). Both sides see the same 32 bytes so the bootstrap-declared
  // PeerID and EVMAddress derive from the same material.
  const libp2pPrivateKey = await generateKeyPair('secp256k1')
  const privateKey = NeuronPrivateKey.fromBytes(libp2pPrivateKey.raw)

  // libp2p config stays transport-pure: no `announce` override here because
  // that causes the internal peer-store to attempt address resolution for
  // addresses it can't reach from its own POV. The announce only affects the
  // browser-facing bootstrap JSON (below).
  const libp2p = await createLibp2p({
    privateKey: libp2pPrivateKey,
    addresses: { listen: [`/ip4/${bind}/tcp/${port}/ws`] },
    transports: [webSockets()],
    connectionEncrypters: [noise()],
    streamMuxers: [yamux()],
    services: { identify: identify() },
  })
  await libp2p.start()

  // Choose which multiaddr to put in bootstrap.json. libp2p.getMultiaddrs()
  // already emits one multiaddr per listening interface when bind=0.0.0.0,
  // each with its own canonical /p2p/<peerId> encoding. Pick from that list
  // rather than hand-concatenating — the peer-id suffix that `.toString()`
  // produces is NOT guaranteed to be byte-identical to the suffix inside
  // libp2p's own multiaddr objects (the latter encodes the peer-id as a
  // multihash, the former may use a different multibase alias). A mismatch
  // causes Upgrader._encryptOutbound to see `remotePeerId = undefined`.
  const libp2pMultiaddrs = libp2p.getMultiaddrs().map((a) => a.toString())
  let wssMultiaddr: string | undefined
  if (announceHosts.length > 0) {
    // Prefer a libp2p-emitted multiaddr whose host matches the operator's
    // announce host (requires bind=0.0.0.0 so the interface is visible).
    const target = announceHosts[0] ?? ''
    wssMultiaddr = libp2pMultiaddrs.find(
      (a) => a.includes(`/ip4/${target}/`) || a.includes(`/dns4/${target}/`),
    )
    // Fallback: if libp2p didn't list that host (e.g. behind NAT, announce
    // host is a public IP but the interface only has a private address, or
    // the announce is a DNS name libp2p never sees on its interfaces),
    // substitute the host in the first /ws/ multiaddr. Keeps the canonical
    // peer-id suffix; only swaps the host component. Uses /dns4/ when the
    // announce target isn't an IPv4 literal — required because multiaddr
    // /ip4/<non-numeric>/... is malformed and causes downstream dial
    // failures.
    if (!wssMultiaddr) {
      const firstWs = libp2pMultiaddrs.find((a) => a.includes('/ws/'))
      if (firstWs) {
        const isIpv4Literal = /^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(target)
        const prefix = isIpv4Literal ? `/ip4/${target}/` : `/dns4/${target}/`
        wssMultiaddr = firstWs.replace(/^\/(?:ip4|ip6|dns4|dns6|dns)\/[^/]+\//, prefix)
      }
    }
  }
  if (!wssMultiaddr) {
    wssMultiaddr = libp2pMultiaddrs.find((a) => a.includes('/ws/'))
  }
  if (!wssMultiaddr) throw new Error('seller host did not advertise a /ws/ multiaddr')

  return {
    libp2p,
    privateKey,
    evmAddress: privateKey.publicKey().evmAddress().toString(),
    peerId: libp2p.peerId.toString(),
    wssMultiaddr,
  }
}
