import { defineConfig } from 'vite'
import { resolve } from 'node:path'

// Spec 012 — real demo vite config (separate from tests/smoke/).
// Serves index.html and public/bootstrap.json (generated by scripts/run-demo.ts)
// at the same origin (FR-B23, FR-B24). Binds to 127.0.0.1:5173 so browsers
// treat the origin as loopback (exempts ws:// per mixed-content rules).
export default defineConfig({
  root: __dirname,
  publicDir: resolve(__dirname, 'public'),
  resolve: {
    // keylib modules reach `node:crypto` for timingSafeEqual. Map to a
    // browser-only shim. Must match how Vite emits the import; Node's
    // `node:` scheme is preserved as-is in bundled output.
    alias: [
      { find: 'node:crypto', replacement: resolve(__dirname, 'node-crypto-shim.ts') },
    ],
  },
  server: {
    port: 5173,
    host: process.env.VITE_HOST ?? '127.0.0.1',
    strictPort: true,
    // Don't auto-open a browser when running on a headless VPS.
    open: process.env.VITE_HOST ? false : '/',
    // When bound externally (VPS demo), Vite's default host-check returns
    // 403 for any HTTP Host header that isn't in its allowlist. This blocks
    // the browser from reaching the page via a DNS-form URL that resolves
    // to the VPS. Opt into all hosts when VITE_HOST is set (demo-mode);
    // default loopback runs keep Vite's default protection.
    allowedHosts: process.env.VITE_HOST ? true : undefined,
  },
  build: {
    rollupOptions: {
      input: resolve(__dirname, 'index.html'),
    },
    outDir: resolve(__dirname, 'dist'),
    emptyOutDir: true,
  },
})
