// Command ecies-fixture-gen emits a fixture JSON for TS-side ECIES interop tests.
//
// Produces a ciphertext using impl/golang/internal/delivery/EncryptMultiaddrs,
// so any TS client that decrypts the result with the recipient private key
// verifies byte-level compatibility with the Go implementation.
//
// Used once per interop-test update; output path defaults to
// impl/typescript/tests/ecies/fixtures/go-vector.json but can be overridden
// with --out. Safe to regenerate: TS test reads `plaintext` from the fixture,
// so a new random run still passes as long as decrypt succeeds.
//
// Usage:
//
//	go run ./cmd/ecies-fixture-gen --out ../typescript/tests/ecies/fixtures/go-vector.json
package main

import (
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/ethereum/go-ethereum/crypto"

	"github.com/neuron-sdk/neuron-go-sdk/internal/delivery"
)

type fixture struct {
	Note                string   `json:"note"`
	RecipientPrivKeyHex string   `json:"recipientPrivKeyHex"`
	RecipientPubKeyHex  string   `json:"recipientPubKeyHexCompressed"`
	Plaintext           []string `json:"plaintext"`
	CiphertextBase64    string   `json:"ciphertextBase64"`
}

func main() {
	out := flag.String("out", "go-vector.json", "output fixture JSON path")
	flag.Parse()

	// Deterministic recipient private key — known bytes so TS test can hardcode it.
	recipientPrivHex := "1122334455667788990011223344556677889900aabbccddeeff00112233ccdd"
	recipientPrivBytes, err := hex.DecodeString(recipientPrivHex)
	if err != nil {
		fail("hex decode: %v", err)
	}
	recipientPriv, err := crypto.ToECDSA(recipientPrivBytes)
	if err != nil {
		fail("ToECDSA: %v", err)
	}
	recipientPubCompressed := crypto.CompressPubkey(&recipientPriv.PublicKey)

	plaintext := []string{
		"/ip4/127.0.0.1/tcp/8080/ws/p2p/12D3KooWGoVectorFixture0001",
		"/dns4/example.com/tcp/443/wss/p2p/12D3KooWGoVectorFixture0002",
	}
	wire, err := delivery.EncryptMultiaddrs(plaintext, &recipientPriv.PublicKey)
	if err != nil {
		fail("EncryptMultiaddrs: %v", err)
	}

	// Sanity: decrypt with Go, confirm round-trip.
	got, err := delivery.DecryptMultiaddrs(wire, recipientPriv)
	if err != nil {
		fail("DecryptMultiaddrs: %v", err)
	}
	if len(got) != len(plaintext) {
		fail("go decrypt length mismatch: got %d, want %d", len(got), len(plaintext))
	}
	for i := range got {
		if got[i] != plaintext[i] {
			fail("go decrypt[%d]: %q != %q", i, got[i], plaintext[i])
		}
	}

	fx := fixture{
		Note:                "Generated by impl/golang/cmd/ecies-fixture-gen. Regenerate when ECIES primitives change. Tests verify TS decrypt of this Go-produced ciphertext matches `plaintext` byte-for-byte.",
		RecipientPrivKeyHex: recipientPrivHex,
		RecipientPubKeyHex:  hex.EncodeToString(recipientPubCompressed),
		Plaintext:           plaintext,
		CiphertextBase64:    wire,
	}

	absOut, _ := filepath.Abs(*out)
	if err := os.MkdirAll(filepath.Dir(absOut), 0o755); err != nil {
		fail("mkdir: %v", err)
	}
	body, err := json.MarshalIndent(fx, "", "  ")
	if err != nil {
		fail("marshal: %v", err)
	}
	if err := os.WriteFile(absOut, append(body, '\n'), 0o644); err != nil {
		fail("write: %v", err)
	}
	fmt.Printf("wrote %s (%d bytes)\n", absOut, len(body))
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "ecies-fixture-gen: "+format+"\n", args...)
	os.Exit(1)
}
